// Extracted from GitHub Copilot model pricing docs. Prices are USD per 1 million tokens.
// Source: https://docs.github.com/en/enterprise-cloud@latest/copilot/reference/copilot-billing/models-and-pricing

export interface CopilotModelPricing {
    modelId: string;
    displayName: string;
    provider: 'openai' | 'anthropic' | 'google' | 'xai' | 'github';
    releaseStatus: 'GA' | 'Public preview';
    category: 'Lightweight' | 'Versatile' | 'Powerful';
    usdPerMillionInputTokens: number;
    usdPerMillionCachedInputTokens: number;
    usdPerMillionOutputTokens: number;
    usdPerMillionCacheWriteTokens?: number;
    source: string;
}

export const COPILOT_PRICING_SOURCE =
    'https://docs.github.com/en/enterprise-cloud@latest/copilot/reference/copilot-billing/models-and-pricing';

export const COPILOT_MODEL_PRICING: readonly CopilotModelPricing[] = [
    {
        modelId: 'gpt-4.1',
        displayName: 'GPT-4.1',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Versatile',
        usdPerMillionInputTokens: 2,
        usdPerMillionCachedInputTokens: 0.5,
        usdPerMillionOutputTokens: 8,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gpt-5-mini',
        displayName: 'GPT-5 mini',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Lightweight',
        usdPerMillionInputTokens: 0.25,
        usdPerMillionCachedInputTokens: 0.025,
        usdPerMillionOutputTokens: 2,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gpt-5.2',
        displayName: 'GPT-5.2',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Versatile',
        usdPerMillionInputTokens: 1.75,
        usdPerMillionCachedInputTokens: 0.175,
        usdPerMillionOutputTokens: 14,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gpt-5.2-codex',
        displayName: 'GPT-5.2-Codex',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Powerful',
        usdPerMillionInputTokens: 1.75,
        usdPerMillionCachedInputTokens: 0.175,
        usdPerMillionOutputTokens: 14,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gpt-5.3-codex',
        displayName: 'GPT-5.3-Codex',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Powerful',
        usdPerMillionInputTokens: 1.75,
        usdPerMillionCachedInputTokens: 0.175,
        usdPerMillionOutputTokens: 14,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gpt-5.4',
        displayName: 'GPT-5.4',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Versatile',
        usdPerMillionInputTokens: 2.5,
        usdPerMillionCachedInputTokens: 0.25,
        usdPerMillionOutputTokens: 15,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gpt-5.4-mini',
        displayName: 'GPT-5.4 mini',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Lightweight',
        usdPerMillionInputTokens: 0.75,
        usdPerMillionCachedInputTokens: 0.075,
        usdPerMillionOutputTokens: 4.5,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gpt-5.4-nano',
        displayName: 'GPT-5.4 nano',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Lightweight',
        usdPerMillionInputTokens: 0.2,
        usdPerMillionCachedInputTokens: 0.02,
        usdPerMillionOutputTokens: 1.25,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gpt-5.5',
        displayName: 'GPT-5.5',
        provider: 'openai',
        releaseStatus: 'GA',
        category: 'Powerful',
        usdPerMillionInputTokens: 5,
        usdPerMillionCachedInputTokens: 0.5,
        usdPerMillionOutputTokens: 30,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'claude-haiku-4.5',
        displayName: 'Claude Haiku 4.5',
        provider: 'anthropic',
        releaseStatus: 'GA',
        category: 'Versatile',
        usdPerMillionInputTokens: 1,
        usdPerMillionCachedInputTokens: 0.1,
        usdPerMillionCacheWriteTokens: 1.25,
        usdPerMillionOutputTokens: 5,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'claude-sonnet-4',
        displayName: 'Claude Sonnet 4',
        provider: 'anthropic',
        releaseStatus: 'GA',
        category: 'Versatile',
        usdPerMillionInputTokens: 3,
        usdPerMillionCachedInputTokens: 0.3,
        usdPerMillionCacheWriteTokens: 3.75,
        usdPerMillionOutputTokens: 15,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'claude-sonnet-4.5',
        displayName: 'Claude Sonnet 4.5',
        provider: 'anthropic',
        releaseStatus: 'GA',
        category: 'Versatile',
        usdPerMillionInputTokens: 3,
        usdPerMillionCachedInputTokens: 0.3,
        usdPerMillionCacheWriteTokens: 3.75,
        usdPerMillionOutputTokens: 15,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'claude-sonnet-4.6',
        displayName: 'Claude Sonnet 4.6',
        provider: 'anthropic',
        releaseStatus: 'GA',
        category: 'Versatile',
        usdPerMillionInputTokens: 3,
        usdPerMillionCachedInputTokens: 0.3,
        usdPerMillionCacheWriteTokens: 3.75,
        usdPerMillionOutputTokens: 15,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'claude-opus-4.5',
        displayName: 'Claude Opus 4.5',
        provider: 'anthropic',
        releaseStatus: 'GA',
        category: 'Powerful',
        usdPerMillionInputTokens: 5,
        usdPerMillionCachedInputTokens: 0.5,
        usdPerMillionCacheWriteTokens: 6.25,
        usdPerMillionOutputTokens: 25,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'claude-opus-4.6',
        displayName: 'Claude Opus 4.6',
        provider: 'anthropic',
        releaseStatus: 'GA',
        category: 'Powerful',
        usdPerMillionInputTokens: 5,
        usdPerMillionCachedInputTokens: 0.5,
        usdPerMillionCacheWriteTokens: 6.25,
        usdPerMillionOutputTokens: 25,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'claude-opus-4.7',
        displayName: 'Claude Opus 4.7',
        provider: 'anthropic',
        releaseStatus: 'GA',
        category: 'Powerful',
        usdPerMillionInputTokens: 5,
        usdPerMillionCachedInputTokens: 0.5,
        usdPerMillionCacheWriteTokens: 6.25,
        usdPerMillionOutputTokens: 25,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'claude-opus-4.8',
        displayName: 'Claude Opus 4.8',
        provider: 'anthropic',
        releaseStatus: 'GA',
        category: 'Powerful',
        usdPerMillionInputTokens: 5,
        usdPerMillionCachedInputTokens: 0.5,
        usdPerMillionCacheWriteTokens: 6.25,
        usdPerMillionOutputTokens: 25,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gemini-2.5-pro',
        displayName: 'Gemini 2.5 Pro',
        provider: 'google',
        releaseStatus: 'GA',
        category: 'Powerful',
        usdPerMillionInputTokens: 1.25,
        usdPerMillionCachedInputTokens: 0.125,
        usdPerMillionOutputTokens: 10,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gemini-3-flash',
        displayName: 'Gemini 3 Flash',
        provider: 'google',
        releaseStatus: 'Public preview',
        category: 'Lightweight',
        usdPerMillionInputTokens: 0.5,
        usdPerMillionCachedInputTokens: 0.05,
        usdPerMillionOutputTokens: 3,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'gemini-3.1-pro',
        displayName: 'Gemini 3.1 Pro',
        provider: 'google',
        releaseStatus: 'Public preview',
        category: 'Powerful',
        usdPerMillionInputTokens: 2,
        usdPerMillionCachedInputTokens: 0.2,
        usdPerMillionOutputTokens: 12,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'grok-code-fast-1',
        displayName: 'Grok Code Fast 1',
        provider: 'xai',
        releaseStatus: 'GA',
        category: 'Lightweight',
        usdPerMillionInputTokens: 0.2,
        usdPerMillionCachedInputTokens: 0.02,
        usdPerMillionOutputTokens: 1.5,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'raptor-mini',
        displayName: 'Raptor mini',
        provider: 'github',
        releaseStatus: 'Public preview',
        category: 'Versatile',
        usdPerMillionInputTokens: 0.25,
        usdPerMillionCachedInputTokens: 0.025,
        usdPerMillionOutputTokens: 2,
        source: COPILOT_PRICING_SOURCE,
    },
    {
        modelId: 'goldeneye',
        displayName: 'Goldeneye',
        provider: 'github',
        releaseStatus: 'Public preview',
        category: 'Powerful',
        usdPerMillionInputTokens: 1.25,
        usdPerMillionCachedInputTokens: 0.125,
        usdPerMillionOutputTokens: 10,
        source: COPILOT_PRICING_SOURCE,
    },
];
