/**
 * Core TypeScript types for diff comments in the web UI.
 * Browser-compatible with no platform dependencies.
 *
 * Selection and context types are re-exported from forge.
 * CoC-specific types (DiffComment, DiffCommentsData) are defined here.
 */

// Re-export diff selection/context types from forge
export type { DiffCommentSelection, DiffCommentContext } from '@plusplusoneplusplus/forge/editor/types';

import type { CommentCategory } from './comment-constants';
import { ALL_COMMENT_CATEGORIES, resolveCommentCategory } from './comment-constants';

// ============================================================================
// Diff Comment Types
// ============================================================================

export type DiffCommentStatus = 'open' | 'resolved' | 'orphaned';

export type DiffCommentCategory = CommentCategory;

export const ALL_DIFF_CATEGORIES: DiffCommentCategory[] = [...ALL_COMMENT_CATEGORIES];

/** Get category from a DiffComment (field first, then text prefix fallback). */
export function getDiffCommentCategory(comment: DiffComment): DiffCommentCategory {
    return resolveCommentCategory(comment.category, comment.comment);
}

/**
 * A single comment on a diff in the web UI.
 */
export interface DiffComment {
    /** Unique identifier (UUID) */
    id: string;
    /** Identifies the diff (repository, file, and ref range) this comment belongs to */
    context: import('@plusplusoneplusplus/forge/editor/types').DiffCommentContext;
    /** Selection range within the rendered diff */
    selection: import('@plusplusoneplusplus/forge/editor/types').DiffCommentSelection;
    selectedText: string;
    /** User's comment content */
    comment: string;
    status: DiffCommentStatus;
    /** ISO timestamp when created */
    createdAt: string;
    /** ISO timestamp when last updated */
    updatedAt: string;
    author?: string;
    category?: DiffCommentCategory;
    /** Optional anchor for robust location tracking after diff changes */
    anchor?: import('@plusplusoneplusplus/forge/editor/types').CommentAnchor;
    /** Threaded replies to this comment */
    replies?: DiffCommentReply[];
    /** AI-generated clarification response */
    aiResponse?: string;
}

export interface DiffCommentReply {
    /** Unique identifier (UUID) */
    id: string;
    author: string;
    text: string;
    /** ISO timestamp when created */
    createdAt: string;
    /** Whether this reply was generated by AI */
    isAI?: boolean;
}

/**
 * Container for all comments on a single diff.
 */
export interface DiffCommentsData {
    /** Stable key identifying the diff (e.g. "<repositoryId>:<filePath>:<oldRef>..<newRef>") */
    diffId: string;
    comments: DiffComment[];
    /** Schema version for forward compatibility */
    version: number;
}
