/**
 * Core TypeScript types for task comments in the web UI.
 * Browser-compatible with no platform dependencies.
 *
 * Selection, anchor, and relocation types are re-exported from forge.
 * CoC-specific types (TaskComment, TaskCommentsData) are defined here.
 */

// Re-export anchor/selection types from forge
export type { CommentSelection, CommentAnchor } from '@plusplusoneplusplus/forge/editor/types';

import type { CommentCategory } from './comment-constants';
import { ALL_COMMENT_CATEGORIES, resolveCommentCategory } from './comment-constants';

// ============================================================================
// Task Comment Types
// ============================================================================

export type TaskCommentStatus = 'open' | 'resolved';

export type TaskCommentCategory = CommentCategory;

// ============================================================================
// Category Constants
// ============================================================================

export interface CategoryInfo {
    label: string;
    icon: string;
}

export const CATEGORY_INFO: Record<TaskCommentCategory, CategoryInfo> = {
    bug:        { label: 'Bug',        icon: '🐛' },
    question:   { label: 'Question',   icon: '❓' },
    suggestion: { label: 'Suggestion', icon: '💡' },
    praise:     { label: 'Praise',     icon: '🌟' },
    nitpick:    { label: 'Nitpick',    icon: '🔍' },
    general:    { label: 'General',    icon: '💬' },
};

export const ALL_CATEGORIES: TaskCommentCategory[] = [...ALL_COMMENT_CATEGORIES];

/** Get category from a TaskComment (field first, then text prefix fallback). */
export function getCommentCategory(comment: TaskComment): TaskCommentCategory {
    return resolveCommentCategory(comment.category, comment.comment);
}

/**
 * A single comment on a task document in the web UI.
 */
export interface TaskComment {
    /** Unique identifier (UUID) */
    id: string;
    taskId: string;
    /** Selection range in the file */
    selection: import('@plusplusoneplusplus/forge/editor/types').CommentSelection;
    selectedText: string;
    /** User's comment content */
    comment: string;
    status: TaskCommentStatus;
    /** ISO timestamp when created */
    createdAt: string;
    /** ISO timestamp when last updated */
    updatedAt: string;
    author?: string;
    category?: TaskCommentCategory;
    /** Optional anchor for robust location tracking after content changes */
    anchor?: import('@plusplusoneplusplus/forge/editor/types').CommentAnchor;
    /** Threaded replies to this comment */
    replies?: TaskCommentReply[];
    /** AI-generated clarification response */
    aiResponse?: string;
}

export interface TaskCommentReply {
    /** Unique identifier (UUID) */
    id: string;
    author: string;
    text: string;
    /** ISO timestamp when created */
    createdAt: string;
    /** Whether this reply was generated by AI */
    isAI?: boolean;
}

/**
 * Container for all comments on a single task.
 */
export interface TaskCommentsData {
    taskId: string;
    comments: TaskComment[];
    /** Schema version for forward compatibility */
    version: number;
}
