export type {
    KnownWorkItemStatus,
    WorkItemStatus,
    WorkItemSource,
    WorkItemPriority,
    WorkItemType,
    WorkItemTrackerKind,
    WorkItemGitHubTrackerMetadata,
    WorkItemGitHubMirrorMetadata,
    WorkItemAzureBoardsTrackerMetadata,
    WorkItemAzureBoardsMirrorMetadata,
    WorkItemTrackerMetadata,
    WorkItemSyncProvider,
    WorkItemSyncRemoteIdentity,
    WorkItemSyncParentReference,
    WorkItemContentVersionSource,
    WorkItemPlan,
    WorkItemPlanVersion,
    WorkItemPlanVersionComparison,
    WorkItemPlanVersionDiffChunk,
    WorkItemExecution,
    WorkItem,
    WorkItemIndexEntry,
    WorkItemFilter,
    WorkItemStore,
    ReviewComment,
} from './types';

export {
    WORK_ITEM_STATUSES,
    WORK_ITEM_TYPES,
    WORK_ITEM_TRACKER_KINDS,
    TERMINAL_WORK_ITEM_STATUSES,
    VALID_TRANSITIONS,
    isKnownWorkItemStatus,
    isTerminalStatus,
    isValidTransition,
    getOwnWorkItemTrackerKind,
    toIndexEntry,
} from './types';

export { FileWorkItemStore, type FileWorkItemStoreOptions, createWorkItemStore } from './work-item-store';
export {
    DEFAULT_WORK_ITEM_SYNC_PROVIDER,
    SUPPORTED_WORK_ITEM_SYNC_PROVIDERS,
    WORK_ITEM_SYNC_MAX_ITEMS,
    detectWorkItemSyncProviderFromRemoteUrl,
    isSupportedWorkItemSyncProvider,
    unavailableWorkItemSyncProviderStatus,
    type WorkItemSyncProviderAdapter,
    type WorkItemSyncProviderContext,
} from './work-item-sync-provider';
export {
    buildGitHubWorkItemIssueUpdate,
    buildGitHubWorkItemLabels,
    buildGitHubWorkItemSyncMetadata,
    formatGitHubWorkItemSyncMetadataBlock,
    hasExactlyOneGitHubWorkItemSyncMetadataBlock,
    parseGitHubWorkItemIssue,
    parseGitHubWorkItemSyncMetadataBlocks,
    stripGitHubWorkItemSyncMetadataBlocks,
    upsertGitHubWorkItemSyncMetadataBlock,
    type GitHubIssueLabel,
    type GitHubWorkItemIssueSnapshot,
    type GitHubWorkItemIssueUpdate,
    type GitHubWorkItemSyncMetadata,
    type ParseGitHubWorkItemSyncMetadataResult,
    type ParsedGitHubWorkItemIssue,
} from './work-item-sync-github-issue';
export {
    COC_STATUS_TO_GITHUB_STATE,
    GITHUB_STATE_TO_COC_STATUS,
    mapGitHubStateToWorkItemStatus,
    mapWorkItemStatusToGitHubState,
    type GitHubIssueState,
} from './work-item-sync-github-mapping';
export {
    GhCliGitHubWorkItemIssueTransport,
    convertLocalEpicTreeToGitHubBacked,
    createGitHubWorkItemSyncProviderAdapter,
    createGitHubIssueForLocalChild,
    createGitHubIssueForLocalEpicRoot,
    deleteGitHubEpicMirrorTree,
    detachGitHubEpicTreeToLocalOnly,
    importGitHubEpicTreeAsWorkItems,
    parentReferenceForGitHubMirrorChild,
    updateGitHubIssueForLocalMirror,
    type ConvertGitHubEpicTreeTrackerResult,
    type CreateGitHubIssueForLocalChildOptions,
    type CreateGitHubIssueForLocalChildResult,
    type CreateGitHubIssueForLocalEpicRootOptions,
    type CreateGitHubWorkItemSyncProviderOptions,
    type GitHubWorkItemIssue,
    type GitHubWorkItemIssueListFilters,
    type GitHubWorkItemIssueTransport,
    type ImportGitHubEpicTreeOptions,
    type ImportGitHubEpicTreeResult,
    type UpdateGitHubIssueForLocalMirrorOptions,
    type UpdateGitHubIssueForLocalMirrorResult,
} from './work-item-sync-github-provider';
export {
    AzureBoardsRestWorkItemTransport,
    azureBoardsProjectFromStatus,
    azureBoardsRemoteWorkItemIdForLocalItem,
    azureBoardsWorkItemIdFromUrl,
    createAzureBoardsWorkItemForLocalChild,
    createAzureBoardsWorkItemSyncProviderAdapter,
    deleteAzureBoardsEpicMirrorTree,
    importAzureBoardsEpicTreeAsWorkItems,
    resolveAzureDevOpsCliAccessToken,
    updateAzureBoardsWorkItemForLocalMirror,
    type AvailableAzureBoardsWorkItemSyncProject,
    type AzureBoardsAccessTokenResolver,
    type AzureBoardsSyncWarning,
    type AzureBoardsWorkItem,
    type AzureBoardsWorkItemCreateInput,
    type AzureBoardsWorkItemRelation,
    type AzureBoardsWorkItemTransport,
    type AzureBoardsWorkItemUpdateInput,
    type CreateAzureBoardsWorkItemSyncProviderOptions,
    type CreateAzureBoardsWorkItemForLocalChildOptions,
    type CreateAzureBoardsWorkItemForLocalChildResult,
    type ImportAzureBoardsEpicTreeOptions,
    type ImportAzureBoardsEpicTreeResult,
    type UpdateAzureBoardsWorkItemForLocalMirrorOptions,
    type UpdateAzureBoardsWorkItemForLocalMirrorResult,
} from './work-item-sync-azure-boards-provider';
export {
    AZURE_BOARDS_COC_TYPE_TAG_PREFIX,
    AZURE_BOARDS_TAG_SEPARATOR,
    AZURE_BOARDS_UNKNOWN_PRIORITY_TAG_PREFIX,
    AZURE_BOARDS_UNKNOWN_TYPE_TAG_PREFIX,
    formatAzureBoardsTags,
    mapAzureBoardsPriorityToWorkItemPriority,
    mapAzureBoardsStateToWorkItemStatus,
    mapAzureBoardsTypeToCocWorkItemType,
    mapCocWorkItemTypeToAzureBoardsType,
    mapWorkItemPriorityToAzureBoardsPriority,
    mapWorkItemStatusToAzureBoardsState,
    parseAzureBoardsTags,
    type AzureBoardsPriorityMapping,
    type AzureBoardsRemoteTypeMapping,
    type AzureBoardsTypeMapping,
} from './work-item-sync-azure-boards-mapping';
export {
    DEFAULT_WORK_ITEM_GITHUB_PULL_INTERVAL_MINUTES,
    WorkItemGitHubPullPoller,
    type WorkItemGitHubPullPollerOptions,
    type WorkItemGitHubPullPollerTimerApi,
    type WorkItemGitHubPullPollError,
    type WorkItemGitHubPullWorkspaceResult,
} from './work-item-github-pull-poller';
export {
    DEFAULT_WORK_ITEM_AZURE_BOARDS_PULL_INTERVAL_MINUTES,
    WorkItemAzureBoardsPullPoller,
    type WorkItemAzureBoardsPullPollerOptions,
    type WorkItemAzureBoardsPullPollerTimerApi,
    type WorkItemAzureBoardsPullPollError,
    type WorkItemAzureBoardsPullWorkspaceResult,
} from './work-item-azure-boards-pull-poller';
export {
    WORK_ITEM_SYNC_CONFLICT_CODE,
    buildAzureBoardsWorkItemSyncConflict,
    buildGitHubWorkItemSyncConflict,
    type BuildAzureBoardsWorkItemSyncConflictOptions,
    type BuildGitHubWorkItemSyncConflictOptions,
} from './work-item-sync-conflict';
export {
    executeWorkItem,
    handleWorkItemTaskComplete,
    buildExecutionPrompt,
    resolveWorkItemComments,
    isResolveSessionCategory,
    type EnqueueFunction,
    type ExecuteWorkItemOptions,
    type ResolveWorkItemCommentsOptions,
} from './work-item-executor';

export type { WorkItemChange, WorkItemChangeCommit } from './types';
