/**
 * Work Item Types
 *
 * A CoC work item is a tracked unit of work with a description, status lifecycle,
 * and an AI-generated plan. Work items can be created manually, spawned from chat
 * sessions, or generated by schedulers.
 *
 * Lifecycle: created → planning → readyToExecute → executing → aiDone → done | failed
 *
 * Each work item may have a plan with version history, and links to queue tasks
 * for execution tracking.
 */

// ============================================================================
// Status & Source Enums
// ============================================================================

/** Work item lifecycle status. */
export type WorkItemStatus = 'created' | 'planning' | 'readyToExecute' | 'executing' | 'aiDone' | 'aiFailed' | 'done' | 'failed';

/** All valid work item statuses (useful for validation). */
export const WORK_ITEM_STATUSES: readonly WorkItemStatus[] = Object.freeze([
    'created', 'planning', 'readyToExecute', 'executing', 'aiDone', 'aiFailed', 'done', 'failed',
]);

/** Terminal statuses that cannot transition further. */
export const TERMINAL_WORK_ITEM_STATUSES: ReadonlySet<WorkItemStatus> = new Set([
    'done', 'failed',
]);

/** How the work item was created. */
export type WorkItemSource = 'manual' | 'chat' | 'schedule';

/** Priority levels for work items. */
export type WorkItemPriority = 'high' | 'normal' | 'low';

/** Work item type — distinguishes bugs from regular work items. */
export type WorkItemType = 'work-item' | 'bug';

/** All valid work item types (useful for validation). */
export const WORK_ITEM_TYPES: readonly WorkItemType[] = Object.freeze(['work-item', 'bug']);

// ============================================================================
// Plan Types
// ============================================================================

/** Current plan attached to a work item. */
export interface WorkItemPlan {
    /** Plan version number (1-based, monotonically increasing). */
    version: number;
    /** Markdown plan content. */
    content: string;
    /** ISO timestamp of last update. */
    updatedAt: string;
    /** Who last resolved/updated the plan. */
    resolvedBy?: 'user' | 'ai';
}

/** A historical version of a plan. */
export interface WorkItemPlanVersion {
    /** Version number. */
    version: number;
    /** Markdown plan content. */
    content: string;
    /** ISO timestamp when this version was created. */
    createdAt: string;
    /** Who created this version. */
    resolvedBy?: 'user' | 'ai';
    /** Summary of changes from previous version. */
    summary?: string;
}

// ============================================================================
// Execution Tracking
// ============================================================================

/** Record of a single execution attempt for a work item. */
export interface WorkItemExecution {
    /** Queue task ID. */
    taskId: string;
    /** AI process ID (assigned when task starts executing). */
    processId?: string;
    /** ISO timestamp when execution started. */
    startedAt: string;
    /** ISO timestamp when execution completed. */
    completedAt?: string;
    /** Outcome of this execution. */
    status: 'running' | 'completed' | 'failed' | 'cancelled';
    /** Error message if execution failed. */
    error?: string;
    /** Whether this execution was triggered automatically after comment resolution. */
    autoReExecuted?: boolean;
    /** Session category (e.g. 'generating-code', 'resolve-plan-comments', 'resolve-commit-comments'). */
    sessionCategory?: string;
    /** Descriptive title for this execution (e.g. 'Code Implement', 'Resolve comments for Run #2'). */
    title?: string;
}

// ============================================================================
// Change Tracking
// ============================================================================

/** A lightweight git commit record attached to a Change entry. */
export interface WorkItemChangeCommit {
    sha: string;
    message: string;
    author?: string;
    date?: string;
}

/**
 * A Change bundles one plan version with the git commits produced during
 * the corresponding execution cycle.
 *
 * Lifecycle:
 *   open   — plan has been saved; execution may or may not have started
 *   closed — execution completed (successfully or not); commits attached
 */
export interface WorkItemChange {
    /** Unique identifier (UUID). */
    id: string;
    /** Plan version number that was active when this Change was opened. */
    planVersion: number;
    /** Git commits produced during this Change's execution window. */
    commits: WorkItemChangeCommit[];
    /** ISO timestamp when this Change was opened (plan saved / execution queued). */
    startedAt: string;
    /** ISO timestamp when this Change was closed (execution completed). */
    completedAt?: string;
    /** Queue task ID linked to this Change (set when execution starts). */
    taskId?: string;
    /** Git HEAD SHA captured immediately before execution enqueued. */
    headBefore?: string;
    /** Whether this Change is still tracking an active execution. */
    status: 'open' | 'closed';
}

// ============================================================================
// Work Item
// ============================================================================

/** A tracked unit of work with a plan and execution history. */
export interface WorkItem {
    /** Unique identifier (UUID). */
    id: string;
    /** Sequential human-readable number (e.g. 1 → displayed as WI-1). Per-repo, never reused. */
    workItemNumber?: number;
    /** Workspace/repo this work item belongs to. */
    repoId: string;
    /** Short title. */
    title: string;
    /** Markdown description of what needs to be done. */
    description: string;
    /** Current lifecycle status. */
    status: WorkItemStatus;
    /** Work item type — 'work-item' (default) or 'bug'. */
    type?: WorkItemType;
    /** ISO timestamp when the work item was created. */
    createdAt: string;
    /** ISO timestamp of last modification. */
    updatedAt: string;
    /** ISO timestamp when the work item reached a terminal state. */
    completedAt?: string;

    // Source tracking
    /** How this work item was created. */
    source: WorkItemSource;
    /** ID of the source entity (e.g., processId for chat, scheduleId for schedule). */
    sourceId?: string;

    // Plan
    /** Current plan version (if any). */
    plan?: WorkItemPlan;

    // Execution tracking
    /** Queue task ID of the currently executing task. */
    taskId?: string;
    /** AI process ID of the currently executing task. */
    processId?: string;
    /** History of all execution attempts. */
    executionHistory?: WorkItemExecution[];
    /** Change tracking entries (plan version + commits per execution cycle). */
    changes?: WorkItemChange[];

    // Metadata
    /** Freeform tags for categorization. */
    tags?: string[];
    /** Priority level. */
    priority?: WorkItemPriority;
    /** Whether to auto-execute when status reaches 'readyToExecute'. */
    autoExecute?: boolean;
    /** Whether to auto-resolve diff comments via AI and re-execute when all are resolved. */
    autoResolveAndReExecute?: boolean;
    /** Number of auto-resolve-then-re-execute cycles completed in the current change. Used as a loop guard. */
    autoReExecuteCycles?: number;

    // Review
    /** Review comments for the AIDone state. */
    reviewComments?: ReviewComment[];
}

// ============================================================================
// Review Comments (for AIDone state)
// ============================================================================

/** A review comment left by the user after AI completes execution. */
export interface ReviewComment {
    /** Unique identifier. */
    id: string;
    /** Comment text. */
    text: string;
    /** ISO timestamp when comment was created. */
    createdAt: string;
    /** Whether this comment has been addressed. */
    resolved?: boolean;
}

// ============================================================================
// Index Entry (lightweight, for listing)
// ============================================================================

/** Lightweight work item summary for index listing (avoids loading full data). */
export interface WorkItemIndexEntry {
    id: string;
    /** Sequential human-readable number (e.g. 1 → displayed as WI-1). */
    workItemNumber?: number;
    repoId: string;
    title: string;
    status: WorkItemStatus;
    type?: WorkItemType;
    source: WorkItemSource;
    priority?: WorkItemPriority;
    planVersion?: number;
    createdAt: string;
    updatedAt: string;
    completedAt?: string;
    /** ISO timestamp of the most recent execution activity (derived from executionHistory). */
    lastRunAt?: string;
    tags?: string[];
}

// ============================================================================
// Store Interface
// ============================================================================

/** Filter criteria for listing work items. */
export interface WorkItemFilter {
    /** Filter by status(es). */
    status?: WorkItemStatus | WorkItemStatus[];
    /** Filter by source. */
    source?: WorkItemSource;
    /** Filter by repo/workspace ID. */
    repoId?: string;
    /** Filter by priority. */
    priority?: WorkItemPriority;
    /** Filter by tag (any match). */
    tags?: string[];
    /** Filter by type. */
    type?: WorkItemType;
}

/** Abstract store interface for work item persistence. */
export interface WorkItemStore {
    // CRUD
    addWorkItem(item: WorkItem): Promise<void>;
    getWorkItem(id: string, repoId?: string): Promise<WorkItem | undefined>;
    updateWorkItem(id: string, updates: Partial<Omit<WorkItem, 'id' | 'repoId' | 'createdAt'>>): Promise<WorkItem | undefined>;
    removeWorkItem(id: string): Promise<boolean>;
    listWorkItems(filter?: WorkItemFilter): Promise<WorkItemIndexEntry[]>;

    // Plan versioning
    getPlanVersions(workItemId: string): Promise<WorkItemPlanVersion[]>;
    getPlanVersion(workItemId: string, version: number): Promise<WorkItemPlanVersion | undefined>;
    savePlanVersion(workItemId: string, plan: WorkItemPlanVersion): Promise<void>;

    // Execution history
    addExecution(workItemId: string, execution: WorkItemExecution): Promise<void>;
    updateExecution(workItemId: string, taskId: string, updates: Partial<WorkItemExecution>): Promise<void>;

    // Change tracking
    addChange(workItemId: string, change: WorkItemChange): Promise<void>;
    updateChange(workItemId: string, changeId: string, updates: Partial<WorkItemChange>): Promise<void>;
    getChanges(workItemId: string): Promise<WorkItemChange[]>;
}

// ============================================================================
// Helpers
// ============================================================================

/** Check if a work item status is terminal (done or failed). */
export function isTerminalStatus(status: WorkItemStatus): boolean {
    return TERMINAL_WORK_ITEM_STATUSES.has(status);
}

/** Valid status transitions. */
export const VALID_TRANSITIONS: Record<WorkItemStatus, readonly WorkItemStatus[]> = {
    created:        ['planning', 'readyToExecute', 'done', 'failed'],
    planning:       ['readyToExecute', 'created', 'done', 'failed'],
    readyToExecute: ['executing', 'planning', 'done', 'failed'],
    executing:      ['aiDone', 'aiFailed', 'failed', 'readyToExecute'],
    aiDone:         ['readyToExecute', 'done', 'failed'],
    aiFailed:       ['readyToExecute', 'created', 'failed'],  // Retry or give up
    done:           ['created'],      // Allow re-opening
    failed:         ['created'],      // Allow re-opening
};

/** Check if a status transition is valid. */
export function isValidTransition(from: WorkItemStatus, to: WorkItemStatus): boolean {
    return VALID_TRANSITIONS[from]?.includes(to) ?? false;
}

/**
 * Derive the most recent execution timestamp from a work item's execution history.
 * Prefers `completedAt`, then `startedAt` from the latest entry.
 * Returns `undefined` if there is no execution history.
 */
export function getLastRunTime(executionHistory: WorkItemExecution[] | undefined): string | undefined {
    if (!executionHistory || executionHistory.length === 0) return undefined;
    let latest: string | undefined;
    for (const exec of executionHistory) {
        const ts = exec.completedAt ?? exec.startedAt;
        if (!latest || ts > latest) latest = ts;
    }
    return latest;
}

/** Extract an index entry from a full work item. */
export function toIndexEntry(item: WorkItem): WorkItemIndexEntry {
    return {
        id: item.id,
        workItemNumber: item.workItemNumber,
        repoId: item.repoId,
        title: item.title,
        status: item.status,
        type: item.type,
        source: item.source,
        priority: item.priority,
        planVersion: item.plan?.version,
        createdAt: item.createdAt,
        updatedAt: item.updatedAt,
        completedAt: item.completedAt,
        lastRunAt: getLastRunTime(item.executionHistory),
        tags: item.tags,
    };
}
