/**
 * Work Item Types
 *
 * A CoC work item is a tracked unit of work with a description, status lifecycle,
 * and an AI-generated plan. Work items can be created manually, spawned from chat
 * sessions, or generated by schedulers.
 *
 * Lifecycle: created → planning → readyToExecute → executing → aiDone → done | failed
 *
 * Each work item may have a plan with version history, and links to queue tasks
 * for execution tracking.
 */

// ============================================================================
// Status & Source Enums
// ============================================================================

/**
 * Work item lifecycle status.
 *
 * `drafting` is an optional pre-planning phase used by `goal` items while their
 * spec is developed interactively (e.g. a Ralph grilling session). Other types
 * skip it and start at `created`.
 */
export type KnownWorkItemStatus = 'created' | 'drafting' | 'planning' | 'readyToExecute' | 'executing' | 'aiDone' | 'aiFailed' | 'done' | 'failed';
export type WorkItemStatus = KnownWorkItemStatus | (string & {});

/** All valid work item statuses (useful for validation). */
export const WORK_ITEM_STATUSES: readonly KnownWorkItemStatus[] = Object.freeze([
    'created', 'drafting', 'planning', 'readyToExecute', 'executing', 'aiDone', 'aiFailed', 'done', 'failed',
]);

/** Terminal statuses that cannot transition further. */
export const TERMINAL_WORK_ITEM_STATUSES: ReadonlySet<KnownWorkItemStatus> = new Set([
    'done', 'failed',
]);

/** How the work item was created. */
export type WorkItemSource = 'manual' | 'chat' | 'schedule';

/** Priority levels for work items. */
export type WorkItemPriority = 'high' | 'normal' | 'low';

/**
 * Work item type.
 * - `work-item`, `bug`, `goal`: leaf types that can be planned and executed.
 *   A `goal` is outcome-oriented and may first be spec'd out via a drafting
 *   phase before execution.
 * - `epic`, `feature`, `pbi`: hierarchy container types (planning only).
 */
export type WorkItemType = 'work-item' | 'bug' | 'goal' | 'epic' | 'feature' | 'pbi';

/** All valid work item types (useful for validation). */
export const WORK_ITEM_TYPES: readonly WorkItemType[] = Object.freeze([
    'work-item', 'bug', 'goal', 'epic', 'feature', 'pbi',
]);

/** Container types — hierarchy planning containers, not directly executable. */
export const HIERARCHY_CONTAINER_TYPES: ReadonlySet<WorkItemType> = new Set<WorkItemType>([
    'epic', 'feature', 'pbi',
]);

/** Leaf types — executable items that support plan/execution flows. */
export const LEAF_WORK_ITEM_TYPES: ReadonlySet<WorkItemType> = new Set<WorkItemType>([
    'work-item', 'bug', 'goal',
]);

/**
 * Allowed parent types for each work item type.
 * An empty array means the type cannot have a parent (top-level only).
 * Any item may be temporarily unparented (parentId absent) regardless of type.
 */
export const ALLOWED_PARENT_TYPES: Record<WorkItemType, readonly WorkItemType[]> = {
    epic:        [],
    feature:     ['epic'],
    pbi:         ['feature'],
    'work-item': ['pbi'],
    bug:         ['pbi'],
    goal:        ['pbi'],
};

/**
 * Allowed child types for each work item type.
 * An empty array means the type cannot have children.
 */
export const ALLOWED_CHILD_TYPES: Record<WorkItemType, readonly WorkItemType[]> = {
    epic:        ['feature'],
    feature:     ['pbi'],
    pbi:         ['work-item', 'bug', 'goal'],
    'work-item': [],
    bug:         [],
    goal:        [],
};

// ============================================================================
// Tracker Ownership
// ============================================================================

/** Top-level tracker partition for an Epic tree. */
export type WorkItemTrackerKind = 'local-only' | 'github-backed' | 'azure-boards-backed';

/** All valid tracker kinds (useful for validation). */
export const WORK_ITEM_TRACKER_KINDS: readonly WorkItemTrackerKind[] = Object.freeze([
    'local-only', 'github-backed', 'azure-boards-backed',
]);

/** GitHub-backed Epic root metadata. Repository identity is workspace-scoped config, not per Epic. */
export interface WorkItemGitHubTrackerMetadata {
    /** Provider-native issue ID for the imported/pushed Epic root. */
    issueId?: string;
    /** Provider-native issue number for the imported/pushed Epic root. */
    issueNumber?: number;
    /** Browser URL for the imported/pushed Epic root issue. */
    issueUrl?: string;
    /** Last successful GitHub→local pull timestamp for this Epic tree. */
    lastPulledAt?: string;
}

/** Per-item read-mirror details for a GitHub-backed Epic tree. */
export interface WorkItemGitHubMirrorMetadata {
    /** Provider-native issue ID for this mirrored item. */
    issueId?: string;
    /** Provider-native issue number for this mirrored item. */
    issueNumber: number;
    /** Browser URL for this mirrored GitHub issue. */
    issueUrl?: string;
    /** Mirrored GitHub issue open/closed state. CoC lifecycle status stays local. */
    state?: string;
    /** Provider updated-at timestamp for the mirrored issue. */
    updatedAt?: string;
    /** Last successful GitHub→local pull timestamp for this item. */
    lastPulledAt?: string;
}

/** Azure Boards-backed Epic root metadata. Organization/project identity is workspace-scoped config. */
export interface WorkItemAzureBoardsTrackerMetadata {
    /** Azure Boards work item ID for the imported/pushed Epic root. */
    workItemId?: number;
    /** Browser URL for the Azure Boards work item. */
    workItemUrl?: string;
    /** Azure Boards revision number from the last successful pull/push. */
    revision?: number;
    /** Provider updated-at timestamp. */
    updatedAt?: string;
    /** Last successful Azure Boards→local pull timestamp for this Epic tree. */
    lastPulledAt?: string;
}

/** Per-item read-mirror details for an Azure Boards-backed Epic tree. */
export interface WorkItemAzureBoardsMirrorMetadata {
    /** Azure Boards work item ID for this mirrored item. */
    workItemId: number;
    /** Browser URL for this mirrored Azure Boards work item. */
    workItemUrl?: string;
    /** Azure Boards revision number from the last successful pull/push. */
    revision?: number;
    /** Mirrored Azure Boards work item type. CoC type is mapped separately. */
    workItemType?: string;
    /** Mirrored Azure Boards state. */
    state?: string;
    /** Provider updated-at timestamp. */
    updatedAt?: string;
    /** Last successful Azure Boards→local pull timestamp for this item. */
    lastPulledAt?: string;
    /** Hash of Azure-owned local fields after the last successful pull/push. Used to warn on remote-wins conflict pulls. */
    lastSyncedLocalFingerprint?: string;
}

/**
 * Tracker identity for a work-item tree.
 *
 * This is set on the Epic root. Descendants inherit the root identity instead of
 * carrying per-item sync ownership.
 */
export type WorkItemTrackerMetadata =
    | { kind: 'local-only' }
    | { kind: 'github-backed'; provider: 'github'; github: WorkItemGitHubTrackerMetadata }
    | { kind: 'azure-boards-backed'; provider: 'azure-boards'; azureBoards: WorkItemAzureBoardsTrackerMetadata };

// ============================================================================
// External Provider Metadata
// ============================================================================

/** External work-item sync provider. */
export type WorkItemSyncProvider = 'github' | 'azure-boards';

/** Remote issue identity encoded in provider-owned metadata such as GitHub issue bodies. */
export interface WorkItemSyncRemoteIdentity {
    /** GitHub owner or future provider account/organization name. */
    owner?: string;
    /** GitHub repository name or future provider repository identity. */
    repo?: string;
    /** Optional provider project identity for providers that need one. */
    projectId?: string;
    /** Provider-native issue/work-item ID. */
    issueId?: string;
    /** Provider-native issue number when available. */
    issueNumber?: number;
    /** Browser URL for the remote issue/work item. */
    issueUrl?: string;
}

/** Parent reference captured in provider-owned metadata for hierarchy reconstruction. */
export interface WorkItemSyncParentReference {
    /** CoC parent work item ID when known. */
    workItemId?: string;
    /** Remote parent issue/work-item ID when known. */
    issueId?: string;
    /** Remote parent issue number when available. */
    issueNumber?: number;
    /** Browser URL for the remote parent. */
    issueUrl?: string;
    /** Remote parent owner when it differs from the child remote. */
    owner?: string;
    /** Remote parent repo when it differs from the child remote. */
    repo?: string;
}

// ============================================================================
// Plan Types
// ============================================================================

/** Source/author category for an immutable work item content version. */
export type WorkItemContentVersionSource = 'user' | 'ai' | 'system' | (string & {});

/** Current plan attached to a work item. */
export interface WorkItemPlan {
    /** Plan version number (1-based, monotonically increasing). */
    version: number;
    /** Explicit pointer to the current immutable content version. Mirrors `version` for plan-backed content. */
    currentVersion?: number;
    /** Markdown plan content. */
    content: string;
    /** ISO timestamp of last update. */
    updatedAt: string;
    /** Who last resolved/updated the plan. */
    resolvedBy?: 'user' | 'ai';
    /** Source that produced the current version. */
    source?: WorkItemContentVersionSource;
    /** Reason this version became current. */
    reason?: string;
    /** Previous version restored into this current version, when applicable. */
    restoredFromVersion?: number;
}

/** A historical version of a plan. */
export interface WorkItemPlanVersion {
    /** Version number. */
    version: number;
    /** Markdown plan content. */
    content: string;
    /** ISO timestamp when this version was created. */
    createdAt: string;
    /** Who created this version. */
    resolvedBy?: 'user' | 'ai';
    /** Source that produced this immutable version. */
    source?: WorkItemContentVersionSource;
    /** Author type for UI/history filtering; defaults to `source`. */
    authorType?: WorkItemContentVersionSource;
    /** Reason this version was created. */
    reason?: string;
    /** Previous version restored into this version, when applicable. */
    restoredFromVersion?: number;
    /** Summary of changes from previous version. */
    summary?: string;
}

/** Line-level diff chunk between two immutable plan/content versions. */
export interface WorkItemPlanVersionDiffChunk {
    type: 'equal' | 'added' | 'removed';
    lines: string[];
}

/** Compare response for two immutable plan/content versions. */
export interface WorkItemPlanVersionComparison {
    base: WorkItemPlanVersion;
    target: WorkItemPlanVersion;
    diff: WorkItemPlanVersionDiffChunk[];
}

// ============================================================================
// Execution Tracking
// ============================================================================

/** User-selected implementation strategy for a Work Item run. */
export type WorkItemExecutionMode = 'one-shot' | 'ralph';

/** AI controls captured at enqueue time for an execution run. */
export interface WorkItemExecutionAiSettings {
    provider?: string;
    model?: string;
    reasoningEffort?: string;
    effortTier?: string;
    autoProviderRouting?: boolean;
}

/** Record of a single execution attempt for a work item. */
export interface WorkItemExecution {
    /** Queue task ID. */
    taskId: string;
    /** AI process ID (assigned when task starts executing). */
    processId?: string;
    /** Immutable plan/content version selected for this execution. */
    planVersion?: number;
    /** Execution mode selected for this run. */
    executionMode?: WorkItemExecutionMode;
    /** Ralph session ID when this run uses Ralph execution. */
    ralphSessionId?: string;
    /** AI provider/model controls captured when the run was enqueued. */
    aiSettings?: WorkItemExecutionAiSettings;
    /** Skill names selected for this run. */
    skillNames?: string[];
    /** ISO timestamp when execution started. */
    startedAt: string;
    /** ISO timestamp when execution completed. */
    completedAt?: string;
    /** Outcome of this execution. */
    status: 'running' | 'completed' | 'failed' | 'cancelled';
    /** Error message if execution failed. */
    error?: string;
    /** Whether this execution was triggered automatically after comment resolution. */
    autoReExecuted?: boolean;
    /** Session category (e.g. 'generating-code', 'resolve-plan-comments', 'resolve-commit-comments'). */
    sessionCategory?: string;
    /** Descriptive title for this execution (e.g. 'Code Implement', 'Resolve comments for Run #2'). */
    title?: string;
    /** Execution kind (e.g. 'pr-generation' for PR creation runs). */
    kind?: string;
    /** PR generation iteration number. */
    prIteration?: number;
    /** URL of the created/updated pull request. */
    prUrl?: string;
}

// ============================================================================
// Change Tracking
// ============================================================================

/** A lightweight git commit record attached to a Change entry. */
export interface WorkItemChangeCommit {
    sha: string;
    message: string;
    author?: string;
    date?: string;
}

/**
 * A Change bundles one plan version with the git commits produced during
 * the corresponding execution cycle.
 *
 * Lifecycle:
 *   open   — plan has been saved; execution may or may not have started
 *   closed — execution completed (successfully or not); commits attached
 */
export interface WorkItemChange {
    /** Unique identifier (UUID). */
    id: string;
    /** Plan version number that was active when this Change was opened. */
    planVersion: number;
    /** Git commits produced during this Change's execution window. */
    commits: WorkItemChangeCommit[];
    /** ISO timestamp when this Change was opened (plan saved / execution queued). */
    startedAt: string;
    /** ISO timestamp when this Change was closed (execution completed). */
    completedAt?: string;
    /** Queue task ID linked to this Change (set when execution starts). */
    taskId?: string;
    /** Git HEAD SHA captured immediately before execution enqueued. */
    headBefore?: string;
    /** Whether this Change is still tracking an active execution. */
    status: 'open' | 'closed';
    /** Git branch name used for this change's PR. */
    branchName?: string;
    /** Pull request number (GitHub/ADO). */
    prNumber?: number;
    /** Pull request URL. */
    prUrl?: string;
    /** Pull request status. */
    prStatus?: 'open' | 'merged' | 'closed';
}

// ============================================================================
// Work Item
// ============================================================================

/** A tracked unit of work with a plan and execution history. */
export interface WorkItem {
    /** Unique identifier (UUID). */
    id: string;
    /** Sequential human-readable number (e.g. 1 → displayed as WI-1). Per-repo, never reused. */
    workItemNumber?: number;
    /** Workspace/repo this work item belongs to. */
    repoId: string;
    /** Short title. */
    title: string;
    /** Markdown description of what needs to be done. */
    description: string;
    /** Current lifecycle status. */
    status: WorkItemStatus;
    /** Work item type — 'work-item' (default), 'bug', 'goal', 'epic', 'feature', or 'pbi'. */
    type?: WorkItemType;
    /** Parent work item ID (hierarchy). Only set when hierarchy is enabled. */
    parentId?: string;
    /** Epic-rooted tracker identity. Set on Epic roots; descendants inherit it. */
    tracker?: WorkItemTrackerMetadata;
    /** GitHub read-mirror identity for items inside a GitHub-backed Epic tree. */
    githubMirror?: WorkItemGitHubMirrorMetadata;
    /** Azure Boards read-mirror identity for items inside an Azure Boards-backed Epic tree. */
    azureBoardsMirror?: WorkItemAzureBoardsMirrorMetadata;
    /** ISO timestamp when the work item was created. */
    createdAt: string;
    /** ISO timestamp of last modification. */
    updatedAt: string;
    /** ISO timestamp when the work item reached a terminal state. */
    completedAt?: string;
    /** ISO timestamp when the work item was pinned (undefined = not pinned). */
    pinnedAt?: string;
    /** ISO timestamp when the work item was archived (undefined = not archived). */
    archivedAt?: string;

    // Source tracking
    /** How this work item was created. */
    source: WorkItemSource;
    /** ID of the source entity (e.g., processId for chat, scheduleId for schedule). */
    sourceId?: string;

    // Plan
    /** Current plan version (if any). */
    plan?: WorkItemPlan;
    /** Explicit current immutable content version pointer for plan-backed Work Item/Goal content. */
    currentContentVersion?: number;

    // Goal-specific
    /**
     * Success criteria defining what "done" looks like for a `goal` item.
     * Markdown. Ignored for non-goal types.
     */
    successCriteria?: string;
    /**
     * Process ID of the linked spec-drafting (Ralph grilling) chat session for a
     * `goal` item, set while the goal is in the `drafting` phase.
     */
    grillSessionId?: string;

    // Execution tracking
    /** Queue task ID of the currently executing task. */
    taskId?: string;
    /** AI process ID of the currently executing task. */
    processId?: string;
    /** History of all execution attempts. */
    executionHistory?: WorkItemExecution[];
    /** Change tracking entries (plan version + commits per execution cycle). */
    changes?: WorkItemChange[];

    // Metadata
    /** Freeform tags for categorization. */
    tags?: string[];
    /** Priority level. */
    priority?: WorkItemPriority;
    /** Whether to auto-execute when status reaches 'readyToExecute'. */
    autoExecute?: boolean;
    /** Whether to auto-resolve diff comments via AI and re-execute when all are resolved. */
    autoResolveAndReExecute?: boolean;
    /** Number of auto-resolve-then-re-execute cycles completed in the current change. Used as a loop guard. */
    autoReExecuteCycles?: number;

    // Review
    /** Review comments for the AIDone state. */
    reviewComments?: ReviewComment[];
}

// ============================================================================
// Review Comments (for AIDone state)
// ============================================================================

/** A review comment left by the user after AI completes execution. */
export interface ReviewComment {
    /** Unique identifier. */
    id: string;
    /** Comment text. */
    text: string;
    /** ISO timestamp when comment was created. */
    createdAt: string;
    /** Whether this comment has been addressed. */
    resolved?: boolean;
}

// ============================================================================
// Index Entry (lightweight, for listing)
// ============================================================================

/** Lightweight work item summary for index listing (avoids loading full data). */
export interface WorkItemIndexEntry {
    id: string;
    /** Sequential human-readable number (e.g. 1 → displayed as WI-1). */
    workItemNumber?: number;
    repoId: string;
    title: string;
    /** Description excerpt for search (may be truncated). */
    description?: string;
    status: WorkItemStatus;
    type?: WorkItemType;
    /** Parent work item ID (hierarchy). Only set when hierarchy is enabled. */
    parentId?: string;
    /** Epic-rooted tracker identity. Set on Epic roots; descendants inherit it. */
    tracker?: WorkItemTrackerMetadata;
    /** GitHub read-mirror identity for items inside a GitHub-backed Epic tree. */
    githubMirror?: WorkItemGitHubMirrorMetadata;
    /** Azure Boards read-mirror identity for items inside an Azure Boards-backed Epic tree. */
    azureBoardsMirror?: WorkItemAzureBoardsMirrorMetadata;
    source: WorkItemSource;
    priority?: WorkItemPriority;
    planVersion?: number;
    /** Explicit current immutable content version pointer for list/detail parity. */
    currentContentVersion?: number;
    createdAt: string;
    updatedAt: string;
    completedAt?: string;
    /** ISO timestamp when pinned (undefined = not pinned). */
    pinnedAt?: string;
    /** ISO timestamp when archived (undefined = not archived). */
    archivedAt?: string;
    /** ISO timestamp of the most recent execution activity (derived from executionHistory). */
    lastRunAt?: string;
    tags?: string[];
}

// ============================================================================
// Store Interface
// ============================================================================

/** Filter criteria for listing work items. */
export interface WorkItemFilter {
    /** Filter by status(es). */
    status?: WorkItemStatus | WorkItemStatus[];
    /** Filter by source. */
    source?: WorkItemSource;
    /** Filter by repo/workspace ID. */
    repoId?: string;
    /** Filter by priority. */
    priority?: WorkItemPriority;
    /** Filter by tag (any match). */
    tags?: string[];
    /** Filter by type. */
    type?: WorkItemType;
    /** Filter by inherited Epic-rooted tracker kind. */
    tracker?: WorkItemTrackerKind;
    /** Full-text search query (case-insensitive substring match against title, description, tags). */
    search?: string;
    /** Pagination offset (0-based). */
    offset?: number;
    /** Maximum number of items to return. */
    limit?: number;
}

/** Paginated result from listWorkItems. */
export interface WorkItemListResult {
    items: WorkItemIndexEntry[];
    /** Total number of matching items (before pagination). */
    total: number;
}

/** Per-status grouped result from listWorkItemsGrouped. */
export interface WorkItemGroupedResult {
    /** Items and totals keyed by status. Only statuses with at least one item are included. */
    groups: Record<string, WorkItemListResult>;
}

/** Abstract store interface for work item persistence. */
export interface WorkItemStore {
    // CRUD
    addWorkItem(item: WorkItem): Promise<void>;
    getWorkItem(id: string, repoId?: string): Promise<WorkItem | undefined>;
    updateWorkItem(id: string, updates: Partial<Omit<WorkItem, 'id' | 'repoId' | 'createdAt'>>): Promise<WorkItem | undefined>;
    removeWorkItem(id: string): Promise<boolean>;
    listWorkItems(filter?: WorkItemFilter): Promise<WorkItemListResult>;
    /** List work items grouped by status with per-group pagination. */
    listWorkItemsGrouped(filter?: WorkItemFilter): Promise<WorkItemGroupedResult>;
    /** List direct children of a work item within a repo. */
    listChildren(parentId: string, repoId: string): Promise<WorkItemIndexEntry[]>;

    // Plan versioning
    getPlanVersions(workItemId: string): Promise<WorkItemPlanVersion[]>;
    getPlanVersion(workItemId: string, version: number): Promise<WorkItemPlanVersion | undefined>;
    savePlanVersion(workItemId: string, plan: WorkItemPlanVersion): Promise<void>;

    // Execution history
    addExecution(workItemId: string, execution: WorkItemExecution): Promise<void>;
    updateExecution(workItemId: string, taskId: string, updates: Partial<WorkItemExecution>): Promise<void>;

    // Change tracking
    addChange(workItemId: string, change: WorkItemChange): Promise<void>;
    updateChange(workItemId: string, changeId: string, updates: Partial<WorkItemChange>): Promise<void>;
    getChanges(workItemId: string): Promise<WorkItemChange[]>;

    // Pin/archive
    pinWorkItem(id: string, pinnedAt: string): Promise<WorkItem | undefined>;
    unpinWorkItem(id: string): Promise<WorkItem | undefined>;
    archiveWorkItem(id: string, archivedAt: string): Promise<WorkItem | undefined>;
    unarchiveWorkItem(id: string): Promise<WorkItem | undefined>;
}

// ============================================================================
// Helpers
// ============================================================================

/** Check if a work item status is terminal (done or failed). */
export function isTerminalStatus(status: WorkItemStatus): boolean {
    return isKnownWorkItemStatus(status) && TERMINAL_WORK_ITEM_STATUSES.has(status);
}

/** Valid status transitions. */
export const VALID_TRANSITIONS: Record<KnownWorkItemStatus, readonly KnownWorkItemStatus[]> = {
    created:        ['drafting', 'planning', 'readyToExecute', 'done', 'failed'],
    drafting:       ['planning', 'readyToExecute', 'created', 'failed'],
    planning:       ['readyToExecute', 'drafting', 'created', 'done', 'failed'],
    readyToExecute: ['executing', 'planning', 'done', 'failed'],
    executing:      ['aiDone', 'aiFailed', 'failed', 'readyToExecute'],
    aiDone:         ['readyToExecute', 'done', 'failed'],
    aiFailed:       ['readyToExecute', 'created', 'failed'],  // Retry or give up
    done:           ['created'],      // Allow re-opening
    failed:         ['created'],      // Allow re-opening
};

/** Check whether a status is one of CoC's built-in lifecycle states. */
export function isKnownWorkItemStatus(status: unknown): status is KnownWorkItemStatus {
    return typeof status === 'string' && WORK_ITEM_STATUSES.includes(status as KnownWorkItemStatus);
}

/** Check if a status transition is valid. */
export function isValidTransition(from: WorkItemStatus, to: WorkItemStatus): boolean {
    if (!isKnownWorkItemStatus(from) || !isKnownWorkItemStatus(to)) return false;
    return VALID_TRANSITIONS[from]?.includes(to) ?? false;
}

/**
 * Derive the most recent execution timestamp from a work item's execution history.
 * Prefers `completedAt`, then `startedAt` from the latest entry.
 * Returns `undefined` if there is no execution history.
 */
export function getLastRunTime(executionHistory: WorkItemExecution[] | undefined): string | undefined {
    if (!executionHistory || executionHistory.length === 0) return undefined;
    let latest: string | undefined;
    for (const exec of executionHistory) {
        const ts = exec.completedAt ?? exec.startedAt;
        if (!latest || ts > latest) latest = ts;
    }
    return latest;
}

/** Return the item-local tracker kind, defaulting absent metadata to local-only. */
export function getOwnWorkItemTrackerKind(item: { tracker?: WorkItemTrackerMetadata }): WorkItemTrackerKind {
    return item.tracker?.kind ?? 'local-only';
}

/** Extract an index entry from a full work item. */
export function toIndexEntry(item: WorkItem): WorkItemIndexEntry {
    return {
        id: item.id,
        workItemNumber: item.workItemNumber,
        repoId: item.repoId,
        title: item.title,
        description: item.description || undefined,
        status: item.status,
        type: item.type,
        parentId: item.parentId,
        tracker: item.tracker,
        githubMirror: item.githubMirror,
        azureBoardsMirror: item.azureBoardsMirror,
        source: item.source,
        priority: item.priority,
        planVersion: item.plan?.version,
        currentContentVersion: item.currentContentVersion ?? item.plan?.currentVersion ?? item.plan?.version,
        createdAt: item.createdAt,
        updatedAt: item.updatedAt,
        completedAt: item.completedAt,
        pinnedAt: item.pinnedAt,
        archivedAt: item.archivedAt,
        lastRunAt: getLastRunTime(item.executionHistory),
        tags: item.tags,
    };
}

// ============================================================================
// Hierarchy Helpers
// ============================================================================

/**
 * Returns the effective type for an item, defaulting to 'work-item' for
 * existing data that pre-dates the type field.
 */
export function getEffectiveType(type?: WorkItemType): WorkItemType {
    return type ?? 'work-item';
}

/** Returns true if the type is a hierarchy container (epic, feature, pbi). */
export function isContainerType(type: WorkItemType): boolean {
    return HIERARCHY_CONTAINER_TYPES.has(type);
}

/** Returns true if the type is an executable leaf (work-item, bug). */
export function isLeafType(type: WorkItemType): boolean {
    return LEAF_WORK_ITEM_TYPES.has(type);
}

/**
 * Returns true if `parentType` is a valid parent for `childType`.
 * Note: being unparented (no parentId) is always valid; this function
 * only validates when a parentId is present.
 */
export function isValidParentChildTypes(childType: WorkItemType, parentType: WorkItemType): boolean {
    const allowed = ALLOWED_PARENT_TYPES[childType] as readonly WorkItemType[];
    return allowed.includes(parentType);
}
