/**
 * Work Item Types
 *
 * A CoC work item is a tracked unit of work with a description, status lifecycle,
 * and an AI-generated plan. Work items can be created manually, spawned from chat
 * sessions, or generated by schedulers.
 *
 * Lifecycle: created → planning → ready → executing → done | failed
 *
 * Each work item may have a plan with version history, and links to queue tasks
 * for execution tracking.
 */

// ============================================================================
// Status & Source Enums
// ============================================================================

/** Work item lifecycle status. */
export type WorkItemStatus = 'created' | 'planning' | 'ready' | 'executing' | 'done' | 'failed';

/** All valid work item statuses (useful for validation). */
export const WORK_ITEM_STATUSES: readonly WorkItemStatus[] = Object.freeze([
    'created', 'planning', 'ready', 'executing', 'done', 'failed',
]);

/** Terminal statuses that cannot transition further. */
export const TERMINAL_WORK_ITEM_STATUSES: ReadonlySet<WorkItemStatus> = new Set([
    'done', 'failed',
]);

/** How the work item was created. */
export type WorkItemSource = 'manual' | 'chat' | 'schedule';

/** Priority levels for work items. */
export type WorkItemPriority = 'high' | 'normal' | 'low';

// ============================================================================
// Plan Types
// ============================================================================

/** Current plan attached to a work item. */
export interface WorkItemPlan {
    /** Plan version number (1-based, monotonically increasing). */
    version: number;
    /** Markdown plan content. */
    content: string;
    /** ISO timestamp of last update. */
    updatedAt: string;
    /** Who last resolved/updated the plan. */
    resolvedBy?: 'user' | 'ai';
}

/** A historical version of a plan. */
export interface WorkItemPlanVersion {
    /** Version number. */
    version: number;
    /** Markdown plan content. */
    content: string;
    /** ISO timestamp when this version was created. */
    createdAt: string;
    /** Who created this version. */
    resolvedBy?: 'user' | 'ai';
    /** Summary of changes from previous version. */
    summary?: string;
}

// ============================================================================
// Execution Tracking
// ============================================================================

/** Record of a single execution attempt for a work item. */
export interface WorkItemExecution {
    /** Queue task ID. */
    taskId: string;
    /** AI process ID (assigned when task starts executing). */
    processId?: string;
    /** ISO timestamp when execution started. */
    startedAt: string;
    /** ISO timestamp when execution completed. */
    completedAt?: string;
    /** Outcome of this execution. */
    status: 'running' | 'completed' | 'failed' | 'cancelled';
    /** Error message if execution failed. */
    error?: string;
}

// ============================================================================
// Work Item
// ============================================================================

/** A tracked unit of work with a plan and execution history. */
export interface WorkItem {
    /** Unique identifier (UUID). */
    id: string;
    /** Workspace/repo this work item belongs to. */
    repoId: string;
    /** Short title. */
    title: string;
    /** Markdown description of what needs to be done. */
    description: string;
    /** Current lifecycle status. */
    status: WorkItemStatus;
    /** ISO timestamp when the work item was created. */
    createdAt: string;
    /** ISO timestamp of last modification. */
    updatedAt: string;
    /** ISO timestamp when the work item reached a terminal state. */
    completedAt?: string;

    // Source tracking
    /** How this work item was created. */
    source: WorkItemSource;
    /** ID of the source entity (e.g., processId for chat, scheduleId for schedule). */
    sourceId?: string;

    // Plan
    /** Current plan version (if any). */
    plan?: WorkItemPlan;

    // Execution tracking
    /** Queue task ID of the currently executing task. */
    taskId?: string;
    /** AI process ID of the currently executing task. */
    processId?: string;
    /** History of all execution attempts. */
    executionHistory?: WorkItemExecution[];

    // Metadata
    /** Freeform tags for categorization. */
    tags?: string[];
    /** Priority level. */
    priority?: WorkItemPriority;
    /** Whether to auto-execute when status reaches 'ready'. */
    autoExecute?: boolean;
}

// ============================================================================
// Index Entry (lightweight, for listing)
// ============================================================================

/** Lightweight work item summary for index listing (avoids loading full data). */
export interface WorkItemIndexEntry {
    id: string;
    repoId: string;
    title: string;
    status: WorkItemStatus;
    source: WorkItemSource;
    priority?: WorkItemPriority;
    planVersion?: number;
    createdAt: string;
    updatedAt: string;
    completedAt?: string;
    tags?: string[];
}

// ============================================================================
// Store Interface
// ============================================================================

/** Filter criteria for listing work items. */
export interface WorkItemFilter {
    /** Filter by status(es). */
    status?: WorkItemStatus | WorkItemStatus[];
    /** Filter by source. */
    source?: WorkItemSource;
    /** Filter by repo/workspace ID. */
    repoId?: string;
    /** Filter by priority. */
    priority?: WorkItemPriority;
    /** Filter by tag (any match). */
    tags?: string[];
}

/** Abstract store interface for work item persistence. */
export interface WorkItemStore {
    // CRUD
    addWorkItem(item: WorkItem): Promise<void>;
    getWorkItem(id: string): Promise<WorkItem | undefined>;
    updateWorkItem(id: string, updates: Partial<Omit<WorkItem, 'id' | 'repoId' | 'createdAt'>>): Promise<WorkItem | undefined>;
    removeWorkItem(id: string): Promise<boolean>;
    listWorkItems(filter?: WorkItemFilter): Promise<WorkItemIndexEntry[]>;

    // Plan versioning
    getPlanVersions(workItemId: string): Promise<WorkItemPlanVersion[]>;
    getPlanVersion(workItemId: string, version: number): Promise<WorkItemPlanVersion | undefined>;
    savePlanVersion(workItemId: string, plan: WorkItemPlanVersion): Promise<void>;

    // Execution history
    addExecution(workItemId: string, execution: WorkItemExecution): Promise<void>;
    updateExecution(workItemId: string, taskId: string, updates: Partial<WorkItemExecution>): Promise<void>;
}

// ============================================================================
// Helpers
// ============================================================================

/** Check if a work item status is terminal (done or failed). */
export function isTerminalStatus(status: WorkItemStatus): boolean {
    return TERMINAL_WORK_ITEM_STATUSES.has(status);
}

/** Valid status transitions. */
export const VALID_TRANSITIONS: Record<WorkItemStatus, readonly WorkItemStatus[]> = {
    created: ['planning', 'ready', 'failed'],
    planning: ['ready', 'created', 'failed'],
    ready: ['executing', 'planning', 'failed'],
    executing: ['done', 'failed', 'ready'],
    done: ['created'],      // Allow re-opening
    failed: ['created'],    // Allow re-opening
};

/** Check if a status transition is valid. */
export function isValidTransition(from: WorkItemStatus, to: WorkItemStatus): boolean {
    return VALID_TRANSITIONS[from]?.includes(to) ?? false;
}

/** Extract an index entry from a full work item. */
export function toIndexEntry(item: WorkItem): WorkItemIndexEntry {
    return {
        id: item.id,
        repoId: item.repoId,
        title: item.title,
        status: item.status,
        source: item.source,
        priority: item.priority,
        planVersion: item.plan?.version,
        createdAt: item.createdAt,
        updatedAt: item.updatedAt,
        completedAt: item.completedAt,
        tags: item.tags,
    };
}
