/**
 * ExtensionCanvasView — renders a custom extension canvas in a sandboxed iframe.
 *
 * The extension's `ui.html` runs inside `<iframe sandbox="allow-scripts">`
 * (no same-origin access — the page cannot reach the dashboard's cookies or
 * API directly). A bootstrap script injected ahead of the extension HTML
 * exposes `window.CanvasHost` to the extension:
 *
 *   CanvasHost.version            — protocol version marker (2)
 *   CanvasHost.onState(cb)        — re-render callback: cb(state, { revision, title })
 *   CanvasHost.invoke(name, p)    — invoke a declared capability (server-side vm)
 *   CanvasHost.setState(state)    — escape hatch: replace the JSON state directly
 *   CanvasHost.listFiles()        — list the read-only files this canvas was given
 *   CanvasHost.readFile(p, opts)  — read one of them ({ path, size, encoding, content })
 *
 * The file methods are READ-ONLY and scoped to the canvas's own
 * `canvases/<id>/files/` directory — the equivalent of Claude artifacts'
 * `window.fs.readFile`: the data given to this artifact, not the machine. There
 * is no write counterpart; canvas state is the write channel, and unlike a file
 * write it is revision-checked, snapshotted and size-capped.
 *
 * This component renders; it does not speak protocol. The host side lives in
 * `useExtensionCanvasHostController` — it posts `canvas-state` on load and on
 * every live update, and services `invoke-capability` / `set-state` /
 * `list-files` / `read-file` through the canvases REST client, so human UI
 * actions go through the same gate as AI capability calls. The in-frame side is
 * generated by `canvas-host-bootstrap` from the method table in
 * `canvas-host-contract`, which the offline export host is generated from too.
 *
 * Protocol v2 — request/response. `invoke` and `setState` return promises: each
 * extension→host message carries a monotonic `id`, and the host answers with
 * `{ __canvasHost: true, type: 'response', id, ok, result | error }`, which the
 * bootstrap uses to settle the matching entry in its pending map. A request that
 * gets no reply inside REQUEST_TIMEOUT_MS rejects rather than leaking a pending
 * promise. Every rejection carries one shape — an Error with a `code` field, one
 * of 'offline' | 'timeout' | 'revision-conflict' | 'capability-error' — so
 * extension authors branch on `code` instead of string-matching messages.
 *
 * Backwards compatible in both directions: an extension that ignores the
 * returned promise behaves exactly as before, and a message that arrives with no
 * `id` (a pre-v2 sender) is still serviced in full — the host simply posts no
 * reply for it rather than dropping the request.
 *
 * Two authoring paths share this host:
 *   - `ui.html` — the extension's own self-contained HTML+JS, injected after the
 *     bootstrap and otherwise untouched. Loads nothing.
 *   - `ui.js` — a compiled JSX component assigning
 *     `window.CanvasExtension = { mount(rootEl, host) }`. The frame gets a root
 *     element plus a runtime script (see `extension-runtime.ts`) that loads the
 *     manifest's declared libraries from the PAGE origin as classic scripts, in
 *     order, and then calls `mount()`. When that fails, the frame paints a
 *     banner and posts `extension-error` here rather than rendering nothing.
 */

import { useEffect, useState } from 'react';
import type { Canvas, CanvasExtension } from '@plusplusoneplusplus/coc-client';
import { useCocClient } from '../../repos/cloneRouting';
import { buildLiveCanvasHostBootstrap } from './canvas-host-bootstrap';
import { useExtensionCanvasHostController } from './hooks/useExtensionCanvasHostController';
import { buildExtensionRootHtml, buildExtensionRuntimeScript } from './extension-runtime';
import { isCanvasLibraryId } from '../../../../../canvas/canvas-libraries';

export interface ExtensionCanvasViewProps {
    workspaceId: string;
    canvas: Canvas;
    /** Called whenever a capability/setState produced a new canvas record. */
    onCanvasSaved: (canvas: Canvas) => void;
}

/**
 * The in-frame `CanvasHost` bootstrap, generated from the shared method table so
 * it cannot drift from the offline host an export bakes in.
 */
const BOOTSTRAP_SCRIPT = buildLiveCanvasHostBootstrap();

/** The extension documents the frame renders from. A subset of `CanvasExtension`. */
export interface ExtensionSrcDocSource {
    /** Legacy/vanilla authoring: self-contained HTML+JS. */
    uiHtml?: string;
    /** JSX authoring: compiled UI assigning `window.CanvasExtension`. Wins over `uiHtml`. */
    uiJs?: string;
    /** Vendored libraries to load first, dependency-resolved and in order. */
    libraries?: readonly string[];
}

/**
 * Build the iframe `srcdoc`.
 *
 * Two shapes, chosen by which document the extension has:
 *   - `uiJs` — the JSX path: bootstrap, a root element, then the runtime script
 *     that loads the declared libraries from `assetBase` and calls `mount()`.
 *   - `uiHtml` — the legacy path, byte for byte what it always was: bootstrap
 *     followed by the extension's own HTML. Nothing is loaded, nothing injected.
 *
 * `assetBase` is the PAGE origin, deliberately — vendored bundles are the one
 * thing not routed through the workspace-owning server, because they are static
 * assets of the dashboard itself and identical everywhere.
 */
export function buildExtensionSrcDoc(source: ExtensionSrcDocSource, assetBase?: string): string {
    if (source.uiJs) {
        const libraries = (source.libraries ?? []).filter(isCanvasLibraryId);
        const runtime = buildExtensionRuntimeScript({
            uiJs: source.uiJs,
            libraries,
            assetBase: assetBase ?? '',
        });
        return [BOOTSTRAP_SCRIPT, buildExtensionRootHtml(), runtime].join('\n');
    }
    return BOOTSTRAP_SCRIPT + '\n' + (source.uiHtml ?? '');
}

export function ExtensionCanvasView({ workspaceId, canvas, onCanvasSaved }: ExtensionCanvasViewProps) {
    const [extension, setExtension] = useState<CanvasExtension | null>(null);
    const [loadError, setLoadError] = useState<string | null>(null);

    // Route every canvas REST call to the workspace's OWNING server: the remote
    // clone's origin for a remote workspace, else the default page origin. The
    // bare page-origin client (getSpaCocClient) 404s for remote workspaces —
    // their canvas (incl. the extension docs) lives only on the remote server —
    // even though the parent CanvasPanel already loads the content via this same
    // clone-aware client, so the frame renders while the extension GET fails.
    const client = useCocClient(workspaceId);

    // (Re)load extension documents when the canvas or its revision changes —
    // the AI may have replaced the UI/capabilities via
    // create_or_update_extension_canvas, which bumps the revision.
    useEffect(() => {
        let cancelled = false;
        client.canvases.getExtension(workspaceId, canvas.id)
            .then(loaded => {
                if (cancelled) return;
                setExtension(prev =>
                    prev && prev.uiHtml === loaded.uiHtml && prev.uiJs === loaded.uiJs
                        && prev.capabilitiesJs === loaded.capabilitiesJs
                        && JSON.stringify(prev.manifest) === JSON.stringify(loaded.manifest)
                        ? prev
                        : loaded,
                );
                setLoadError(null);
            })
            .catch(() => {
                if (!cancelled) setLoadError('Failed to load canvas extension');
            });
        return () => { cancelled = true; };
    }, [client, workspaceId, canvas.id, canvas.revision]);

    // The whole host side of the CanvasHost protocol — request correlation, the
    // canvases REST calls, error-code mapping, and the two bits of UI state
    // those outcomes drive. This component renders; it does not speak protocol.
    const { iframeRef, pendingInvokes, actionError } = useExtensionCanvasHostController({
        client,
        workspaceId,
        canvas,
        onCanvasSaved,
    });

    if (loadError) {
        return <div className="text-xs text-red-500 py-6 text-center" data-testid="extension-canvas-error">{loadError}</div>;
    }
    if (!extension) {
        return <div className="text-xs text-[#848484] py-6 text-center">Loading extension…</div>;
    }

    return (
        <div className="flex flex-col h-full min-h-0">
            {pendingInvokes > 0 && (
                <div
                    className="px-3 py-1.5 text-[11px] text-[#848484] border-b border-[#e5e5e5] dark:border-[#333]"
                    data-testid="extension-canvas-pending"
                >
                    Running capability…
                </div>
            )}
            {actionError && (
                <div className="px-3 py-1.5 text-[11px] text-red-600 bg-red-50 dark:bg-red-950 border-b border-red-200 dark:border-red-800" data-testid="extension-canvas-action-error">
                    {actionError}
                </div>
            )}
            <iframe
                ref={iframeRef}
                title={canvas.title}
                sandbox="allow-scripts"
                className="flex-1 w-full border-0 bg-white dark:bg-[#1e1e1e]"
                srcDoc={buildExtensionSrcDoc(
                    { uiHtml: extension.uiHtml, uiJs: extension.uiJs, libraries: extension.manifest?.libraries },
                    // Page origin, not the workspace-owning server: the vendored
                    // bundles are static dashboard assets, identical on every
                    // clone. Absolute so the about:srcdoc frame never has to
                    // resolve a relative URL against an inherited base.
                    typeof window !== 'undefined' ? window.location.origin : '',
                )}
                data-testid="extension-canvas-iframe"
            />
        </div>
    );
}
