/**
 * Manages a standalone git repository inside the notes directory
 * (`~/.coc/repos/<wsId>/notes/`). Completely separate from the source code repo —
 * tracks markdown files only.
 */

import * as fs from 'fs';
import * as path from 'path';
import { execGitAsync } from '@plusplusoneplusplus/forge/git';
import { cloneRepository } from '../../routes/api-git-clone-routes';
import type { NotesGitStatus, NotesGitLogEntry, NotesGitDiff, NotesGitDiffFile, NoteFileVersion, NotesGitSyncResult } from './notes-git-types';

/** Empty tree hash used for diffing the initial (parentless) commit. */
const EMPTY_TREE_HASH = '4b825dc642cb6eb9a060e54bf8d69288fbee4904';

/** Longer timeout (ms) for network git operations (fetch/push) than the default. */
const NETWORK_GIT_TIMEOUT_MS = 120_000;

const GITIGNORE_CONTENT = `# Auto-generated by CoC notes git tracking
.DS_Store
Thumbs.db
`;

const DISABLED_HOOKS_PATH = '.git/hooks-disabled';

export class NotesGitService {
    constructor(private readonly notesDir: string) {}

    /** Check if `.git` directory exists inside notesDir. */
    async isInitialized(): Promise<boolean> {
        try {
            const stat = await fs.promises.stat(path.join(this.notesDir, '.git'));
            return stat.isDirectory();
        } catch {
            return false;
        }
    }

    /**
     * Initialize a git repo in notesDir.
     * - `git init`
     * - Disable inherited git hooks for this internal repo
     * - Write `.gitignore` (ignore OS junk)
     * - `git add -A && git commit --allow-empty -m "Initial notes commit"`
     * Idempotent — returns early if already initialized.
     */
    async init(): Promise<void> {
        if (await this.isInitialized()) {
            await this.disableInheritedGitHooks();
            return;
        }

        await fs.promises.mkdir(this.notesDir, { recursive: true });
        await execGitAsync(['init'], this.notesDir);
        await this.disableInheritedGitHooks();

        const gitignorePath = path.join(this.notesDir, '.gitignore');
        await fs.promises.writeFile(gitignorePath, GITIGNORE_CONTENT, 'utf-8');

        // Stage everything and create initial commit
        await execGitAsync(['add', '-A'], this.notesDir);
        await execGitAsync(['commit', '--allow-empty', '-m', 'Initial notes commit'], this.notesDir);
    }

    /**
     * Destructively reset the notes directory to the exact state of a remote origin.
     *
     * Wipes the entire notes directory (including any existing history), then
     * re-clones `remoteUrl` at `branch` (default `main` when blank/unset) into it,
     * reusing the code-repo clone plumbing (`cloneRepository`) so system git and
     * configured credentials handle private-repo auth. After success the notes dir
     * is a real clone with an `origin` remote; inherited git hooks are disabled to
     * match `init()`.
     *
     * Loses all prior local notes and history — there is no backup.
     * Throws when `remoteUrl` is blank or when the clone fails (bad branch/URL/auth).
     */
    async resetFromOrigin(remoteUrl: string, branch?: string): Promise<{ branch: string }> {
        const url = remoteUrl?.trim();
        if (!url) {
            throw new Error('Cannot reset notes from origin: no remote URL configured');
        }
        const targetBranch = branch?.trim() || 'main';

        // Wipe the entire notes directory (files + any existing .git history).
        await fs.promises.rm(this.notesDir, { recursive: true, force: true });

        // git clone creates the target directory; ensure its parent exists.
        const parentDir = path.dirname(this.notesDir);
        await fs.promises.mkdir(parentDir, { recursive: true });

        // Clone the requested branch directly into notesDir using system git.
        await cloneRepository(
            ['clone', '--branch', targetBranch, url, this.notesDir],
            parentDir,
        );

        await this.disableInheritedGitHooks();
        return { branch: targetBranch };
    }

    /**
     * Two-way sync of the notes repo with a configured origin remote.
     *
     * Non-destructive counterpart to {@link resetFromOrigin}:
     *  1. Commit any pending local changes so nothing is lost.
     *  2. Ensure an `origin` remote points at `remoteUrl`.
     *  3. Fetch `branch` from origin. When the branch already exists remotely,
     *     rebase local commits on top of it (integrating remote changes). A
     *     failed rebase is aborted and surfaced — conflicts are never
     *     auto-resolved.
     *  4. Push local commits to `origin/branch`.
     *
     * Uses system git (`execGitAsync`) so configured credentials handle
     * private-repo auth, mirroring the clone path used by `resetFromOrigin`.
     *
     * Throws when the repo is not initialized, `remoteUrl` is blank, a rebase
     * hits conflicts, or a network op fails (bad URL/auth/rejected push).
     */
    async sync(remoteUrl: string, branch?: string): Promise<NotesGitSyncResult> {
        if (!(await this.isInitialized())) {
            throw new Error('Notes git repository is not initialized');
        }
        const url = remoteUrl?.trim();
        if (!url) {
            throw new Error('Cannot sync notes: no remote URL configured');
        }
        const targetBranch = branch?.trim() || 'main';

        // 1. Commit any pending local edits first (also repairs hook config).
        const committedResult = await this.commit();

        // 2. Point `origin` at the configured URL.
        await this.ensureOriginRemote(url);

        // 3. Fetch the target branch; it may not exist remotely yet (empty repo).
        let remoteBranchExists = true;
        try {
            await execGitAsync(
                ['fetch', 'origin', targetBranch],
                this.notesDir,
                { timeout: NETWORK_GIT_TIMEOUT_MS },
            );
        } catch {
            remoteBranchExists = false;
        }

        // 4. Integrate remote commits by rebasing local work on top of them.
        let pulled = false;
        if (remoteBranchExists) {
            try {
                await execGitAsync(['rebase', 'FETCH_HEAD'], this.notesDir);
                pulled = true;
            } catch (err: any) {
                // Leave the repo clean, then surface — never auto-resolve conflicts.
                try { await execGitAsync(['rebase', '--abort'], this.notesDir); } catch { /* best effort */ }
                throw new Error(
                    'Failed to sync notes: local and origin history conflict. Resolve the ' +
                    'conflict manually, or use "Reset from origin" to discard local changes. ' +
                    (err?.message ?? ''),
                );
            }
        }

        // 5. Push local commits to origin/<branch>.
        await execGitAsync(
            ['push', 'origin', `HEAD:${targetBranch}`],
            this.notesDir,
            { timeout: NETWORK_GIT_TIMEOUT_MS },
        );

        return {
            branch: targetBranch,
            committed: committedResult.committed,
            pulled,
            pushed: true,
        };
    }

    /** Add an `origin` remote for `url`, or repoint the existing one. */
    private async ensureOriginRemote(url: string): Promise<void> {
        const remotes = await execGitAsync(['remote'], this.notesDir);
        const hasOrigin = remotes.split('\n').map(r => r.trim()).includes('origin');
        if (hasOrigin) {
            await execGitAsync(['remote', 'set-url', 'origin', url], this.notesDir);
        } else {
            await execGitAsync(['remote', 'add', 'origin', url], this.notesDir);
        }
    }

    private async disableInheritedGitHooks(): Promise<void> {
        await fs.promises.mkdir(path.join(this.notesDir, DISABLED_HOOKS_PATH), { recursive: true });
        await execGitAsync(['config', 'core.hooksPath', DISABLED_HOOKS_PATH], this.notesDir);
    }

    /**
     * Remove the `.git` directory from notesDir, disabling git tracking.
     * Idempotent — does nothing if not initialized. Notes files themselves
     * are preserved; only the version-control history is removed.
     */
    async deinit(): Promise<void> {
        const gitDir = path.join(this.notesDir, '.git');
        try {
            await fs.promises.rm(gitDir, { recursive: true, force: true });
        } catch (err: any) {
            // ENOENT is fine — already deinitialized
            if (err?.code !== 'ENOENT') throw err;
        }
    }

    /**
     * Return working-tree status parsed from `git status --porcelain=v1`.
     * If not initialized, return `{ initialized: false, ... }`.
     */
    async getStatus(): Promise<NotesGitStatus> {
        if (!(await this.isInitialized())) {
            return { initialized: false, branch: '', clean: true, staged: [], unstaged: [], untracked: [], totalChanges: 0, hasUpstream: false, ahead: null, behind: null };
        }

        // Get current branch
        let branch = '';
        try {
            branch = await execGitAsync(['rev-parse', '--abbrev-ref', 'HEAD'], this.notesDir);
        } catch {
            // may fail if no commits yet
        }

        // Compute ahead/behind against the locally-known `origin/<branch>` ref.
        // No network — `origin/<branch>` only advances when we fetch or push, so
        // `ahead` (unpushed) is always accurate; `behind` may be stale until the
        // next Sync. When no tracking ref exists (no remote / never pushed),
        // leave nulls and report no upstream.
        let hasUpstream = false;
        let ahead: number | null = null;
        let behind: number | null = null;
        if (branch) {
            try {
                await execGitAsync(['rev-parse', '--verify', `origin/${branch}`], this.notesDir);
                hasUpstream = true;
                // left = behind (origin has), right = ahead (local has)
                const counts = await execGitAsync(
                    ['rev-list', '--left-right', '--count', `origin/${branch}...HEAD`],
                    this.notesDir,
                );
                const [b, a] = counts.trim().split(/\s+/).map(n => parseInt(n, 10));
                behind = Number.isFinite(b) ? b : 0;
                ahead = Number.isFinite(a) ? a : 0;
            } catch {
                // no upstream ref locally — leave nulls
            }
        }

        const output = await execGitAsync(['status', '--porcelain=v1'], this.notesDir);
        const staged: string[] = [];
        const unstaged: string[] = [];
        const untracked: string[] = [];

        if (output.trim()) {
            for (const line of output.split('\n')) {
                if (!line || line.length < 3) continue;
                const x = line[0]; // index status
                const y = line[1]; // worktree status
                const filePath = line.substring(3);

                if (x === '?' && y === '?') {
                    untracked.push(filePath);
                } else {
                    if (x !== ' ' && x !== '?') {
                        staged.push(filePath);
                    }
                    if (y !== ' ') {
                        unstaged.push(filePath);
                    }
                }
            }
        }

        const totalChanges = staged.length + unstaged.length + untracked.length;
        return {
            initialized: true,
            branch,
            clean: totalChanges === 0,
            staged,
            unstaged,
            untracked,
            totalChanges,
            hasUpstream,
            ahead,
            behind,
        };
    }

    /**
     * Return commit log from `git log`.
     * Use `--skip=<offset> -n <limit>` for pagination.
     * If repo is not initialized or has no commits, return [].
     */
    async getLog(limit: number, offset: number): Promise<NotesGitLogEntry[]> {
        if (!(await this.isInitialized())) return [];

        try {
            const output = await execGitAsync(
                ['log', `--format=%H%x00%h%x00%s%x00%aI`, `--skip=${offset}`, `-n`, `${limit}`, '--shortstat'],
                this.notesDir,
            );

            if (!output.trim()) return [];
            return this.parseLogOutput(output);
        } catch {
            // No commits or other error
            return [];
        }
    }

    /**
     * Parse the combined `--format=...` + `--shortstat` log output.
     * Each commit produces 2–3 lines:
     *   1. The formatted line (hash\0shortHash\0message\0date)
     *   2. An empty line (separator)
     *   3. The shortstat line (e.g. " 1 file changed, 2 insertions(+)")
     * Followed by another empty line before the next commit.
     */
    private parseLogOutput(output: string): NotesGitLogEntry[] {
        const entries: NotesGitLogEntry[] = [];
        const lines = output.split('\n');
        let i = 0;

        while (i < lines.length) {
            const line = lines[i];
            if (!line.includes('\0')) {
                i++;
                continue;
            }

            const parts = line.split('\0');
            if (parts.length < 4) {
                i++;
                continue;
            }

            const [hash, shortHash, message, date] = parts;

            // Look ahead for shortstat line
            let filesChanged = 0;
            for (let j = i + 1; j < Math.min(i + 4, lines.length); j++) {
                const statMatch = lines[j].match(/(\d+)\s+file/);
                if (statMatch) {
                    filesChanged = parseInt(statMatch[1], 10);
                    break;
                }
            }

            entries.push({ hash, shortHash, message, date, filesChanged });
            i++;
        }

        return entries;
    }

    /**
     * Return diff output.
     * - No hash: `git diff` (unstaged) + `git diff --cached` (staged), concatenated.
     * - With hash: `git diff <hash>^..<hash>` (show what that commit changed).
     *   For the initial commit use diff against the empty tree hash.
     */
    async getDiff(hash?: string): Promise<NotesGitDiff> {
        if (!(await this.isInitialized())) {
            return { files: [] };
        }

        if (!hash) {
            return this.getWorkingTreeDiff();
        }
        return this.getCommitDiff(hash);
    }

    private async getWorkingTreeDiff(): Promise<NotesGitDiff> {
        let unstagedDiff = '';
        let unstagedNameStatus = '';
        try {
            unstagedDiff = await execGitAsync(['diff'], this.notesDir);
            unstagedNameStatus = await execGitAsync(['diff', '--name-status'], this.notesDir);
        } catch { /* empty */ }

        let stagedDiff = '';
        let stagedNameStatus = '';
        try {
            stagedDiff = await execGitAsync(['diff', '--cached'], this.notesDir);
            stagedNameStatus = await execGitAsync(['diff', '--cached', '--name-status'], this.notesDir);
        } catch { /* empty */ }

        const nameStatusOutput = [stagedNameStatus, unstagedNameStatus].filter(Boolean).join('\n');
        const combinedDiff = [stagedDiff, unstagedDiff].filter(Boolean).join('\n');

        return this.parseDiffOutput(combinedDiff, nameStatusOutput);
    }

    private async getCommitDiff(hash: string): Promise<NotesGitDiff> {
        // Verify the commit exists — let errors propagate
        await execGitAsync(['cat-file', '-t', hash], this.notesDir);

        let hasParent = true;
        try {
            await execGitAsync(['rev-parse', `${hash}^`], this.notesDir);
        } catch {
            hasParent = false;
        }

        const diffRange = hasParent ? `${hash}^..${hash}` : `${EMPTY_TREE_HASH}..${hash}`;
        let diffOutput = '';
        let nameStatusOutput = '';
        try {
            diffOutput = await execGitAsync(['diff', diffRange], this.notesDir);
            nameStatusOutput = await execGitAsync(['diff', '--name-status', diffRange], this.notesDir);
        } catch { /* empty */ }

        return this.parseDiffOutput(diffOutput, nameStatusOutput);
    }

    /** Parse raw diff and name-status outputs into per-file diff entries. */
    private parseDiffOutput(rawDiff: string, nameStatus: string): NotesGitDiff {
        const files: NotesGitDiffFile[] = [];

        // Build a map of status -> path from name-status
        const statusMap = new Map<string, string>();
        if (nameStatus.trim()) {
            for (const line of nameStatus.split('\n')) {
                if (!line.trim()) continue;
                const status = line[0];
                const filePath = line.substring(1).trim();
                if (filePath) statusMap.set(filePath, status);
            }
        }

        // Split raw diff by file boundaries
        if (rawDiff.trim()) {
            const fileDiffs = rawDiff.split(/^(?=diff --git )/m);
            for (const fileDiff of fileDiffs) {
                if (!fileDiff.trim()) continue;
                // Extract file path from diff header: diff --git a/<path> b/<path>
                const headerMatch = fileDiff.match(/^diff --git a\/(.+?) b\/(.+)/);
                if (!headerMatch) continue;
                const filePath = headerMatch[2];
                const status = statusMap.get(filePath) || 'M';
                files.push({ path: filePath, status, diff: fileDiff });
            }
        }

        // Add files from name-status that have no diff (e.g. binary files, empty adds)
        for (const [filePath, status] of statusMap) {
            if (!files.some(f => f.path === filePath)) {
                files.push({ path: filePath, status, diff: '' });
            }
        }

        return { files };
    }

    /**
     * Stage all changes and commit.
     * Returns `{ committed: false }` if nothing to commit.
     */
    async commit(message?: string): Promise<{ committed: boolean; hash?: string; message?: string }> {
        if (!(await this.isInitialized())) {
            throw new Error('Notes git repository is not initialized');
        }

        await this.disableInheritedGitHooks();
        await execGitAsync(['add', '-A'], this.notesDir);

        // Check if anything to commit
        const status = await execGitAsync(['status', '--porcelain=v1'], this.notesDir);
        if (!status.trim()) {
            return { committed: false };
        }

        const commitMsg = message?.trim() || `Notes snapshot ${new Date().toISOString()}`;
        await execGitAsync(['commit', '-m', commitMsg], this.notesDir);

        const hash = await execGitAsync(['rev-parse', 'HEAD'], this.notesDir);
        return { committed: true, hash, message: commitMsg };
    }

    /**
     * Return commit history that touched `relPath` (relative to notesDir).
     * Uses `git log --follow` so renames are tracked.
     * Returns [] when not initialized or no history exists for the file.
     */
    async getFileLog(relPath: string, limit = 50): Promise<NoteFileVersion[]> {
        if (!(await this.isInitialized())) return [];

        const safeLimit = Math.min(Math.max(1, limit), 200);

        try {
            const output = await execGitAsync(
                ['log', '--follow', `--format=%H%x00%h%x00%s%x00%aI`, `-n`, `${safeLimit}`, '--', relPath],
                this.notesDir,
            );

            if (!output.trim()) return [];

            const versions: NoteFileVersion[] = [];
            for (const line of output.split('\n')) {
                if (!line.includes('\0')) continue;
                const parts = line.split('\0');
                if (parts.length < 4) continue;
                const [hash, shortHash, message, date] = parts;
                versions.push({
                    hash: hash.trim(),
                    shortHash: shortHash.trim(),
                    message: message.trim(),
                    date: date.trim(),
                    isNamedCheckpoint: message.trim().startsWith('[v] '),
                });
            }
            return versions;
        } catch {
            return [];
        }
    }

    /**
     * Return the raw content of `relPath` at the given commit `hash`.
     * Throws when the object does not exist.
     */
    async getFileContentAtRevision(hash: string, relPath: string): Promise<string> {
        return execGitAsync(['show', `${hash}:${relPath}`], this.notesDir);
    }
}
