/**
 * Diff Comments REST API Handler
 *
 * HTTP API routes for CRUD operations on git diff view comments.
 * Stores comments in JSON files under the CoC data directory.
 *
 * Storage layout:
 *   {dataDir}/diff-comments/{workspaceId}/{sha256(repoId+oldRef+newRef+filePath)}.json
 *
 * For working-tree diffs (newRef === 'working-tree'), the storage key is
 *   sha256(repoId+filePath+'working-tree') and every comment is ephemeral.
 *
 * No VS Code dependencies — uses only Node.js built-in modules.
 * Cross-platform compatible (Linux/Mac/Windows).
 */

import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { sendJSON, sendError, parseBody } from '@plusplusoneplusplus/coc-server';
import type { Route, ProcessWebSocketServer } from '@plusplusoneplusplus/coc-server';
import type { DiffComment, DiffCommentContext } from '@plusplusoneplusplus/pipeline-core';
import {
    DEFAULT_AI_COMMANDS,
    type AICommand,
    buildPromptFromContext,
    type PromptContext,
} from '@plusplusoneplusplus/pipeline-core';
import type { ProcessStore } from '@plusplusoneplusplus/pipeline-core';
import type { MultiRepoQueueExecutorBridge } from './multi-repo-executor-bridge';

// ============================================================================
// Types
// ============================================================================

/**
 * A reply to a diff comment.
 */
export interface DiffCommentReply {
    /** Unique identifier (UUID). */
    id: string;
    /** Author name. */
    author: string;
    /** Reply text content. */
    text: string;
    /** ISO timestamp when created. */
    createdAt: string;
    /** Whether this reply was generated by AI. */
    isAI?: boolean;
}

/**
 * Storage format for diff comments.
 */
export interface DiffCommentsStorage {
    comments: DiffComment[];
    settings: {
        showResolved: boolean;
    };
}

// ============================================================================
// Constants
// ============================================================================

/** Sub-directory name for diff comments storage. */
const DIFF_COMMENTS_DIR_NAME = 'diff-comments';

/** Default settings for new diff comment storage files. */
const DEFAULT_DIFF_SETTINGS: DiffCommentsStorage['settings'] = {
    showResolved: true,
};

// ============================================================================
// DiffCommentsManager
// ============================================================================

/**
 * Manages diff comments storage and operations.
 * Mirrors TaskCommentsManager but keyed by sha256(context) instead of filePath.
 */
export class DiffCommentsManager {
    private readonly commentsRoot: string;

    /**
     * @param dataDir - Root data directory (e.g. ~/.coc)
     */
    constructor(dataDir: string) {
        this.commentsRoot = path.join(dataDir, DIFF_COMMENTS_DIR_NAME);
    }

    /**
     * Derive a storage key from a diff context.
     *
     * Fields are concatenated without a separator — clients must use the same
     * concatenation order to produce matching keys.
     *
     * Normal diff:    sha256(repositoryId + oldRef + newRef + filePath)
     * Working-tree:   sha256(repositoryId + filePath + 'working-tree')
     *                 (oldRef is omitted; 'working-tree' sentinel is appended)
     */
    hashContext(ctx: DiffCommentContext): string {
        if (ctx.newRef === 'working-tree') {
            return crypto
                .createHash('sha256')
                .update(ctx.repositoryId + ctx.filePath + 'working-tree')
                .digest('hex');
        }
        return crypto
            .createHash('sha256')
            .update(ctx.repositoryId + ctx.oldRef + ctx.newRef + ctx.filePath)
            .digest('hex');
    }

    /** Get comments directory for a workspace. */
    private getWorkspaceDir(wsId: string): string {
        return path.join(this.commentsRoot, wsId);
    }

    /** Get storage file path for a storage key. */
    private getStorageFile(wsId: string, storageKey: string): string {
        return path.join(this.getWorkspaceDir(wsId), `${storageKey}.json`);
    }

    /** Ensure workspace directory exists. */
    private ensureWorkspaceDir(wsId: string): void {
        const dir = this.getWorkspaceDir(wsId);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
    }

    /** Read all comments for a storage key. */
    async getComments(wsId: string, storageKey: string): Promise<DiffComment[]> {
        const file = this.getStorageFile(wsId, storageKey);
        if (!fs.existsSync(file)) {
            return [];
        }
        try {
            const content = await fs.promises.readFile(file, 'utf8');
            const storage: DiffCommentsStorage = JSON.parse(content);
            return storage.comments || [];
        } catch {
            return [];
        }
    }

    /** Write comments to storage atomically (write to temp file then rename). */
    async writeComments(wsId: string, storageKey: string, comments: DiffComment[]): Promise<void> {
        this.ensureWorkspaceDir(wsId);
        const file = this.getStorageFile(wsId, storageKey);
        const storage: DiffCommentsStorage = {
            comments,
            settings: DEFAULT_DIFF_SETTINGS,
        };
        const tempFile = `${file}.tmp`;
        try {
            await fs.promises.writeFile(tempFile, JSON.stringify(storage, null, 2), 'utf8');
            await fs.promises.rename(tempFile, file);
        } catch (error) {
            // Clean up temp file on error
            try { await fs.promises.unlink(tempFile); } catch { /* ignore */ }
            throw error;
        }
    }

    /**
     * Add a new comment.
     * Sets `ephemeral: true` when `ctx.newRef === 'working-tree'`.
     */
    async addComment(
        wsId: string,
        ctx: DiffCommentContext,
        commentData: Omit<DiffComment, 'id' | 'createdAt' | 'updatedAt' | 'ephemeral'>
    ): Promise<DiffComment> {
        const storageKey = this.hashContext(ctx);
        const comments = await this.getComments(wsId, storageKey);
        const now = new Date().toISOString();
        const newComment: DiffComment = {
            ...commentData,
            id: crypto.randomUUID(),
            createdAt: now,
            updatedAt: now,
            ...(ctx.newRef === 'working-tree' ? { ephemeral: true } : {}),
        };
        comments.push(newComment);
        await this.writeComments(wsId, storageKey, comments);
        return newComment;
    }

    /** Update an existing comment. Returns null if not found. */
    async updateComment(
        wsId: string,
        storageKey: string,
        id: string,
        updates: Partial<Omit<DiffComment, 'id' | 'createdAt'>>
    ): Promise<DiffComment | null> {
        const comments = await this.getComments(wsId, storageKey);
        const index = comments.findIndex(c => c.id === id);
        if (index === -1) {
            return null;
        }
        comments[index] = {
            ...comments[index],
            ...updates,
            id: comments[index].id,
            createdAt: comments[index].createdAt,
            updatedAt: new Date().toISOString(),
        };
        await this.writeComments(wsId, storageKey, comments);
        return comments[index];
    }

    /** Delete a comment. Returns false if not found. */
    async deleteComment(wsId: string, storageKey: string, id: string): Promise<boolean> {
        const comments = await this.getComments(wsId, storageKey);
        const filtered = comments.filter(c => c.id !== id);
        if (filtered.length === comments.length) {
            return false;
        }
        await this.writeComments(wsId, storageKey, filtered);
        return true;
    }

    /** Get a single comment by ID. Returns null if not found. */
    async getComment(wsId: string, storageKey: string, id: string): Promise<DiffComment | null> {
        const comments = await this.getComments(wsId, storageKey);
        return comments.find(c => c.id === id) || null;
    }

    /** Add a reply to a comment. Returns null if comment not found. */
    async addReply(
        wsId: string,
        storageKey: string,
        id: string,
        replyData: { author: string; text: string; isAI?: boolean }
    ): Promise<DiffCommentReply | null> {
        const comments = await this.getComments(wsId, storageKey);
        const index = comments.findIndex(c => c.id === id);
        if (index === -1) return null;

        const reply: DiffCommentReply = {
            id: crypto.randomUUID(),
            author: replyData.author,
            text: replyData.text,
            createdAt: new Date().toISOString(),
            isAI: replyData.isAI,
        };

        if (!comments[index].replies) {
            comments[index].replies = [];
        }
        (comments[index].replies as DiffCommentReply[]).push(reply);
        comments[index].updatedAt = new Date().toISOString();
        await this.writeComments(wsId, storageKey, comments);
        return reply;
    }

    /**
     * Get comment counts for all storage keys in a workspace.
     * Returns a map of storageKey → comment count.
     */
    async getCommentCounts(wsId: string): Promise<Record<string, number>> {
        const wsDir = this.getWorkspaceDir(wsId);
        if (!fs.existsSync(wsDir)) {
            return {};
        }
        const counts: Record<string, number> = {};
        let entries: string[];
        try {
            entries = await fs.promises.readdir(wsDir);
        } catch {
            return {};
        }
        for (const entry of entries) {
            if (!entry.endsWith('.json')) continue;
            try {
                const content = await fs.promises.readFile(path.join(wsDir, entry), 'utf8');
                const storage: DiffCommentsStorage = JSON.parse(content);
                const comments = storage.comments || [];
                const key = entry.slice(0, -5); // strip ".json"
                counts[key] = comments.length;
            } catch {
                // Skip corrupted files
            }
        }
        return counts;
    }

    /**
     * List all comments in a workspace across all storage files.
     */
    async listAllComments(wsId: string): Promise<DiffComment[]> {
        const wsDir = this.getWorkspaceDir(wsId);
        if (!fs.existsSync(wsDir)) {
            return [];
        }
        let entries: string[];
        try {
            entries = await fs.promises.readdir(wsDir);
        } catch {
            return [];
        }
        const all: DiffComment[] = [];
        for (const entry of entries) {
            if (!entry.endsWith('.json')) continue;
            try {
                const content = await fs.promises.readFile(path.join(wsDir, entry), 'utf8');
                const storage: DiffCommentsStorage = JSON.parse(content);
                all.push(...(storage.comments || []));
            } catch {
                // Skip corrupted files
            }
        }
        return all;
    }
}

// ============================================================================
// Validation Helpers
// ============================================================================

/** Validate workspace ID to prevent path traversal. */
function isValidWorkspaceId(wsId: string): boolean {
    return /^[a-zA-Z0-9_-]+$/.test(wsId) && !wsId.includes('..');
}

/** Validate storage key (SHA-256 hex, 64 chars). */
function isValidStorageKey(key: string): boolean {
    return /^[0-9a-f]{64}$/.test(key);
}

/** Validate that a diff comment context object has all required fields. */
function isValidContext(ctx: any): ctx is DiffCommentContext {
    return (
        ctx &&
        typeof ctx === 'object' &&
        typeof ctx.repositoryId === 'string' &&
        typeof ctx.oldRef === 'string' &&
        typeof ctx.newRef === 'string' &&
        typeof ctx.filePath === 'string'
    );
}

// ============================================================================
// URL Patterns
// ============================================================================

// /api/diff-comment-counts/:wsId
const countsPattern = /^\/api\/diff-comment-counts\/([a-zA-Z0-9_-]+)$/;

// /api/diff-comments/:wsId  (list all / create)
const collectionPattern = /^\/api\/diff-comments\/([a-zA-Z0-9_-]+)$/;

// /api/diff-comments/:wsId/:storageKey
const storageKeyPattern = /^\/api\/diff-comments\/([a-zA-Z0-9_-]+)\/([0-9a-f]{64})$/;

// /api/diff-comments/:wsId/:storageKey/:id
const itemPattern = /^\/api\/diff-comments\/([a-zA-Z0-9_-]+)\/([0-9a-f]{64})\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;

// /api/diff-comments/:wsId/:storageKey/:id/replies
const replyPattern = /^\/api\/diff-comments\/([a-zA-Z0-9_-]+)\/([0-9a-f]{64})\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\/replies$/;

// /api/diff-comments/:wsId/:storageKey/:id/ask-ai
const askAiPattern = /^\/api\/diff-comments\/([a-zA-Z0-9_-]+)\/([0-9a-f]{64})\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\/ask-ai$/;

// ============================================================================
// Route Registration
// ============================================================================

/**
 * Register diff comments API routes on the given route table.
 * Mutates the `routes` array in-place.
 *
 * Endpoints:
 *   GET    /api/diff-comment-counts/:wsId              — comment counts per storage key
 *   GET    /api/diff-comments/:wsId                    — list all comments in workspace
 *   POST   /api/diff-comments/:wsId                    — create comment
 *   GET    /api/diff-comments/:wsId/:key               — list comments for storage key
 *   GET    /api/diff-comments/:wsId/:key/:id           — get single comment
 *   PATCH  /api/diff-comments/:wsId/:key/:id           — update comment
 *   DELETE /api/diff-comments/:wsId/:key/:id           — delete comment
 *   POST   /api/diff-comments/:wsId/:key/:id/replies   — add reply
 *   POST   /api/diff-comments/:wsId/:key/:id/ask-ai    — AI clarification
 *
 * @param routes - Shared route table
 * @param dataDir - Directory for comment storage (e.g. ~/.coc)
 * @param bridge - Multi-repo queue bridge (reserved for future AI integration)
 * @param store - Optional process store (reserved for future workspace resolution)
 * @param getWsServer - Optional WebSocket server accessor (reserved for future events)
 */
export function registerDiffCommentsRoutes(
    routes: Route[],
    dataDir: string,
    bridge: MultiRepoQueueExecutorBridge,
    store?: ProcessStore,
    getWsServer?: () => ProcessWebSocketServer | undefined
): void {
    const manager = new DiffCommentsManager(dataDir);

    // ------------------------------------------------------------------
    // GET /api/diff-comment-counts/:wsId — comment counts per storage key
    // ------------------------------------------------------------------
    routes.push({
        method: 'GET',
        pattern: countsPattern,
        handler: async (_req, res, match) => {
            const [, wsId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            try {
                const counts = await manager.getCommentCounts(wsId);
                sendJSON(res, 200, { counts });
            } catch {
                sendError(res, 500, 'Failed to retrieve comment counts');
            }
        },
    });

    // ------------------------------------------------------------------
    // GET /api/diff-comments/:wsId — list all comments in workspace
    // ------------------------------------------------------------------
    routes.push({
        method: 'GET',
        pattern: collectionPattern,
        handler: async (_req, res, match) => {
            const [, wsId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            try {
                const comments = await manager.listAllComments(wsId);
                sendJSON(res, 200, { comments });
            } catch {
                sendError(res, 500, 'Failed to retrieve comments');
            }
        },
    });

    // ------------------------------------------------------------------
    // POST /api/diff-comments/:wsId — create comment
    // ------------------------------------------------------------------
    routes.push({
        method: 'POST',
        pattern: collectionPattern,
        handler: async (req, res, match) => {
            const [, wsId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }
            if (!isValidContext(body.context)) {
                return sendError(res, 400, 'Missing or invalid required field: context');
            }
            if (body.selection === undefined || body.selection === null) {
                return sendError(res, 400, 'Missing required field: selection');
            }
            if (body.selectedText === undefined || body.selectedText === null) {
                return sendError(res, 400, 'Missing required field: selectedText');
            }
            if (body.comment === undefined || body.comment === null) {
                return sendError(res, 400, 'Missing required field: comment');
            }
            try {
                const comment = await manager.addComment(wsId, body.context, {
                    context: body.context,
                    selection: body.selection,
                    selectedText: body.selectedText,
                    comment: body.comment,
                    status: body.status || 'open',
                    author: body.author,
                    tags: body.tags,
                    replies: body.replies,
                    aiResponse: body.aiResponse,
                });
                sendJSON(res, 201, { comment });
            } catch {
                sendError(res, 500, 'Failed to create comment');
            }
        },
    });

    // ------------------------------------------------------------------
    // GET /api/diff-comments/:wsId/:key — list comments for storage key
    // ------------------------------------------------------------------
    routes.push({
        method: 'GET',
        pattern: storageKeyPattern,
        handler: async (_req, res, match) => {
            const [, wsId, storageKey] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            if (!isValidStorageKey(storageKey)) {
                return sendError(res, 400, 'Invalid storage key');
            }
            try {
                const comments = await manager.getComments(wsId, storageKey);
                sendJSON(res, 200, { comments });
            } catch {
                sendError(res, 500, 'Failed to retrieve comments');
            }
        },
    });

    // ------------------------------------------------------------------
    // GET /api/diff-comments/:wsId/:key/:id — get single comment
    // (Must be registered before item PATCH/DELETE to avoid duplicate pattern issues)
    // ------------------------------------------------------------------
    routes.push({
        method: 'GET',
        pattern: itemPattern,
        handler: async (_req, res, match) => {
            const [, wsId, storageKey, id] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            try {
                const comment = await manager.getComment(wsId, storageKey, id);
                if (!comment) {
                    return sendError(res, 404, 'Comment not found');
                }
                sendJSON(res, 200, { comment });
            } catch {
                sendError(res, 500, 'Failed to retrieve comment');
            }
        },
    });

    // ------------------------------------------------------------------
    // PATCH /api/diff-comments/:wsId/:key/:id — update comment
    // ------------------------------------------------------------------
    routes.push({
        method: 'PATCH',
        pattern: itemPattern,
        handler: async (req, res, match) => {
            const [, wsId, storageKey, id] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }
            try {
                const comment = await manager.updateComment(wsId, storageKey, id, body);
                if (!comment) {
                    return sendError(res, 404, 'Comment not found');
                }
                sendJSON(res, 200, { comment });
            } catch {
                sendError(res, 500, 'Failed to update comment');
            }
        },
    });

    // ------------------------------------------------------------------
    // DELETE /api/diff-comments/:wsId/:key/:id — delete comment
    // ------------------------------------------------------------------
    routes.push({
        method: 'DELETE',
        pattern: itemPattern,
        handler: async (_req, res, match) => {
            const [, wsId, storageKey, id] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            try {
                const deleted = await manager.deleteComment(wsId, storageKey, id);
                if (!deleted) {
                    return sendError(res, 404, 'Comment not found');
                }
                sendJSON(res, 204, null);
            } catch {
                sendError(res, 500, 'Failed to delete comment');
            }
        },
    });

    // ------------------------------------------------------------------
    // POST /api/diff-comments/:wsId/:key/:id/replies — add reply
    // ------------------------------------------------------------------
    routes.push({
        method: 'POST',
        pattern: replyPattern,
        handler: async (req, res, match) => {
            const [, wsId, storageKey, id] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }
            if (!body.text || typeof body.text !== 'string') {
                return sendError(res, 400, 'Missing required field: text');
            }
            try {
                const reply = await manager.addReply(wsId, storageKey, id, {
                    author: body.author || 'Anonymous',
                    text: body.text,
                    isAI: body.isAI,
                });
                if (!reply) {
                    return sendError(res, 404, 'Comment not found');
                }
                sendJSON(res, 201, { reply });
            } catch {
                sendError(res, 500, 'Failed to add reply');
            }
        },
    });

    // ------------------------------------------------------------------
    // POST /api/diff-comments/:wsId/:key/:id/ask-ai — AI clarification
    // ------------------------------------------------------------------
    routes.push({
        method: 'POST',
        pattern: askAiPattern,
        handler: async (req, res, match) => {
            const [, wsId, storageKey, commentId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }
            try {
                const comment = await manager.getComment(wsId, storageKey, commentId);
                if (!comment) {
                    return sendError(res, 404, 'Comment not found');
                }

                const commandId: string | undefined = body.commandId;
                const customQuestion: string | undefined = body.customQuestion;

                let prompt: string;
                if (commandId) {
                    const command = DEFAULT_AI_COMMANDS.find(c => c.id === commandId);
                    if (command) {
                        prompt = buildDiffEnrichedPrompt(command, comment, customQuestion);
                    } else {
                        const question = customQuestion || body.question || 'Please explain this section and suggest improvements.';
                        prompt = buildDiffAIPrompt(comment, question);
                    }
                } else {
                    const question = body.question || 'Please explain this section and suggest improvements.';
                    prompt = buildDiffAIPrompt(comment, question);
                }

                let aiResponse: string;
                try {
                    const { createCLIAIInvoker } = await import('../ai-invoker');
                    const invoker = createCLIAIInvoker({ approvePermissions: false });
                    const result = await invoker(prompt, { timeoutMs: 60000 });
                    if (!result.success) {
                        return sendError(res, 502, result.error || 'AI request failed');
                    }
                    aiResponse = result.response || '';
                } catch {
                    return sendError(res, 503, 'AI service unavailable');
                }

                await manager.updateComment(wsId, storageKey, commentId, { aiResponse });

                const reply = await manager.addReply(wsId, storageKey, commentId, {
                    author: 'AI',
                    text: aiResponse,
                    isAI: true,
                });

                sendJSON(res, 200, { aiResponse, reply });
            } catch {
                sendError(res, 500, 'Failed to process AI request');
            }
        },
    });
}

/**
 * Build an enriched prompt using a named AI command for a diff comment.
 */
function buildDiffEnrichedPrompt(
    command: AICommand,
    comment: DiffComment,
    customQuestion: string | undefined
): string {
    const promptTemplate =
        command.isCustomInput && customQuestion ? customQuestion : command.prompt;

    const context: PromptContext = {
        selectedText: comment.selectedText,
        filePath: comment.context.filePath,
    };

    let prompt = buildPromptFromContext(promptTemplate, context);
    prompt += `\n\nDiff context: ${comment.context.filePath} (${comment.context.oldRef} → ${comment.context.newRef})`;
    if (comment.comment) {
        prompt += `\nUser comment: "${comment.comment}"`;
    }
    return prompt;
}

/**
 * Build a simple AI prompt with diff-specific context.
 */
function buildDiffAIPrompt(comment: DiffComment, question: string): string {
    let prompt = 'Context: The user is reviewing a git diff.\n';
    prompt += `File: ${comment.context.filePath}\n`;
    prompt += `Diff range: ${comment.context.oldRef} → ${comment.context.newRef}\n\n`;
    if (comment.selectedText) {
        prompt += 'They selected the following text from the diff:\n---\n' + comment.selectedText + '\n---\n\n';
    }
    if (comment.comment) {
        prompt += 'Their comment says: "' + comment.comment + '"\n\n';
    }
    prompt += 'Question: ' + question + '\n\nProvide a clear, actionable response.';
    return prompt;
}
