/**
 * Notes Git Auto-Commit — script generation & schedule integration.
 *
 * Generates OS-specific auto-commit shell scripts (.ps1 on Windows, .sh on Unix)
 * that perform `git add -A && git commit` only when the working tree is dirty.
 * Wires into the existing ScheduleManager as `targetType: 'script'` entries.
 *
 * Cross-platform compatible (Linux/Mac/Windows).
 */

import * as fs from 'fs';
import * as path from 'path';
import { getRepoDataPath } from './paths';
import type { ScheduleManager, ScheduleEntry } from './schedule-manager';

/** Well-known schedule name for notes auto-commit (singleton per repo). */
export const NOTES_AUTOCOMMIT_SCHEDULE_NAME = 'Notes Auto-Commit';

/**
 * Generate the auto-commit script content for the given platform.
 */
export function generateAutoCommitScript(notesDir: string, platform: NodeJS.Platform): string {
    if (platform === 'win32') {
        return [
            '# Auto-commit script for CoC Notes Git Tracking',
            '# Generated by CoC \u2014 do not edit manually',
            '$ErrorActionPreference = \'Stop\'',
            `Set-Location -LiteralPath '${notesDir}'`,
            '',
            '$status = git status --porcelain 2>&1',
            'if ($LASTEXITCODE -ne 0) {',
            '    Write-Error "git status failed: $status"',
            '    exit 1',
            '}',
            '',
            'if ($status) {',
            '    git add -A',
            '    if ($LASTEXITCODE -ne 0) { exit 1 }',
            '    $timestamp = Get-Date -Format \'yyyy-MM-dd HH:mm\'',
            '    git commit -m "auto: $timestamp"',
            '    if ($LASTEXITCODE -ne 0) { exit 1 }',
            '    Write-Output "Committed changes at $timestamp"',
            '} else {',
            '    Write-Output "No changes to commit"',
            '}',
            '',
        ].join('\r\n');
    }

    // Unix (Linux, macOS, etc.)
    return [
        '#!/bin/bash',
        '# Auto-commit script for CoC Notes Git Tracking',
        '# Generated by CoC \u2014 do not edit manually',
        'set -euo pipefail',
        '',
        `cd '${notesDir}'`,
        '',
        'if [ -n "$(git status --porcelain 2>&1)" ]; then',
        '    git add -A',
        '    git commit -m "auto: $(date \'+%Y-%m-%d %H:%M\')"',
        '    echo "Committed changes at $(date \'+%Y-%m-%d %H:%M\')"',
        'else',
        '    echo "No changes to commit"',
        'fi',
        '',
    ].join('\n');
}

/**
 * Write the auto-commit script to the per-repo data directory.
 * Returns the absolute path to the written script.
 */
export async function writeAutoCommitScript(
    dataDir: string,
    wsId: string,
    notesDir: string,
    platform: NodeJS.Platform = process.platform,
): Promise<string> {
    const ext = platform === 'win32' ? '.ps1' : '.sh';
    const scriptPath = getRepoDataPath(dataDir, wsId, `notes-autocommit${ext}`);

    // Ensure parent directory exists
    await fs.promises.mkdir(path.dirname(scriptPath), { recursive: true });

    const content = generateAutoCommitScript(notesDir, platform);
    await fs.promises.writeFile(scriptPath, content, 'utf-8');

    // Set executable permission on Unix
    if (platform !== 'win32') {
        await fs.promises.chmod(scriptPath, 0o755);
    }

    return scriptPath;
}

/**
 * Delete both .ps1 and .sh variants of the auto-commit script.
 * Tolerates missing files (ENOENT).
 */
export async function deleteAutoCommitScript(dataDir: string, wsId: string): Promise<void> {
    const ps1Path = getRepoDataPath(dataDir, wsId, 'notes-autocommit.ps1');
    const shPath = getRepoDataPath(dataDir, wsId, 'notes-autocommit.sh');

    for (const p of [ps1Path, shPath]) {
        try {
            await fs.promises.unlink(p);
        } catch (err: any) {
            if (err.code !== 'ENOENT') throw err;
        }
    }
}

/**
 * Build the shell invocation string for the schedule target.
 */
export function buildAutoCommitScheduleTarget(
    scriptPath: string,
    platform: NodeJS.Platform = process.platform,
): string {
    if (platform === 'win32') {
        return `powershell -ExecutionPolicy Bypass -File "${scriptPath}"`;
    }
    return `bash "${scriptPath}"`;
}

/**
 * Find the auto-commit schedule for a repo by its well-known name.
 */
export function findAutoCommitSchedule(
    scheduleManager: ScheduleManager,
    repoId: string,
): ScheduleEntry | undefined {
    return scheduleManager.getSchedules(repoId)
        .find(s => s.name === NOTES_AUTOCOMMIT_SCHEDULE_NAME);
}
