/**
 * Task Comments REST API Handler
 *
 * HTTP API routes for CRUD operations on task file comments.
 * Stores comments in JSON files under the CoC data directory,
 * compatible with the extension's comment storage format.
 *
 * Storage layout:
 *   {dataDir}/tasks-comments/{workspaceId}/{sha256(filePath)}.json
 *
 * No VS Code dependencies — uses only Node.js built-in modules.
 * Cross-platform compatible (Linux/Mac/Windows).
 */

import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { sendJSON, sendError, parseBody } from '@plusplusoneplusplus/coc-server';
import type { Route } from '@plusplusoneplusplus/coc-server';
import {
    DEFAULT_AI_COMMANDS,
    type AICommand,
    buildPromptFromContext,
    type PromptContext,
    type CreateTaskInput,
} from '@plusplusoneplusplus/pipeline-core';
import type { ResolveCommentsPayload } from '@plusplusoneplusplus/coc-server';
import type { MultiRepoQueueExecutorBridge } from './multi-repo-executor-bridge';
import type { ProcessStore } from '@plusplusoneplusplus/pipeline-core';

// ============================================================================
// Types
// ============================================================================

/**
 * Comment on a task file, compatible with extension format.
 */
export interface TaskComment {
    /** Unique identifier (UUID). */
    id: string;
    /** Relative path to task file. */
    filePath: string;
    /** Selection range in the file. */
    selection: {
        startLine: number;
        startColumn: number;
        endLine: number;
        endColumn: number;
    };
    /** The actual selected text. */
    selectedText: string;
    /** User's comment content. */
    comment: string;
    /** Current status. */
    status: 'open' | 'resolved' | 'pending';
    /** ISO timestamp when created. */
    createdAt: string;
    /** ISO timestamp when last updated. */
    updatedAt: string;
    /** Optional author name. */
    author?: string;
    /** Optional tags. */
    tags?: string[];
    /** Optional comment category. */
    category?: string;
    /** Optional anchor for robust location tracking. */
    anchor?: CommentAnchor;
    /** Threaded replies to this comment. */
    replies?: TaskCommentReply[];
    /** AI-generated clarification response. */
    aiResponse?: string;
}

/**
 * A reply to a comment.
 */
export interface TaskCommentReply {
    /** Unique identifier (UUID). */
    id: string;
    /** Author name. */
    author: string;
    /** Reply text content. */
    text: string;
    /** ISO timestamp when created. */
    createdAt: string;
    /** Whether this reply was generated by AI. */
    isAI?: boolean;
}

/**
 * Anchor context for robust comment location tracking.
 */
export interface CommentAnchor {
    selectedText: string;
    contextBefore: string;
    contextAfter: string;
    originalLine: number;
    textHash: string;
}

/**
 * Optional document context supplied by the client to enrich AI prompts.
 */
export interface DocumentContext {
    /** Lines surrounding the selection (excluding the selection itself). */
    surroundingLines?: string;
    /** Nearest markdown heading above the selection. */
    nearestHeading?: string;
    /** All headings in the document. */
    allHeadings?: string[];
    /** Relative path of the source file (overrides comment.filePath if provided). */
    filePath?: string;
}

/**
 * Storage format (matches extension's format).
 */
export interface CommentsStorage {
    comments: TaskComment[];
    settings: {
        showResolved: boolean;
        highlightColor: string;
    };
}

// ============================================================================
// Constants
// ============================================================================

/** Sub-directory name for task comments storage. */
const COMMENTS_DIR_NAME = 'tasks-comments';

/** Default settings for new comment storage files. */
const DEFAULT_SETTINGS: CommentsStorage['settings'] = {
    showResolved: true,
    highlightColor: '#ffeb3b',
};

// ============================================================================
// TaskCommentsManager
// ============================================================================

/**
 * Manages task comments storage and operations.
 * Mirrors extension's CommentsManager but for server-side use.
 */
export class TaskCommentsManager {
    private readonly commentsRoot: string;

    /**
     * @param dataDir - Root data directory (e.g. ~/.coc)
     */
    constructor(dataDir: string) {
        this.commentsRoot = path.join(dataDir, COMMENTS_DIR_NAME);
    }

    /** Get comments directory for a workspace. */
    private getWorkspaceDir(workspaceId: string): string {
        return path.join(this.commentsRoot, workspaceId);
    }

    /**
     * Hash file path to create storage filename.
     * Uses SHA-256 for consistent, collision-resistant hashes.
     */
    hashFilePath(filePath: string): string {
        return crypto.createHash('sha256').update(filePath).digest('hex');
    }

    /** Get storage file path for a task file. */
    private getStorageFile(workspaceId: string, taskPath: string): string {
        const hash = this.hashFilePath(taskPath);
        return path.join(this.getWorkspaceDir(workspaceId), `${hash}.json`);
    }

    /** Ensure workspace directory exists. */
    private ensureWorkspaceDir(workspaceId: string): void {
        const dir = this.getWorkspaceDir(workspaceId);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
    }

    /** Read all comments for a task file. */
    async getComments(workspaceId: string, taskPath: string): Promise<TaskComment[]> {
        const file = this.getStorageFile(workspaceId, taskPath);
        if (!fs.existsSync(file)) {
            return [];
        }
        try {
            const content = await fs.promises.readFile(file, 'utf8');
            const storage: CommentsStorage = JSON.parse(content);
            return storage.comments || [];
        } catch {
            return [];
        }
    }

    /** Write comments to storage atomically (write to temp file then rename). */
    private async writeComments(
        workspaceId: string,
        taskPath: string,
        comments: TaskComment[]
    ): Promise<void> {
        this.ensureWorkspaceDir(workspaceId);
        const file = this.getStorageFile(workspaceId, taskPath);
        const storage: CommentsStorage = {
            comments,
            settings: DEFAULT_SETTINGS,
        };
        const tempFile = `${file}.tmp`;
        try {
            await fs.promises.writeFile(tempFile, JSON.stringify(storage, null, 2), 'utf8');
            await fs.promises.rename(tempFile, file);
        } catch (error) {
            // Clean up temp file on error
            try { await fs.promises.unlink(tempFile); } catch { /* ignore */ }
            throw error;
        }
    }

    /** Add a new comment. */
    async addComment(
        workspaceId: string,
        taskPath: string,
        commentData: Omit<TaskComment, 'id' | 'createdAt' | 'updatedAt'>
    ): Promise<TaskComment> {
        const comments = await this.getComments(workspaceId, taskPath);
        const now = new Date().toISOString();
        const newComment: TaskComment = {
            ...commentData,
            id: crypto.randomUUID(),
            createdAt: now,
            updatedAt: now,
        };
        comments.push(newComment);
        await this.writeComments(workspaceId, taskPath, comments);
        return newComment;
    }

    /** Update an existing comment. Returns null if not found. */
    async updateComment(
        workspaceId: string,
        taskPath: string,
        commentId: string,
        updates: Partial<Omit<TaskComment, 'id' | 'createdAt'>>
    ): Promise<TaskComment | null> {
        const comments = await this.getComments(workspaceId, taskPath);
        const index = comments.findIndex(c => c.id === commentId);
        if (index === -1) {
            return null;
        }
        comments[index] = {
            ...comments[index],
            ...updates,
            id: comments[index].id,
            createdAt: comments[index].createdAt,
            updatedAt: new Date().toISOString(),
        };
        await this.writeComments(workspaceId, taskPath, comments);
        return comments[index];
    }

    /** Delete a comment. Returns false if not found. */
    async deleteComment(
        workspaceId: string,
        taskPath: string,
        commentId: string
    ): Promise<boolean> {
        const comments = await this.getComments(workspaceId, taskPath);
        const filtered = comments.filter(c => c.id !== commentId);
        if (filtered.length === comments.length) {
            return false;
        }
        await this.writeComments(workspaceId, taskPath, filtered);
        return true;
    }

    /** Get a single comment by ID. Returns null if not found. */
    async getComment(
        workspaceId: string,
        taskPath: string,
        commentId: string
    ): Promise<TaskComment | null> {
        const comments = await this.getComments(workspaceId, taskPath);
        return comments.find(c => c.id === commentId) || null;
    }

    /** Delete all comments for a task file. */
    async deleteAllComments(workspaceId: string, taskPath: string): Promise<void> {
        const file = this.getStorageFile(workspaceId, taskPath);
        if (fs.existsSync(file)) {
            await fs.promises.unlink(file);
        }
    }

    /** Add a reply to a comment. Returns null if comment not found. */
    async addReply(
        workspaceId: string,
        taskPath: string,
        commentId: string,
        replyData: { author: string; text: string; isAI?: boolean }
    ): Promise<TaskCommentReply | null> {
        const comments = await this.getComments(workspaceId, taskPath);
        const index = comments.findIndex(c => c.id === commentId);
        if (index === -1) return null;

        const reply: TaskCommentReply = {
            id: crypto.randomUUID(),
            author: replyData.author,
            text: replyData.text,
            createdAt: new Date().toISOString(),
            isAI: replyData.isAI,
        };

        if (!comments[index].replies) {
            comments[index].replies = [];
        }
        comments[index].replies!.push(reply);
        comments[index].updatedAt = new Date().toISOString();
        await this.writeComments(workspaceId, taskPath, comments);
        return reply;
    }

    /**
     * Get comment counts for all task files in a workspace.
     * Returns a map of filePath → comment count.
     */
    async getCommentCounts(workspaceId: string): Promise<Record<string, number>> {
        const wsDir = this.getWorkspaceDir(workspaceId);
        if (!fs.existsSync(wsDir)) {
            return {};
        }
        const counts: Record<string, number> = {};
        let entries: string[];
        try {
            entries = await fs.promises.readdir(wsDir);
        } catch {
            return {};
        }
        for (const entry of entries) {
            if (!entry.endsWith('.json')) continue;
            try {
                const content = await fs.promises.readFile(path.join(wsDir, entry), 'utf8');
                const storage: CommentsStorage = JSON.parse(content);
                const comments = storage.comments || [];
                if (comments.length > 0 && comments[0].filePath) {
                    counts[comments[0].filePath] = comments.length;
                }
            } catch {
                // Skip corrupted files
            }
        }
        return counts;
    }
}

// ============================================================================
// Validation Helpers
// ============================================================================

/** Required fields for creating a comment. */
const REQUIRED_FIELDS = ['filePath', 'selection', 'selectedText', 'comment'] as const;

/** Validate that the comment body has all required fields. Returns the missing field name or null. */
function findMissingField(body: any): string | null {
    for (const field of REQUIRED_FIELDS) {
        if (body[field] === undefined || body[field] === null) {
            return field;
        }
    }
    return null;
}

/** Validate workspace ID to prevent path traversal. */
function isValidWorkspaceId(wsId: string): boolean {
    return /^[a-zA-Z0-9_-]+$/.test(wsId) && !wsId.includes('..');
}

// ============================================================================
// Route Registration
// ============================================================================

/**
 * Register task comments API routes on the given route table.
 * Mutates the `routes` array in-place.
 *
 * Endpoints:
 *   GET    /api/comment-counts/:wsId                   — comment counts per file
 *   GET    /api/comments/:wsId/:taskPath(*)           — list comments
 *   POST   /api/comments/:wsId/:taskPath(*)           — create comment
 *   GET    /api/comments/:wsId/:taskPath(*)/:id       — get single comment
 *   PATCH  /api/comments/:wsId/:taskPath(*)/:id       — update comment
 *   DELETE /api/comments/:wsId/:taskPath(*)/:id       — delete comment
 *   POST   /api/comments/:wsId/:taskPath(*)/:id/replies   — add reply
 *   POST   /api/comments/:wsId/:taskPath(*)/:id/ask-ai    — AI clarification
 *   POST   /api/comments/:wsId/:taskPath(*)/batch-resolve — batch AI resolve
 *
 * @param routes - Shared route table
 * @param dataDir - Directory for comment storage (e.g. ~/.coc)
 * @param bridge - Optional multi-repo queue bridge for async AI execution
 * @param store - Optional process store for workspace resolution
 */
export function registerTaskCommentsRoutes(routes: Route[], dataDir: string, bridge?: MultiRepoQueueExecutorBridge, store?: ProcessStore): void {
    const manager = new TaskCommentsManager(dataDir);

    /**
     * Resolve workspace rootPath from a workspace ID via the process store.
     */
    async function resolveWorkspacePath(wsId: string): Promise<string | undefined> {
        if (!store) return undefined;
        try {
            const workspaces = await store.getWorkspaces();
            const ws = workspaces.find((w: any) => w.id === wsId.trim());
            return ws?.rootPath;
        } catch {
            return undefined;
        }
    }

    /**
     * Enqueue a resolve-comments task via the multi-repo bridge.
     * Returns the task ID, or undefined if the bridge is unavailable.
     */
    async function enqueueResolveTask(
        wsId: string,
        taskPath: string,
        commentIds: string[],
        prompt: string,
        documentContent: string,
    ): Promise<string | undefined> {
        if (!bridge) return undefined;
        const rootPath = await resolveWorkspacePath(wsId) || process.cwd();
        bridge.getOrCreateBridge(rootPath);
        const queueManager = bridge.registry.getQueueForRepo(rootPath);
        const input: CreateTaskInput = {
            type: 'resolve-comments',
            priority: 'normal',
            payload: {
                documentUri: taskPath,
                commentIds,
                promptTemplate: prompt,
                workingDirectory: rootPath,
                documentContent,
                filePath: taskPath,
            },
            config: {},
            displayName: `Resolve comments: ${taskPath}`,
        };
        return queueManager.enqueue(input);
    }

    // Pattern for comment counts endpoint: /api/comment-counts/{wsId}
    const countsPattern = /^\/api\/comment-counts\/([a-zA-Z0-9_-]+)$/;

    // Pattern for collection endpoints: /api/comments/{wsId}/{taskPath...}
    // taskPath is everything after the wsId segment, captured greedily.
    const collectionPattern = /^\/api\/comments\/([a-zA-Z0-9_-]+)\/(.+)$/;

    // Pattern for item endpoints: /api/comments/{wsId}/{taskPath...}/{uuid}
    // UUID is a standard v4 UUID at the end of the path.
    const itemPattern = /^\/api\/comments\/([a-zA-Z0-9_-]+)\/(.+)\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;

    // Pattern for reply endpoints: /api/comments/{wsId}/{taskPath...}/{uuid}/replies
    const replyPattern = /^\/api\/comments\/([a-zA-Z0-9_-]+)\/(.+)\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\/replies$/;

    // Pattern for AI ask endpoint: /api/comments/{wsId}/{taskPath...}/{uuid}/ask-ai
    const askAiPattern = /^\/api\/comments\/([a-zA-Z0-9_-]+)\/(.+)\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\/ask-ai$/;

    // Pattern for batch resolve endpoint: /api/comments/{wsId}/{taskPath...}/batch-resolve
    const batchResolvePattern = /^\/api\/comments\/([a-zA-Z0-9_-]+)\/(.+)\/batch-resolve$/;

    // ------------------------------------------------------------------
    // GET /api/comment-counts/:wsId — comment counts per file
    // ------------------------------------------------------------------
    routes.push({
        method: 'GET',
        pattern: countsPattern,
        handler: async (_req, res, match) => {
            const [, wsId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            try {
                const counts = await manager.getCommentCounts(wsId);
                sendJSON(res, 200, { counts });
            } catch {
                sendError(res, 500, 'Failed to retrieve comment counts');
            }
        },
    });

    // ------------------------------------------------------------------
    // GET /api/comments/:wsId/:taskPath(*)/:id — single comment
    // (Must be before the collection GET to avoid greedy match)
    // ------------------------------------------------------------------
    routes.push({
        method: 'GET',
        pattern: itemPattern,
        handler: async (_req, res, match) => {
            const [, wsId, taskPath, commentId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            try {
                const comment = await manager.getComment(wsId, taskPath, commentId);
                if (!comment) {
                    return sendError(res, 404, 'Comment not found');
                }
                sendJSON(res, 200, { comment });
            } catch {
                sendError(res, 500, 'Failed to retrieve comment');
            }
        },
    });

    // ------------------------------------------------------------------
    // GET /api/comments/:wsId/:taskPath(*) — list all comments
    // ------------------------------------------------------------------
    routes.push({
        method: 'GET',
        pattern: collectionPattern,
        handler: async (_req, res, match) => {
            const [, wsId, taskPath] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            try {
                const comments = await manager.getComments(wsId, taskPath);
                sendJSON(res, 200, { comments });
            } catch {
                sendError(res, 500, 'Failed to retrieve comments');
            }
        },
    });

    // ------------------------------------------------------------------
    // POST /api/comments/:wsId/:taskPath(*)/:id/replies — add reply
    // (Must be before the collection POST to avoid greedy match)
    // ------------------------------------------------------------------
    routes.push({
        method: 'POST',
        pattern: replyPattern,
        handler: async (req, res, match) => {
            const [, wsId, taskPath, commentId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }
            if (!body.text || typeof body.text !== 'string') {
                return sendError(res, 400, 'Missing required field: text');
            }
            try {
                const reply = await manager.addReply(wsId, taskPath, commentId, {
                    author: body.author || 'Anonymous',
                    text: body.text,
                    isAI: body.isAI,
                });
                if (!reply) {
                    return sendError(res, 404, 'Comment not found');
                }
                sendJSON(res, 201, { reply });
            } catch {
                sendError(res, 500, 'Failed to add reply');
            }
        },
    });

    // ------------------------------------------------------------------
    // POST /api/comments/:wsId/:taskPath(*)/:id/ask-ai — AI clarification
    // (Must be before the collection POST to avoid greedy match)
    // ------------------------------------------------------------------
    routes.push({
        method: 'POST',
        pattern: askAiPattern,
        handler: async (req, res, match) => {
            const [, wsId, taskPath, commentId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }
            try {
                const comment = await manager.getComment(wsId, taskPath, commentId);
                if (!comment) {
                    return sendError(res, 404, 'Comment not found');
                }

                // Extract new optional body fields
                const commandId: string | undefined = body.commandId;
                const customQuestion: string | undefined = body.customQuestion;
                const documentContext: DocumentContext | undefined = body.documentContext;

                // Resolve branch — returns revised document content, not a Q&A reply
                if (commandId === 'resolve') {
                    const documentContent: string | undefined = body.documentContent;
                    if (!documentContent || typeof documentContent !== 'string') {
                        return sendError(res, 400, 'Missing required field: documentContent');
                    }
                    const resolvePrompt = buildBatchResolvePrompt([comment], documentContent, taskPath);

                    // Try async queue path first
                    try {
                        const taskId = await enqueueResolveTask(wsId, taskPath, [comment.id], resolvePrompt, documentContent);
                        if (taskId) {
                            return sendJSON(res, 202, { taskId });
                        }
                    } catch {
                        // Fall through to direct AI invocation
                    }

                    // Fallback: direct AI invocation when bridge is unavailable
                    let revisedContent: string;
                    try {
                        const { createCLIAIInvoker } = await import('../ai-invoker');
                        const invoker = createCLIAIInvoker({ approvePermissions: false });
                        const result = await invoker(resolvePrompt, { timeoutMs: 120000 });
                        if (!result.success) {
                            return sendError(res, 502, result.error || 'AI request failed');
                        }
                        revisedContent = result.response || '';
                    } catch {
                        return sendError(res, 503, 'AI service unavailable');
                    }
                    return sendJSON(res, 200, { revisedContent, commentId: comment.id });
                }

                let prompt: string;
                if (commandId) {
                    const command = DEFAULT_AI_COMMANDS.find(c => c.id === commandId);
                    if (command) {
                        prompt = buildEnrichedPrompt(command, comment, customQuestion, documentContext);
                    } else {
                        // Unknown commandId: fall back to legacy behavior with question text
                        const question = customQuestion || body.question || 'Please explain this section and suggest improvements.';
                        prompt = buildAIPrompt(comment, question);
                    }
                } else {
                    // Legacy path: no commandId supplied
                    const question = body.question || 'Please explain this section and suggest improvements.';
                    prompt = buildAIPrompt(comment, question);
                }

                // Try to invoke AI
                let aiResponse: string;
                try {
                    const { createCLIAIInvoker } = await import('../ai-invoker');
                    const invoker = createCLIAIInvoker({ approvePermissions: false });
                    const result = await invoker(prompt, { timeoutMs: 60000 });
                    if (!result.success) {
                        return sendError(res, 502, result.error || 'AI request failed');
                    }
                    aiResponse = result.response || '';
                } catch {
                    return sendError(res, 503, 'AI service unavailable');
                }

                // Store AI response on the comment
                await manager.updateComment(wsId, taskPath, commentId, { aiResponse });

                // Also add as an AI reply
                const reply = await manager.addReply(wsId, taskPath, commentId, {
                    author: 'AI',
                    text: aiResponse,
                    isAI: true,
                });

                sendJSON(res, 200, { aiResponse, reply });
            } catch {
                sendError(res, 500, 'Failed to process AI request');
            }
        },
    });

    // ------------------------------------------------------------------
    // POST /api/comments/:wsId/:taskPath(*)/batch-resolve — batch AI resolve
    // (Must be before the collection POST to avoid greedy match)
    // ------------------------------------------------------------------
    routes.push({
        method: 'POST',
        pattern: batchResolvePattern,
        handler: async (req, res, match) => {
            const [, wsId, taskPath] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }

            const documentContent: string | undefined = body.documentContent;
            if (!documentContent || typeof documentContent !== 'string') {
                return sendError(res, 400, 'Missing required field: documentContent');
            }

            // Load and filter open comments
            const allComments = await manager.getComments(wsId, taskPath);
            const openComments = allComments.filter(c => c.status === 'open');
            if (openComments.length === 0) {
                return sendError(res, 400, 'No open comments to resolve');
            }

            // Build prompt and invoke AI
            const prompt = buildBatchResolvePrompt(openComments, documentContent, taskPath);
            const commentIds = openComments.map(c => c.id);

            // Try async queue path first
            try {
                const taskId = await enqueueResolveTask(wsId, taskPath, commentIds, prompt, documentContent);
                if (taskId) {
                    return sendJSON(res, 202, { taskId });
                }
            } catch {
                // Fall through to direct AI invocation
            }

            // Fallback: direct AI invocation when bridge is unavailable
            let revisedContent: string;
            try {
                const { createCLIAIInvoker } = await import('../ai-invoker');
                const invoker = createCLIAIInvoker({ approvePermissions: false });
                const result = await invoker(prompt, { timeoutMs: 120000 });
                if (!result.success) {
                    return sendError(res, 502, result.error || 'AI request failed');
                }
                revisedContent = result.response || '';
            } catch {
                return sendError(res, 503, 'AI service unavailable');
            }

            sendJSON(res, 200, {
                revisedContent,
                commentIds,
            });
        },
    });

    // ------------------------------------------------------------------
    // POST /api/comments/:wsId/:taskPath(*) — create comment
    // ------------------------------------------------------------------
    routes.push({
        method: 'POST',
        pattern: collectionPattern,
        handler: async (req, res, match) => {
            const [, wsId, taskPath] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }
            const missing = findMissingField(body);
            if (missing) {
                return sendError(res, 400, `Missing required field: ${missing}`);
            }
            if (!body.status) {
                body.status = 'open';
            }
            try {
                const comment = await manager.addComment(wsId, taskPath, body);
                sendJSON(res, 201, { comment });
            } catch {
                sendError(res, 500, 'Failed to create comment');
            }
        },
    });

    // ------------------------------------------------------------------
    // PATCH /api/comments/:wsId/:taskPath(*)/:id — update comment
    // ------------------------------------------------------------------
    routes.push({
        method: 'PATCH',
        pattern: itemPattern,
        handler: async (req, res, match) => {
            const [, wsId, taskPath, commentId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            let body: any;
            try {
                body = await parseBody(req);
            } catch {
                return sendError(res, 400, 'Invalid JSON');
            }
            try {
                const comment = await manager.updateComment(wsId, taskPath, commentId, body);
                if (!comment) {
                    return sendError(res, 404, 'Comment not found');
                }
                sendJSON(res, 200, { comment });
            } catch {
                sendError(res, 500, 'Failed to update comment');
            }
        },
    });

    // ------------------------------------------------------------------
    // DELETE /api/comments/:wsId/:taskPath(*)/:id — delete comment
    // ------------------------------------------------------------------
    routes.push({
        method: 'DELETE',
        pattern: itemPattern,
        handler: async (_req, res, match) => {
            const [, wsId, taskPath, commentId] = match!;
            if (!isValidWorkspaceId(wsId)) {
                return sendError(res, 400, 'Invalid workspace ID');
            }
            try {
                const deleted = await manager.deleteComment(wsId, taskPath, commentId);
                if (!deleted) {
                    return sendError(res, 404, 'Comment not found');
                }
                res.writeHead(204);
                res.end();
            } catch {
                sendError(res, 500, 'Failed to delete comment');
            }
        },
    });
}

/**
 * Build an enriched prompt using a named AI command and optional document context.
 */
function buildEnrichedPrompt(
    command: AICommand,
    comment: TaskComment,
    customQuestion: string | undefined,
    docCtx: DocumentContext | undefined
): string {
    const promptTemplate =
        command.isCustomInput && customQuestion ? customQuestion : command.prompt;

    const context: PromptContext = {
        selectedText: comment.selectedText,
        filePath: docCtx?.filePath ?? comment.filePath,
        surroundingContent: docCtx?.surroundingLines,
        nearestHeading: docCtx?.nearestHeading ?? null,
        headings: docCtx?.allHeadings,
    };

    return buildPromptFromContext(promptTemplate, context);
}

/**
 * Build a document revision prompt for one or more open comments.
 * Ported from VS Code's PromptGenerator.generateMarkdownPrompt().
 *
 * @param comments       - Array of TaskComment objects; only status==='open' are included.
 * @param documentContent - Full raw markdown content of the document.
 * @param filePath       - Relative task path (used for display only).
 * @returns Structured prompt string. The AI must output ONLY the revised document.
 */
export function buildBatchResolvePrompt(
    comments: TaskComment[],
    documentContent: string,
    filePath: string
): string {
    const openComments = comments
        .filter(c => c.status === 'open')
        .sort((a, b) => a.selection.startLine - b.selection.startLine);

    let prompt = '# Document Revision Request\n\n';
    prompt += 'Please review and address the following comments in the markdown document.\n';
    prompt += 'For each comment, make the necessary changes to the document.\n\n';
    prompt += '---\n\n';
    prompt += `## File: ${filePath}\n\n`;
    prompt += '### Full Document Content\n\n';
    prompt += '```markdown\n';
    prompt += documentContent;
    prompt += '\n```\n\n';

    openComments.forEach((c, i) => {
        prompt += `### Comment ${i + 1} (Line ${c.selection.startLine})\n\n`;
        prompt += `**ID:** \`${c.id}\`\n\n`;
        prompt += '**Selected Text:**\n```\n';
        prompt += c.selectedText;
        prompt += '\n```\n\n';
        prompt += `**Comment:** ${c.comment}\n\n`;
        prompt += '**Requested Action:** Revise this section to address the comment.\n\n';
    });

    prompt += '---\n\n';
    prompt += '# Instructions\n\n';
    prompt += '1. For each comment above, modify the corresponding section in the document\n';
    prompt += '2. Preserve the overall document structure and formatting\n';
    prompt += '3. Output the COMPLETE revised document content\n';
    prompt += '4. Do NOT include any markdown fencing or explanation — output ONLY the revised document\n';

    return prompt;
}

/**
 * Build a prompt for AI clarification from a comment.
 */
function buildAIPrompt(comment: TaskComment, question: string): string {
    let prompt = 'Context: The user is reviewing a markdown task document.\n';
    if (comment.selectedText) {
        prompt += 'They selected the following text:\n---\n' + comment.selectedText + '\n---\n\n';
    }
    if (comment.comment) {
        prompt += 'Their comment says: "' + comment.comment + '"\n\n';
    }
    prompt += 'Question: ' + question + '\n\nProvide a clear, actionable response.';
    return prompt;
}
