/**
 * TaskCommentsManager — types, constants, and manager class for task comments.
 *
 * Extracted from task-comments-handler.ts to reduce file size.
 * The route registration remains in task-comments-handler.ts.
 */

import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { getRepoDataPath } from './paths';
import { BaseCommentsManager } from './base-comments-manager';

// ============================================================================
// Types
// ============================================================================

/**
 * Comment on a task file, compatible with extension format.
 */
export interface TaskComment {
    /** Unique identifier (UUID). */
    id: string;
    /** Relative path to task file. */
    filePath: string;
    /** Selection range in the file. */
    selection: {
        startLine: number;
        startColumn: number;
        endLine: number;
        endColumn: number;
    };
    /** The actual selected text. */
    selectedText: string;
    /** User's comment content. */
    comment: string;
    /** Current status. */
    status: 'open' | 'resolved' | 'pending';
    /** ISO timestamp when created. */
    createdAt: string;
    /** ISO timestamp when last updated. */
    updatedAt: string;
    /** Optional author name. */
    author?: string;
    /** Optional tags. */
    tags?: string[];
    /** Optional comment category. */
    category?: string;
    /** Optional anchor for robust location tracking. */
    anchor?: CommentAnchor;
    /** Threaded replies to this comment. */
    replies?: TaskCommentReply[];
    /** AI-generated clarification response. */
    aiResponse?: string;
}

/**
 * A reply to a comment.
 */
export interface TaskCommentReply {
    /** Unique identifier (UUID). */
    id: string;
    /** Author name. */
    author: string;
    /** Reply text content. */
    text: string;
    /** ISO timestamp when created. */
    createdAt: string;
    /** Whether this reply was generated by AI. */
    isAI?: boolean;
}

/**
 * Anchor context for robust comment location tracking.
 */
export interface CommentAnchor {
    selectedText: string;
    contextBefore: string;
    contextAfter: string;
    originalLine: number;
    textHash: string;
}

/**
 * Optional document context supplied by the client to enrich AI prompts.
 */
export interface DocumentContext {
    /** Lines surrounding the selection (excluding the selection itself). */
    surroundingLines?: string;
    /** Nearest markdown heading above the selection. */
    nearestHeading?: string;
    /** All headings in the document. */
    allHeadings?: string[];
    /** Relative path of the source file (overrides comment.filePath if provided). */
    filePath?: string;
}

/**
 * Storage format (matches extension's format).
 */
export interface CommentsStorage {
    comments: TaskComment[];
    settings: {
        showResolved: boolean;
        highlightColor: string;
    };
}

// ============================================================================
// Constants
// ============================================================================

/** Sub-directory name for task comments storage. */
export const COMMENTS_DIR_NAME = 'tasks-comments';

/** Default settings for new comment storage files. */
export const DEFAULT_SETTINGS: CommentsStorage['settings'] = {
    showResolved: true,
    highlightColor: '#ffeb3b',
};

// ============================================================================
// TaskCommentsManager
// ============================================================================

/**
 * Manages task comments storage and operations.
 * Mirrors extension's CommentsManager but for server-side use.
 */
export class TaskCommentsManager extends BaseCommentsManager<TaskComment, TaskCommentReply> {
    private readonly dataDir: string;

    /**
     * @param dataDir - Root data directory (e.g. ~/.coc)
     */
    constructor(dataDir: string) {
        super();
        this.dataDir = dataDir;
    }

    /** Get comments directory for a workspace. */
    protected getWorkspaceDir(workspaceId: string): string {
        return getRepoDataPath(this.dataDir, workspaceId, COMMENTS_DIR_NAME);
    }

    /** Build the storage envelope for serialization. */
    protected buildStorage(comments: TaskComment[]): CommentsStorage {
        return { comments, settings: DEFAULT_SETTINGS };
    }

    /**
     * Hash file path to create storage filename.
     * Uses SHA-256 for consistent, collision-resistant hashes.
     */
    hashFilePath(filePath: string): string {
        return crypto.createHash('sha256').update(filePath).digest('hex');
    }

    /** Get storage file path for a task file (hashes the taskPath). */
    protected override getStorageFile(workspaceId: string, taskPath: string): string {
        const hash = this.hashFilePath(taskPath);
        return path.join(this.getWorkspaceDir(workspaceId), `${hash}.json`);
    }

    /**
     * Get storage file path with fallback to legacy `.vscode/tasks/`-prefixed hash.
     * Tries the current hash first; if the file doesn't exist, tries the legacy path.
     */
    getStorageFileWithFallback(workspaceId: string, taskPath: string): { file: string; usedLegacy: boolean } {
        const primary = this.getStorageFile(workspaceId, taskPath);
        if (fs.existsSync(primary)) {
            return { file: primary, usedLegacy: false };
        }
        // Fallback: try the old `.vscode/tasks/` prefix
        const legacyPath = '.vscode/tasks/' + taskPath;
        const legacyFile = path.join(
            this.getWorkspaceDir(workspaceId),
            `${this.hashFilePath(legacyPath)}.json`
        );
        if (fs.existsSync(legacyFile)) {
            return { file: legacyFile, usedLegacy: true };
        }
        return { file: primary, usedLegacy: false };
    }

    /** Read all comments for a task file, with fallback to legacy hash. */
    override async getComments(workspaceId: string, taskPath: string): Promise<TaskComment[]> {
        const { file } = this.getStorageFileWithFallback(workspaceId, taskPath);
        if (!fs.existsSync(file)) {
            return [];
        }
        try {
            const content = await fs.promises.readFile(file, 'utf8');
            const storage: CommentsStorage = JSON.parse(content);
            return storage.comments || [];
        } catch {
            return [];
        }
    }

    /** Add a new comment. */
    async addComment(
        workspaceId: string,
        taskPath: string,
        commentData: Omit<TaskComment, 'id' | 'createdAt' | 'updatedAt'>
    ): Promise<TaskComment> {
        return this.addCommentCore(workspaceId, taskPath, commentData);
    }

    /** Delete all comments for a task file. */
    async deleteAllComments(workspaceId: string, taskPath: string): Promise<void> {
        const file = this.getStorageFile(workspaceId, taskPath);
        if (fs.existsSync(file)) {
            await fs.promises.unlink(file);
        }
    }

    /**
     * Get comment counts for all task files in a workspace.
     * Returns a map of filePath → comment count.
     */
    async getCommentCounts(workspaceId: string): Promise<Record<string, number>> {
        const wsDir = this.getWorkspaceDir(workspaceId);
        if (!fs.existsSync(wsDir)) {
            return {};
        }
        const counts: Record<string, number> = {};
        let entries: string[];
        try {
            entries = await fs.promises.readdir(wsDir);
        } catch {
            return {};
        }
        for (const entry of entries) {
            if (!entry.endsWith('.json')) continue;
            try {
                const content = await fs.promises.readFile(path.join(wsDir, entry), 'utf8');
                const storage: CommentsStorage = JSON.parse(content);
                const comments = storage.comments || [];
                if (comments.length > 0 && comments[0].filePath) {
                    counts[comments[0].filePath] = comments.length;
                }
            } catch {
                // Skip corrupted files
            }
        }
        return counts;
    }
}
