/**
 * Map-Reduce AI Framework
 *
 * A reusable framework for AI map-reduce workflows.
 * Provides pluggable splitters, mappers, reducers, and prompt templates
 * with consistent UI/process tracking.
 *
 * Cross-platform compatible (Linux/Mac/Windows).
 *
 * NOTE: All map-reduce functionality is now provided by the pipeline-core package.
 * This module re-exports everything from pipeline-core for backward compatibility.
 */

// ============================================================================
// Re-export everything from pipeline-core's map-reduce module
// ============================================================================
export {
    // Core types
    WorkItem,
    MapContext,
    MapResult,
    ReduceContext,
    ReduceResult,
    ReduceStats,
    ReduceMode,
    MapReduceOptions,
    Splitter,
    Mapper,
    Reducer,
    MapReduceJob,
    ProgressCallback,
    JobProgress,
    MapReduceResult,
    ExecutionStats,
    PromptTemplate,
    PromptRenderOptions,
    AIInvoker,
    AIInvokerOptions,
    AIInvokerResult,
    ProcessTracker,
    ExecutorOptions,
    SessionMetadata,
    DEFAULT_MAP_REDUCE_OPTIONS,
    // Executor
    MapReduceExecutor,
    createExecutor,
    // Concurrency limiter
    ConcurrencyLimiter,
    CancellationError,
    DEFAULT_MAX_CONCURRENCY,
    // Prompt template
    renderTemplate,
    createTemplate,
    extractVariables,
    validateTemplate,
    composeTemplates,
    TemplateHelpers,
    ResponseParsers,
    MissingVariableError,
    TemplateRenderError,
    // Reducers
    BaseReducer,
    IdentityReducer,
    FlattenReducer,
    AggregatingReducer,
    DeterministicReducer,
    createDeterministicReducer,
    StringDeduplicationReducer,
    NumericAggregationReducer,
    AIReducer,
    createAIReducer,
    createTextSynthesisReducer,
    HybridReducer,
    createHybridReducer,
    createSimpleHybridReducer,
    Deduplicatable,
    DeterministicReducerOptions,
    DeterministicReduceOutput,
    AIReducerOptions,
    TextSynthesisOutput,
    TextSynthesisOptions,
    HybridReducerOptions,
    SimplePolishedOutput,
    // Splitters
    FileSplitter,
    createFileSplitter,
    createExtensionFilteredSplitter,
    BatchedFileSplitter,
    createBatchedFileSplitter,
    ChunkSplitter,
    createChunkSplitter,
    createLineChunkSplitter,
    createParagraphChunkSplitter,
    RuleSplitter,
    createRuleSplitter,
    createAlphabeticRuleSplitter,
    createPriorityRuleSplitter,
    createPatternFilteredRuleSplitter,
    BatchedRuleSplitter,
    createBatchedRuleSplitter,
    FileItem,
    FileInput,
    FileWorkItemData,
    FileSplitterOptions,
    BatchedFileWorkItemData,
    ChunkInput,
    ChunkWorkItemData,
    ChunkSplitterOptions,
    Rule,
    RuleInput,
    RuleWorkItemData,
    RuleSplitterOptions,
    BatchedRuleWorkItemData,
    // Jobs
    createCodeReviewJob,
    createTemplateJob,
    createSimpleTemplateJob,
    createJsonTemplateJob,
    createListProcessingJob,
    createPromptMapJob,
    createPromptMapInput,
    ReviewSeverity,
    ReviewFinding,
    RuleReviewResult,
    ReviewSummary,
    CodeReviewOutput,
    CodeReviewInput,
    CodeReviewJobOptions,
    TemplateItem,
    TemplateJobInput,
    TemplateWorkItemData,
    TemplateItemResult,
    TemplateJobOptions,
    PromptItem,
    PromptMapInput,
    PromptWorkItemData,
    PromptMapResult,
    PromptMapOutput,
    PromptMapSummary,
    PromptMapJobOptions,
    OutputFormat,
    // Temp file utilities
    writeTempFile,
    readTempFile,
    cleanupTempFile,
    cleanupAllTempFiles,
    ensureTempDir,
    generateTempFileName,
    isTempFilePath,
    getTempDirPath,
    TempFileResult
} from '@anthropic-ai/pipeline-core';
