/**
 * NotesGitService Tests
 *
 * Integration tests that exercise the NotesGitService against a real git repo
 * in a temporary directory. Each test creates a fresh temp dir and cleans up.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { NotesGitService } from '../../src/server/notes-git-service';
import { safeRmSync } from '../helpers/safe-rm';

describe('NotesGitService', { timeout: 60_000 }, () => {
    let tmpDir: string;
    let service: NotesGitService;

    beforeEach(() => {
        tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'notes-git-svc-'));
        service = new NotesGitService(tmpDir);
    });

    afterEach(() => {
        safeRmSync(tmpDir);
    });

    // Helper: write a file in the notes directory
    function writeFile(relativePath: string, content: string): void {
        const filePath = path.join(tmpDir, relativePath);
        const dir = path.dirname(filePath);
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(filePath, content, 'utf-8');
    }

    // ========================================================================
    // isInitialized
    // ========================================================================
    describe('isInitialized', () => {
        it('returns false before init', async () => {
            expect(await service.isInitialized()).toBe(false);
        });

        it('returns true after init', async () => {
            await service.init();
            expect(await service.isInitialized()).toBe(true);
        });

        it('returns false for non-existent directory', async () => {
            const nonExistent = new NotesGitService(path.join(tmpDir, 'does-not-exist'));
            expect(await nonExistent.isInitialized()).toBe(false);
        });
    });

    // ========================================================================
    // init
    // ========================================================================
    describe('init', () => {
        it('creates .git directory and .gitignore', async () => {
            await service.init();

            expect(fs.existsSync(path.join(tmpDir, '.git'))).toBe(true);
            expect(fs.statSync(path.join(tmpDir, '.git')).isDirectory()).toBe(true);

            const gitignore = fs.readFileSync(path.join(tmpDir, '.gitignore'), 'utf-8');
            expect(gitignore).toContain('.DS_Store');
            expect(gitignore).toContain('Thumbs.db');
        });

        it('is idempotent — second call does not error', async () => {
            await service.init();
            await expect(service.init()).resolves.toBeUndefined();

            // Still initialized
            expect(await service.isInitialized()).toBe(true);
        });

        it('creates an initial commit', async () => {
            await service.init();

            const log = await service.getLog(10, 0);
            expect(log.length).toBeGreaterThanOrEqual(1);
            expect(log[0].message).toBe('Initial notes commit');
        });

        it('.order.json files are NOT ignored', async () => {
            const gitignore = '# Auto-generated by CoC notes git tracking\n.DS_Store\nThumbs.db\n';
            expect(gitignore).not.toContain('.order.json');
        });
    });

    // ========================================================================
    // getStatus
    // ========================================================================
    describe('getStatus', () => {
        it('returns initialized: false when no repo exists', async () => {
            const status = await service.getStatus();
            expect(status.initialized).toBe(false);
            expect(status.staged).toEqual([]);
            expect(status.unstaged).toEqual([]);
            expect(status.untracked).toEqual([]);
            expect(status.clean).toBe(true);
            expect(status.totalChanges).toBe(0);
        });

        it('returns clean status after init', async () => {
            await service.init();
            const status = await service.getStatus();
            expect(status.initialized).toBe(true);
            expect(status.clean).toBe(true);
            expect(status.staged).toEqual([]);
            expect(status.unstaged).toEqual([]);
            expect(status.untracked).toEqual([]);
            expect(status.totalChanges).toBe(0);
        });

        it('detects untracked files', async () => {
            await service.init();
            writeFile('new-note.md', '# New Note');

            const status = await service.getStatus();
            expect(status.clean).toBe(false);
            expect(status.untracked).toContain('new-note.md');
            expect(status.totalChanges).toBeGreaterThan(0);
        });

        it('detects staged files', async () => {
            await service.init();
            writeFile('staged.md', '# Staged');

            const { execGitAsync } = await import('@plusplusoneplusplus/forge/git');
            await execGitAsync(['add', 'staged.md'], tmpDir);

            const status = await service.getStatus();
            expect(status.staged).toContain('staged.md');
        });

        it('detects unstaged modifications', async () => {
            await service.init();
            writeFile('tracked.md', '# Tracked');

            const { execGitAsync } = await import('@plusplusoneplusplus/forge/git');
            await execGitAsync(['add', 'tracked.md'], tmpDir);
            await execGitAsync(['commit', '-m', 'add tracked'], tmpDir);

            // Now modify without staging
            writeFile('tracked.md', '# Tracked - modified');

            const status = await service.getStatus();
            expect(status.unstaged).toContain('tracked.md');
        });

        it('returns branch name', async () => {
            await service.init();
            const status = await service.getStatus();
            expect(status.branch).toBeTruthy();
            // Could be 'main' or 'master' depending on git config
            expect(['main', 'master']).toContain(status.branch);
        });
    });

    // ========================================================================
    // getLog
    // ========================================================================
    describe('getLog', () => {
        it('returns empty array when not initialized', async () => {
            const log = await service.getLog(10, 0);
            expect(log).toEqual([]);
        });

        it('returns initial commit after init', async () => {
            await service.init();
            const log = await service.getLog(10, 0);
            expect(log.length).toBeGreaterThanOrEqual(1);
            expect(log[0].message).toBe('Initial notes commit');
        });

        it('entries have correct shape', async () => {
            await service.init();
            const log = await service.getLog(10, 0);
            const entry = log[0];

            expect(entry).toHaveProperty('hash');
            expect(entry).toHaveProperty('shortHash');
            expect(entry).toHaveProperty('message');
            expect(entry).toHaveProperty('date');
            expect(entry).toHaveProperty('filesChanged');

            expect(typeof entry.hash).toBe('string');
            expect(entry.hash.length).toBe(40);
            expect(typeof entry.shortHash).toBe('string');
            expect(entry.shortHash.length).toBeGreaterThanOrEqual(7);
            expect(typeof entry.date).toBe('string');
        });

        it('respects limit', async () => {
            await service.init();

            // Create extra commits
            writeFile('a.md', 'a');
            await service.commit('commit a');
            writeFile('b.md', 'b');
            await service.commit('commit b');
            writeFile('c.md', 'c');
            await service.commit('commit c');

            const log = await service.getLog(2, 0);
            expect(log).toHaveLength(2);
        });

        it('respects offset', async () => {
            await service.init();
            writeFile('a.md', 'a');
            await service.commit('commit a');
            writeFile('b.md', 'b');
            await service.commit('commit b');

            const allLogs = await service.getLog(10, 0);
            const offsetLogs = await service.getLog(10, 1);

            expect(offsetLogs.length).toBe(allLogs.length - 1);
            // The first entry of offset list should be the second entry of the full list
            expect(offsetLogs[0].hash).toBe(allLogs[1].hash);
        });
    });

    // ========================================================================
    // getDiff
    // ========================================================================
    describe('getDiff', () => {
        it('returns empty files when not initialized', async () => {
            const diff = await service.getDiff();
            expect(diff.files).toEqual([]);
        });

        it('returns empty diff when clean', async () => {
            await service.init();
            const diff = await service.getDiff();
            expect(diff.files).toEqual([]);
        });

        it('returns diff content after modifying a file', async () => {
            await service.init();
            writeFile('test.md', '# Test');
            const { execGitAsync } = await import('@plusplusoneplusplus/forge/git');
            await execGitAsync(['add', 'test.md'], tmpDir);
            await execGitAsync(['commit', '-m', 'add test'], tmpDir);

            // Modify
            writeFile('test.md', '# Test\n\nUpdated content');

            const diff = await service.getDiff();
            expect(diff.files.length).toBeGreaterThan(0);
            const testFile = diff.files.find(f => f.path === 'test.md');
            expect(testFile).toBeDefined();
            expect(testFile!.diff).toContain('Updated content');
        });

        it('returns commit-specific diff with hash argument', async () => {
            await service.init();
            writeFile('file1.md', '# File 1');
            const result = await service.commit('add file1');
            expect(result.committed).toBe(true);

            const diff = await service.getDiff(result.hash!);
            expect(diff.files.length).toBeGreaterThan(0);
            const file = diff.files.find(f => f.path === 'file1.md');
            expect(file).toBeDefined();
        });

        it('handles parentless initial commit correctly', async () => {
            await service.init();
            const log = await service.getLog(1, 0);
            const initialHash = log[0].hash;

            // Should not throw
            const diff = await service.getDiff(initialHash);
            expect(diff.files).toBeDefined();
            // The initial commit adds .gitignore
            const gitignoreFile = diff.files.find(f => f.path === '.gitignore');
            expect(gitignoreFile).toBeDefined();
        });

        it('shows staged changes in working tree diff', async () => {
            await service.init();
            writeFile('staged.md', '# Staged content');
            const { execGitAsync } = await import('@plusplusoneplusplus/forge/git');
            await execGitAsync(['add', 'staged.md'], tmpDir);

            const diff = await service.getDiff();
            expect(diff.files.length).toBeGreaterThan(0);
            const stagedFile = diff.files.find(f => f.path === 'staged.md');
            expect(stagedFile).toBeDefined();
        });
    });

    // ========================================================================
    // commit
    // ========================================================================
    describe('commit', () => {
        it('creates commit with auto-generated message', async () => {
            await service.init();
            writeFile('note.md', '# Note');

            const result = await service.commit();
            expect(result.committed).toBe(true);
            expect(result.hash).toBeTruthy();
            expect(result.hash!.length).toBe(40);
            expect(result.message).toMatch(/^Notes snapshot /);
        });

        it('creates commit with custom message', async () => {
            await service.init();
            writeFile('note.md', '# Note');

            const result = await service.commit('My custom commit');
            expect(result.committed).toBe(true);
            expect(result.message).toBe('My custom commit');
        });

        it('returns committed: false when nothing to commit', async () => {
            await service.init();
            const result = await service.commit();
            expect(result.committed).toBe(false);
            expect(result.hash).toBeUndefined();
        });

        it('throws when not initialized', async () => {
            await expect(service.commit()).rejects.toThrow('not initialized');
        });

        it('trims whitespace from custom message', async () => {
            await service.init();
            writeFile('note.md', '# Note');

            const result = await service.commit('  padded message  ');
            expect(result.committed).toBe(true);
            expect(result.message).toBe('padded message');
        });

        it('tracks .order.json files', async () => {
            await service.init();
            writeFile('.order.json', '["a","b","c"]');

            const result = await service.commit('track order file');
            expect(result.committed).toBe(true);

            // Verify it was actually committed
            const status = await service.getStatus();
            expect(status.clean).toBe(true);
        });
    });

    // ========================================================================
    // Paths with spaces
    // ========================================================================
    describe('paths with spaces', () => {
        let spacedDir: string;
        let spacedService: NotesGitService;

        beforeEach(() => {
            // Create a temp directory whose name contains spaces
            const base = fs.mkdtempSync(path.join(os.tmpdir(), 'notes git svc '));
            spacedDir = base;
            spacedService = new NotesGitService(spacedDir);
        });

        afterEach(() => {
            safeRmSync(spacedDir);
        });

        it('init succeeds when path contains spaces', async () => {
            await spacedService.init();
            expect(await spacedService.isInitialized()).toBe(true);
        });

        it('commit succeeds when path contains spaces', async () => {
            await spacedService.init();
            const filePath = path.join(spacedDir, 'note.md');
            fs.writeFileSync(filePath, '# Hello', 'utf-8');

            const result = await spacedService.commit('test commit');
            expect(result.committed).toBe(true);
            expect(result.hash).toBeTruthy();
        });

        it('getStatus works when path contains spaces', async () => {
            await spacedService.init();
            const status = await spacedService.getStatus();
            expect(status.initialized).toBe(true);
            expect(status.clean).toBe(true);
        });
    });
});
