/**
 * Diff Comment Types
 *
 * Core TypeScript types for diff comments in the web UI.
 * Browser-compatible — no Node.js or VS Code dependencies.
 *
 * Selection and context types are re-exported from pipeline-core.
 * CoC-specific types (DiffComment, DiffCommentsData) are defined here.
 */

// Re-export diff selection/context types from pipeline-core
export type { DiffCommentSelection, DiffCommentContext } from '@plusplusoneplusplus/pipeline-core/editor/types';

// ============================================================================
// Diff Comment Types
// ============================================================================

/** Comment status values. */
export type DiffCommentStatus = 'open' | 'resolved' | 'orphaned';

/** Comment categories. */
export type DiffCommentCategory = 'bug' | 'question' | 'suggestion' | 'praise' | 'nitpick' | 'general';

// ============================================================================
// Category Constants
// ============================================================================

export interface DiffCategoryInfo {
    label: string;
    icon: string;
}

export const DIFF_CATEGORY_INFO: Record<DiffCommentCategory, DiffCategoryInfo> = {
    bug:        { label: 'Bug',        icon: '🐛' },
    question:   { label: 'Question',   icon: '❓' },
    suggestion: { label: 'Suggestion', icon: '💡' },
    praise:     { label: 'Praise',     icon: '🌟' },
    nitpick:    { label: 'Nitpick',    icon: '🔍' },
    general:    { label: 'General',    icon: '💬' },
};

export const ALL_DIFF_CATEGORIES: DiffCommentCategory[] = ['bug', 'question', 'suggestion', 'praise', 'nitpick', 'general'];

/** Get category from a DiffComment (field first, then text prefix fallback). */
export function getDiffCommentCategory(comment: DiffComment): DiffCommentCategory {
    if (comment.category && ALL_DIFF_CATEGORIES.includes(comment.category)) {
        return comment.category;
    }
    const match = comment.comment.match(/^\[(bug|question|suggestion|praise|nitpick|general)\]\s*/i);
    if (match) return match[1].toLowerCase() as DiffCommentCategory;
    return 'general';
}

/**
 * A single comment on a diff in the web UI.
 */
export interface DiffComment {
    /** Unique identifier (UUID) */
    id: string;
    /** Identifies the diff (repository, file, and ref range) this comment belongs to */
    context: import('@plusplusoneplusplus/pipeline-core/editor/types').DiffCommentContext;
    /** Selection range within the rendered diff */
    selection: import('@plusplusoneplusplus/pipeline-core/editor/types').DiffCommentSelection;
    /** The actual selected text */
    selectedText: string;
    /** User's comment content */
    comment: string;
    /** Current status */
    status: DiffCommentStatus;
    /** ISO timestamp when created */
    createdAt: string;
    /** ISO timestamp when last updated */
    updatedAt: string;
    /** Optional author name */
    author?: string;
    /** Optional comment category */
    category?: DiffCommentCategory;
    /** Optional anchor for robust location tracking after diff changes */
    anchor?: import('@plusplusoneplusplus/pipeline-core/editor/types').CommentAnchor;
    /** Threaded replies to this comment */
    replies?: DiffCommentReply[];
    /** AI-generated clarification response */
    aiResponse?: string;
}

/**
 * A reply to a diff comment.
 */
export interface DiffCommentReply {
    /** Unique identifier (UUID) */
    id: string;
    /** Author name */
    author: string;
    /** Reply text content */
    text: string;
    /** ISO timestamp when created */
    createdAt: string;
    /** Whether this reply was generated by AI */
    isAI?: boolean;
}

/**
 * Container for all comments on a single diff.
 */
export interface DiffCommentsData {
    /** Stable key identifying the diff (e.g. "<repositoryId>:<filePath>:<oldRef>..<newRef>") */
    diffId: string;
    /** Array of comments */
    comments: DiffComment[];
    /** Schema version for forward compatibility */
    version: number;
}
