/**
 * Task preview mermaid diagram rendering.
 *
 * Lazily loads mermaid.js from CDN when a task preview contains mermaid blocks,
 * then renders diagrams with zoom/pan, source/preview toggle, and collapse.
 *
 * Works on the `.mermaid-container` HTML generated by pipeline-core's
 * `renderMermaidContainer()` which is called during `renderMarkdownToHtml()`.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MERMAID_CDN = 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js';
const MIN_ZOOM = 0.25;
const MAX_ZOOM = 4;
const ZOOM_STEP = 0.25;

// ---------------------------------------------------------------------------
// Mermaid global declaration
// ---------------------------------------------------------------------------

declare const mermaid: {
    initialize(config: Record<string, unknown>): void;
    run(opts: { nodes: NodeListOf<Element> | Element[] }): Promise<void>;
};

// ---------------------------------------------------------------------------
// Theme helper
// ---------------------------------------------------------------------------

function isDarkTheme(): boolean {
    const theme = document.documentElement.getAttribute('data-theme');
    if (theme === 'dark') return true;
    if (theme === 'light') return false;
    return window.matchMedia('(prefers-color-scheme: dark)').matches;
}

// ---------------------------------------------------------------------------
// Lazy loader
// ---------------------------------------------------------------------------

let mermaidLoadPromise: Promise<void> | null = null;

/**
 * Lazily load mermaid.js from CDN if not already present.
 * Returns immediately if mermaid is already loaded.
 */
export function ensureMermaid(): Promise<void> {
    if (typeof mermaid !== 'undefined' && mermaid?.initialize) {
        return Promise.resolve();
    }
    if (mermaidLoadPromise) return mermaidLoadPromise;

    mermaidLoadPromise = new Promise<void>((resolve, reject) => {
        const script = document.createElement('script');
        script.src = MERMAID_CDN;
        script.async = true;
        script.onload = () => {
            mermaid.initialize({
                startOnLoad: false,
                theme: isDarkTheme() ? 'dark' : 'default',
                securityLevel: 'loose',
                flowchart: { useMaxWidth: false, htmlLabels: true, curve: 'basis' },
                fontSize: 14,
            });
            resolve();
        };
        script.onerror = () => {
            mermaidLoadPromise = null;
            reject(new Error('Failed to load mermaid.js from CDN'));
        };
        document.head.appendChild(script);
    });
    return mermaidLoadPromise;
}

// ---------------------------------------------------------------------------
// Zoom / pan state per container
// ---------------------------------------------------------------------------

interface ZoomState {
    scale: number;
    translateX: number;
    translateY: number;
    isDragging: boolean;
    dragStartX: number;
    dragStartY: number;
    lastTX: number;
    lastTY: number;
}

function applyTransform(svgWrapper: HTMLElement, state: ZoomState, container: Element): void {
    svgWrapper.style.transform =
        'translate(' + state.translateX + 'px, ' + state.translateY + 'px) scale(' + state.scale + ')';
    const display = container.querySelector('.task-mermaid-zoom-level');
    if (display) display.textContent = Math.round(state.scale * 100) + '%';
}

// ---------------------------------------------------------------------------
// Toolbar injection
// ---------------------------------------------------------------------------

function buildToolbarHTML(): string {
    return '<div class="task-mermaid-toolbar">' +
        '<button class="task-mermaid-btn task-mermaid-toggle" title="Toggle source/preview">Source</button>' +
        '<button class="task-mermaid-btn task-mermaid-zoom-out" title="Zoom out">\u2212</button>' +
        '<span class="task-mermaid-zoom-level">100%</span>' +
        '<button class="task-mermaid-btn task-mermaid-zoom-in" title="Zoom in">+</button>' +
        '<button class="task-mermaid-btn task-mermaid-zoom-reset" title="Reset view">\u27F2</button>' +
        '<button class="task-mermaid-btn task-mermaid-collapse" title="Collapse">\u25BC</button>' +
        '</div>';
}

// ---------------------------------------------------------------------------
// Container transformation
// ---------------------------------------------------------------------------

/**
 * Transform a static `.mermaid-container` (from pipeline-core) into an
 * interactive one with toolbar, viewport, and mermaid-ready `<pre>`.
 */
function transformContainer(container: HTMLElement): void {
    // Extract source code from the hidden source element
    const sourceEl = container.querySelector('.mermaid-source code');
    const source = sourceEl?.textContent || '';
    if (!source.trim()) return;

    // Get the mermaid-content wrapper
    const contentDiv = container.querySelector('.mermaid-content') as HTMLElement;
    if (!contentDiv) return;

    // Inject toolbar after .mermaid-header
    const header = container.querySelector('.mermaid-header');
    if (header) {
        header.insertAdjacentHTML('afterend', buildToolbarHTML());
    }

    // Replace .mermaid-content contents with viewport structure
    contentDiv.innerHTML =
        '<div class="task-mermaid-viewport">' +
            '<div class="task-mermaid-svg-wrapper">' +
                '<pre class="mermaid">' + escapeHtmlForMermaid(source) + '</pre>' +
            '</div>' +
        '</div>' +
        '<div class="task-mermaid-source-view" style="display:none;">' +
            '<pre><code>' + escapeHtmlForMermaid(source) + '</code></pre>' +
        '</div>';
}

function escapeHtmlForMermaid(str: string): string {
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ---------------------------------------------------------------------------
// Event handlers
// ---------------------------------------------------------------------------

function setupZoomPan(container: HTMLElement): void {
    const viewport = container.querySelector('.task-mermaid-viewport') as HTMLElement | null;
    const svgWrapper = container.querySelector('.task-mermaid-svg-wrapper') as HTMLElement | null;
    if (!viewport || !svgWrapper) return;

    const state: ZoomState = {
        scale: 1, translateX: 0, translateY: 0,
        isDragging: false, dragStartX: 0, dragStartY: 0, lastTX: 0, lastTY: 0,
    };

    // Zoom in button
    container.querySelector('.task-mermaid-zoom-in')?.addEventListener('click', (e) => {
        e.stopPropagation();
        state.scale = Math.min(MAX_ZOOM, state.scale + ZOOM_STEP);
        applyTransform(svgWrapper, state, container);
    });

    // Zoom out button
    container.querySelector('.task-mermaid-zoom-out')?.addEventListener('click', (e) => {
        e.stopPropagation();
        state.scale = Math.max(MIN_ZOOM, state.scale - ZOOM_STEP);
        applyTransform(svgWrapper, state, container);
    });

    // Reset button
    container.querySelector('.task-mermaid-zoom-reset')?.addEventListener('click', (e) => {
        e.stopPropagation();
        state.scale = 1;
        state.translateX = 0;
        state.translateY = 0;
        applyTransform(svgWrapper, state, container);
    });

    // Ctrl+wheel zoom
    viewport.addEventListener('wheel', (e: WheelEvent) => {
        if (!e.ctrlKey && !e.metaKey) return;
        e.preventDefault();
        e.stopPropagation();
        const delta = e.deltaY > 0 ? -ZOOM_STEP : ZOOM_STEP;
        const newScale = Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, state.scale + delta));
        if (newScale !== state.scale) {
            const rect = viewport.getBoundingClientRect();
            const mx = e.clientX - rect.left;
            const my = e.clientY - rect.top;
            const px = (mx - state.translateX) / state.scale;
            const py = (my - state.translateY) / state.scale;
            state.scale = newScale;
            state.translateX = mx - px * state.scale;
            state.translateY = my - py * state.scale;
            applyTransform(svgWrapper, state, container);
        }
    }, { passive: false });

    // Pan: mousedown
    viewport.addEventListener('mousedown', (e: MouseEvent) => {
        if (e.button !== 0) return;
        state.isDragging = true;
        state.dragStartX = e.clientX;
        state.dragStartY = e.clientY;
        state.lastTX = state.translateX;
        state.lastTY = state.translateY;
        viewport.classList.add('task-mermaid-dragging');
        e.preventDefault();
    });

    // Pan: mousemove (document-level)
    document.addEventListener('mousemove', (e: MouseEvent) => {
        if (!state.isDragging) return;
        state.translateX = state.lastTX + (e.clientX - state.dragStartX);
        state.translateY = state.lastTY + (e.clientY - state.dragStartY);
        applyTransform(svgWrapper, state, container);
    });

    // Pan: mouseup (document-level)
    document.addEventListener('mouseup', () => {
        if (!state.isDragging) return;
        state.isDragging = false;
        viewport.classList.remove('task-mermaid-dragging');
    });
}

function setupSourceToggle(container: HTMLElement): void {
    const toggleBtn = container.querySelector('.task-mermaid-toggle') as HTMLElement | null;
    const viewport = container.querySelector('.task-mermaid-viewport') as HTMLElement | null;
    const sourceView = container.querySelector('.task-mermaid-source-view') as HTMLElement | null;
    if (!toggleBtn || !viewport || !sourceView) return;

    toggleBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        const showingSource = sourceView.style.display !== 'none';
        if (showingSource) {
            // Switch to preview
            sourceView.style.display = 'none';
            viewport.style.display = '';
            toggleBtn.textContent = 'Source';
        } else {
            // Switch to source
            viewport.style.display = 'none';
            sourceView.style.display = '';
            toggleBtn.textContent = 'Preview';
        }
    });
}

function setupCollapse(container: HTMLElement): void {
    const collapseBtn = container.querySelector('.task-mermaid-collapse') as HTMLElement | null;
    const contentDiv = container.querySelector('.mermaid-content') as HTMLElement | null;
    if (!collapseBtn || !contentDiv) return;

    collapseBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        const collapsed = contentDiv.style.display === 'none';
        if (collapsed) {
            contentDiv.style.display = '';
            collapseBtn.textContent = '\u25BC'; // ▼
            collapseBtn.title = 'Collapse';
        } else {
            contentDiv.style.display = 'none';
            collapseBtn.textContent = '\u25B6'; // ▶
            collapseBtn.title = 'Expand';
        }
    });
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Initialize mermaid rendering for all `.mermaid-container` elements within
 * the task preview body. Call this after `renderMarkdownToHtml()` has been
 * inserted into the DOM.
 *
 * No-op if there are no mermaid containers.
 */
export async function initTaskMermaid(root?: HTMLElement): Promise<void> {
    const scope = root || document.getElementById('task-preview-body');
    if (!scope) return;

    const containers = scope.querySelectorAll('.mermaid-container');
    if (containers.length === 0) return;

    // Transform each container from static to interactive
    containers.forEach((c) => transformContainer(c as HTMLElement));

    // Lazy-load mermaid.js
    try {
        await ensureMermaid();
    } catch {
        // Show error in each container
        containers.forEach((c) => {
            const preview = c.querySelector('.task-mermaid-viewport');
            if (preview) {
                preview.innerHTML = '<div class="task-mermaid-error">Failed to load diagram renderer</div>';
            }
        });
        return;
    }

    // Render mermaid diagrams
    const mermaidPres = scope.querySelectorAll('.mermaid-container .mermaid');
    if (mermaidPres.length > 0) {
        await mermaid.run({ nodes: mermaidPres });
    }

    // Set up interactive handlers for each container
    containers.forEach((c) => {
        const el = c as HTMLElement;
        setupZoomPan(el);
        setupSourceToggle(el);
        setupCollapse(el);
    });
}

/**
 * Re-initialize mermaid with the current theme. Call on theme change.
 */
export function reinitMermaidTheme(): void {
    if (typeof mermaid === 'undefined') return;
    mermaid.initialize({
        startOnLoad: false,
        theme: isDarkTheme() ? 'dark' : 'default',
        securityLevel: 'loose',
        flowchart: { useMaxWidth: false, htmlLabels: true, curve: 'basis' },
        fontSize: 14,
    });
}
