/**
 * DiffCommentsManager — types, constants, manager class, and validation helpers
 * for diff comments.
 *
 * Extracted from diff-comments-handler.ts to reduce file size.
 * The route registration remains in diff-comments-handler.ts.
 */

import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { getRepoDataPath } from '../../paths';
import { BaseCommentsManager } from './base-comments-manager';
import type { DiffComment, DiffCommentContext } from '@plusplusoneplusplus/forge';

// ============================================================================
// Types
// ============================================================================

/**
 * A reply to a diff comment.
 */
export interface DiffCommentReply {
    /** Unique identifier (UUID). */
    id: string;
    /** Author name. */
    author: string;
    /** Reply text content. */
    text: string;
    /** ISO timestamp when created. */
    createdAt: string;
    /** Whether this reply was generated by AI. */
    isAI?: boolean;
}

/**
 * Storage format for diff comments.
 */
export interface DiffCommentsStorage {
    comments: DiffComment[];
    settings: {
        showResolved: boolean;
    };
}

// ============================================================================
// Constants
// ============================================================================

/** Sub-directory name for diff comments storage. */
export const DIFF_COMMENTS_DIR_NAME = 'diff-comments';

/** Default settings for new diff comment storage files. */
export const DEFAULT_DIFF_SETTINGS: DiffCommentsStorage['settings'] = {
    showResolved: true,
};

// ============================================================================
// Validation Helpers
// ============================================================================

/** Validate storage key (SHA-256 hex, 64 chars). */
export function isValidStorageKey(key: string): boolean {
    return /^[0-9a-f]{64}$/.test(key);
}

/** Validate that a diff comment context object has all required fields. */
export function isValidContext(ctx: any): ctx is DiffCommentContext {
    return (
        ctx &&
        typeof ctx === 'object' &&
        typeof ctx.repositoryId === 'string' &&
        typeof ctx.oldRef === 'string' &&
        typeof ctx.newRef === 'string' &&
        typeof ctx.filePath === 'string'
    );
}

// ============================================================================
// DiffCommentsManager
// ============================================================================

/**
 * Manages diff comments storage and operations.
 * Keyed by sha256(context) instead of filePath.
 * Extends BaseCommentsManager for shared CRUD, read, and write logic.
 */
export class DiffCommentsManager extends BaseCommentsManager<DiffComment, DiffCommentReply> {
    private readonly dataDir: string;

    /**
     * @param dataDir - Root data directory (e.g. ~/.coc)
     */
    constructor(dataDir: string) {
        super();
        this.dataDir = dataDir;
    }

    /** Return the workspace directory (repos/<wsId>/diff-comments). */
    protected getWorkspaceDir(wsId: string): string {
        return getRepoDataPath(this.dataDir, wsId, DIFF_COMMENTS_DIR_NAME);
    }

    /** Wrap comments in the diff-specific storage envelope. */
    protected buildStorage(comments: DiffComment[]): DiffCommentsStorage {
        return { comments, settings: DEFAULT_DIFF_SETTINGS };
    }

    /**
     * Derive a storage key from a diff context.
     *
     * Fields are concatenated without a separator — clients must use the same
     * concatenation order to produce matching keys.
     *
     * Normal diff:    sha256(repositoryId + oldRef + newRef + filePath)
     * Working-tree:   sha256(repositoryId + filePath + 'working-tree')
     *                 (oldRef is omitted; 'working-tree' sentinel is appended)
     */
    hashContext(ctx: DiffCommentContext): string {
        if (ctx.newRef === 'working-tree') {
            return crypto
                .createHash('sha256')
                .update(ctx.repositoryId + ctx.filePath + 'working-tree')
                .digest('hex');
        }
        return crypto
            .createHash('sha256')
            .update(ctx.repositoryId + ctx.oldRef + ctx.newRef + ctx.filePath)
            .digest('hex');
    }

    /**
     * Add a new comment.
     * Sets `ephemeral: true` when `ctx.newRef === 'working-tree'`.
     */
    async addComment(
        wsId: string,
        ctx: DiffCommentContext,
        commentData: Omit<DiffComment, 'id' | 'createdAt' | 'updatedAt' | 'ephemeral'>
    ): Promise<DiffComment> {
        const storageKey = this.hashContext(ctx);
        const extra = ctx.newRef === 'working-tree' ? { ephemeral: true as const } : {};
        return this.addCommentCore(wsId, storageKey, { ...commentData, ...extra });
    }

    /**
     * Get comment counts for all storage keys in a workspace.
     * Returns a map of storageKey → comment count.
     *
     * @param wsId - Workspace ID
     * @param options - Optional filters:
     *   - `oldRef`    Only count comments whose context.oldRef matches.
     *   - `newRef`    Only count comments whose context.newRef matches.
     *   - `statuses`  Only count comments with one of these status values.
     *                 Defaults to all statuses when omitted.
     */
    async getCommentCounts(
        wsId: string,
        options?: { oldRef?: string; newRef?: string; statuses?: string[] }
    ): Promise<Record<string, number>> {
        const wsDir = this.getWorkspaceDir(wsId);
        if (!fs.existsSync(wsDir)) {
            return {};
        }
        const counts: Record<string, number> = {};
        let entries: string[];
        try {
            entries = await fs.promises.readdir(wsDir);
        } catch {
            return {};
        }
        for (const entry of entries) {
            if (!entry.endsWith('.json')) continue;
            try {
                const content = await fs.promises.readFile(path.join(wsDir, entry), 'utf8');
                const storage: DiffCommentsStorage = JSON.parse(content);
                let comments = storage.comments || [];

                // Filter by ref range when requested
                if (options?.oldRef !== undefined || options?.newRef !== undefined) {
                    comments = comments.filter(c => {
                        if (options?.oldRef !== undefined && c.context?.oldRef !== options.oldRef) return false;
                        if (options?.newRef !== undefined && c.context?.newRef !== options.newRef) return false;
                        return true;
                    });
                }

                // Filter by status when requested
                if (options?.statuses && options.statuses.length > 0) {
                    comments = comments.filter(c => options.statuses!.includes(c.status));
                }

                if (comments.length === 0) continue;
                const key = entry.slice(0, -5); // strip ".json"
                counts[key] = comments.length;
            } catch {
                // Skip corrupted files
            }
        }
        return counts;
    }

    /**
     * Get total active comment counts per commit hash.
     *
     * Scans all storage files in the workspace and groups comment counts by
     * `context.newRef` (commit hash).  Only hashes present in `commitHashes`
     * are included in the result, and only entries with a count > 0 are returned.
     *
     * @param wsId          - Workspace ID
     * @param commitHashes  - The commit hashes to tally
     * @param options       - Optional `statuses` filter (defaults to all statuses)
     */
    async getCommentTotals(
        wsId: string,
        commitHashes: string[],
        options?: { statuses?: string[] }
    ): Promise<Record<string, number>> {
        if (commitHashes.length === 0) return {};
        const hashSet = new Set(commitHashes);
        const wsDir = this.getWorkspaceDir(wsId);
        if (!fs.existsSync(wsDir)) {
            return {};
        }
        let entries: string[];
        try {
            entries = await fs.promises.readdir(wsDir);
        } catch {
            return {};
        }
        const totals: Record<string, number> = {};
        for (const entry of entries) {
            if (!entry.endsWith('.json')) continue;
            try {
                const content = await fs.promises.readFile(path.join(wsDir, entry), 'utf8');
                const storage: DiffCommentsStorage = JSON.parse(content);
                let comments = storage.comments || [];

                // Filter by status when requested
                if (options?.statuses && options.statuses.length > 0) {
                    comments = comments.filter(c => options.statuses!.includes(c.status));
                }

                for (const comment of comments) {
                    const ref = comment.context?.newRef;
                    if (ref && hashSet.has(ref)) {
                        totals[ref] = (totals[ref] ?? 0) + 1;
                    }
                }
            } catch {
                // Skip corrupted files
            }
        }
        return totals;
    }

    /**
     * List all comments in a workspace across all storage files.
     */
    async listAllComments(wsId: string): Promise<DiffComment[]> {
        const wsDir = this.getWorkspaceDir(wsId);
        if (!fs.existsSync(wsDir)) {
            return [];
        }
        let entries: string[];
        try {
            entries = await fs.promises.readdir(wsDir);
        } catch {
            return [];
        }
        const all: DiffComment[] = [];
        for (const entry of entries) {
            if (!entry.endsWith('.json')) continue;
            try {
                const content = await fs.promises.readFile(path.join(wsDir, entry), 'utf8');
                const storage: DiffCommentsStorage = JSON.parse(content);
                all.push(...(storage.comments || []));
            } catch {
                // Skip corrupted files
            }
        }
        return all;
    }
}
