/**
 * The generated type surface and the script that produces it.
 *
 * `src/native-bindings.ts` is generated from the `#[napi]` items but committed,
 * so `npm run build` stays plain `tsc` on a machine with no Rust toolchain. CI
 * regenerates it and fails on a diff; these tests cover the parts of that
 * arrangement a diff cannot catch.
 */

import * as fs from 'fs';
import * as path from 'path';
import { describe, expect, it } from 'vitest';

// @ts-expect-error — a .mjs build script with no type declarations.
import { BINDINGS_FILE, nativeBinaryName as scriptBinaryName, renderBindings } from '../scripts/build-native.mjs';
import { nativeBinaryName, nativeTriple } from '../src/loader';

const PACKAGE_ROOT = path.resolve(__dirname, '..');

/** Triples the release workflow publishes, as [platform, arch] pairs. */
const RELEASED: Array<[string, string]> = [
    ['linux', 'x64'],
    ['linux', 'arm64'],
    ['darwin', 'arm64'],
    ['darwin', 'x64'],
    ['win32', 'x64'],
];

describe('binary naming agrees between the build and the loader', () => {
    // The script asks napi to name the binary and the loader computes the name
    // independently. If they ever disagree the loader silently finds nothing.
    it.each(RELEASED)('matches for %s-%s', (platform, arch) => {
        expect(scriptBinaryName(platform, arch)).toBe(nativeBinaryName(platform, arch));
    });
});

describe('renderBindings', () => {
    const napiOutput = [
        '/* tslint:disable */',
        '/* eslint-disable */',
        '',
        '/* auto-generated by NAPI-RS */',
        '',
        '/** How to build (and later refresh) an index. */',
        'export interface BuildOptions {',
        '  includeIgnored?: boolean',
        '}',
        '',
    ].join('\n');

    it('keeps the declarations verbatim', () => {
        const rendered = renderBindings(napiOutput);
        expect(rendered).toContain('export interface BuildOptions {');
        expect(rendered).toContain('  includeIgnored?: boolean');
        // Doc comments carried over from the Rust survive.
        expect(rendered).toContain('/** How to build (and later refresh) an index. */');
    });

    it("replaces napi's header with one that says how to regenerate", () => {
        const rendered = renderBindings(napiOutput);
        expect(rendered).not.toContain('tslint:disable');
        expect(rendered).not.toContain('auto-generated by NAPI-RS');
        expect(rendered).toContain('Do not edit');
        expect(rendered).toContain('npm run build:native');
    });

    it('is a pure function of its input, so regeneration is deterministic', () => {
        expect(renderBindings(napiOutput)).toBe(renderBindings(napiOutput));
    });

    it('emits a lint pragma, since the body is generated', () => {
        expect(renderBindings(napiOutput).startsWith('/* eslint-disable */')).toBe(true);
    });
});

describe('the committed bindings', () => {
    const source = fs.readFileSync(path.join(PACKAGE_ROOT, BINDINGS_FILE), 'utf-8');

    it('lives where the build script writes it', () => {
        expect(BINDINGS_FILE).toBe(path.join('src', 'native-bindings.ts'));
    });

    it('is a .ts, not a .d.ts, so tsc emits it into dist for consumers', () => {
        // A .d.ts under src would leave dist/file-index.d.ts importing a module
        // that was never emitted, breaking every downstream package's types.
        expect(BINDINGS_FILE.endsWith('.d.ts')).toBe(false);
        expect(BINDINGS_FILE.endsWith('.ts')).toBe(true);
    });

    it('declares the whole file-index surface the capability re-exports', () => {
        expect(source).toContain('export interface BuildOptions');
        expect(source).toContain('export interface FileMatch');
        expect(source).toContain('export declare class FileIndex');
        expect(source).toContain('export declare function buildFileIndex');
    });

    it('declares the whole Notes-index surface the capability re-exports', () => {
        expect(source).toContain('export interface NotesIndexBuildOptions');
        expect(source).toContain('export interface NotesMatch');
        expect(source).toContain('export interface NotesSearchResult');
        expect(source).toContain('export interface NotesSearchResponse');
        expect(source).toContain('export declare class NotesIndex');
        expect(source).toContain('export declare function buildNotesIndex');
        expect(source).toContain('refresh(): Promise<void>');
        expect(source).toContain('refreshChanged(changedPaths: Array<string>): Promise<void>');
    });

    it('carries the UTF-16 offset contract through from the Rust', () => {
        // Highlighting depends on these being JavaScript string indices; the
        // Rust doc comment is the source of that claim.
        expect(source).toContain('UTF-16 offsets');
        expect(source).toContain('indices: Array<number>');
    });

    it('declares no runtime code, only types', () => {
        // Every exported value is `declare`d — the implementations come from
        // the binary, so this file must emit nothing executable.
        const runtimeExport = /^export (?!interface |type |declare )/m;
        expect(runtimeExport.test(source)).toBe(false);
    });

    it('is marked generated, so nobody hand-edits it', () => {
        expect(source).toContain('Do not edit');
        expect(source).toContain('npm run build:native');
    });
});

describe('the .mjs modules these tests import', () => {
    // Vitest inlines a project-local `.mjs` and, unlike a `.ts`, never runs it
    // through esbuild first. Vite skips a leading hashbang with `/^#!.*\n/`,
    // which is LF-only, so on a CRLF checkout — every Windows runner — the
    // regex misses and `#!` ends up inside the module wrapper. The suite then
    // dies at import with "SyntaxError: Invalid or unexpected token" before a
    // single test runs. `.gitattributes` pins these files to LF; this keeps
    // them hashbang-free whatever a clone's autocrlf happens to be.
    const testDir = path.join(PACKAGE_ROOT, 'test');
    const imported = fs
        .readdirSync(testDir)
        .filter(entry => entry.endsWith('.test.ts'))
        .flatMap(entry => [
            ...fs.readFileSync(path.join(testDir, entry), 'utf-8').matchAll(/from '(\.[^']*\.mjs)'/g),
        ])
        .map(match => path.resolve(testDir, match[1]));

    it('start with no hashbang, which Vite only strips from an LF file', () => {
        // Self-check: a scan that silently found nothing would pass forever.
        expect(imported).toContain(path.join(PACKAGE_ROOT, 'scripts', 'build-native.mjs'));
        for (const file of imported) {
            const relative = path.relative(PACKAGE_ROOT, file);
            expect(fs.readFileSync(file, 'utf-8').startsWith('#!'), `${relative} starts with a hashbang`).toBe(false);
        }
    });
});

describe('the built binary', () => {
    it('leaves no napi JS binding shim beside the package', () => {
        // `napi build` writes an index.js that resolves per-platform npm
        // packages. The loader resolves from disk, so the build script deletes
        // it; committing one would shadow nothing but confuse everything.
        expect(fs.existsSync(path.join(PACKAGE_ROOT, 'index.js'))).toBe(false);
    });

    it('is named what the loader looks for, when one has been built', () => {
        const expected = path.join(PACKAGE_ROOT, nativeBinaryName());
        const built = fs
            .readdirSync(PACKAGE_ROOT)
            .filter(entry => entry.endsWith('.node'))
            .map(entry => path.join(PACKAGE_ROOT, entry));
        if (built.length === 0) return; // nothing built here; CI's native job covers it
        // napi's own triple naming has to keep matching nativeTriple().
        expect(built, `expected a binary for ${nativeTriple()}`).toContain(expected);
    });
});
