/**
 * Compile the Rust addon and regenerate the TypeScript view of it.
 *
 * Produces two artifacts:
 *   - `coc-native.<platform>-<arch>[-abi].node`, next to the loader.
 *   - `src/native-bindings.ts`, the `#[napi]` type surface as TypeScript.
 *
 * `@napi-rs/cli` drives both, because the `.d.ts` is derived from the Rust
 * macros during compilation — a hand-written mirror of the `#[napi]` structs
 * has nothing keeping it in step with them.
 *
 * The CLI is used for the build, not for resolution: the loader finds binaries
 * on disk (locally built, then `prebuilt/`) rather than through napi-rs's
 * per-platform npm packages, and `npm run build` stays plain `tsc` over the
 * committed `native-bindings.ts` so the TypeScript build never needs cargo.
 *
 * No hashbang on purpose. `build-native.test.ts` imports these helpers, and
 * Vitest inlines a project-local `.mjs` without an esbuild pass — Vite only
 * skips a leading `#!` with the LF-only regex `/^#!.*\n/`. On a CRLF checkout
 * that misses and the `#!` lands inside the module wrapper, so the suite dies
 * at import. This file is run as `node scripts/build-native.mjs` and is not
 * executable, so the hashbang bought nothing.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cargoCwd = path.join('rust', 'napi');

/** Where the generated type surface is committed. */
export const BINDINGS_FILE = path.join('src', 'native-bindings.ts');

/** Platform/arch/abi triple used in the binary file name. */
export function nativeTriple(platform = process.platform, arch = process.arch) {
    if (platform === 'linux') return `linux-${arch}-gnu`;
    if (platform === 'win32') return `win32-${arch}-msvc`;
    return `${platform}-${arch}`;
}

/** File name the loader looks for. */
export function nativeBinaryName(platform = process.platform, arch = process.arch) {
    return `coc-native.${nativeTriple(platform, arch)}.node`;
}

/**
 * Wrap the CLI's output in a banner of our own.
 *
 * Their header is two lint pragmas; this one has to tell a reader why editing
 * the file is pointless and which command regenerates it.
 */
export function renderBindings(generated) {
    const body = generated
        .replace(/^\/\* tslint:disable \*\/\r?\n/m, '')
        .replace(/^\/\* eslint-disable \*\/\r?\n/m, '')
        .replace(/^\/\* auto-generated by NAPI-RS \*\/\r?\n/m, '')
        .trim();

    return `/* eslint-disable */
/**
 * The addon's type surface, generated from the \`#[napi]\` items in
 * \`rust/napi/src/\` by \`npm run build:native\`. Do not edit.
 *
 * Committed on purpose: \`npm run build\` is plain \`tsc\`, so the TypeScript
 * build must not need a Rust toolchain. CI regenerates this and fails on a
 * diff, which is what keeps it honest.
 *
 * Declarations only — this emits no runtime code. Capability modules re-export
 * these under the package's own names; the real implementations come from the
 * binary the loader resolves.
 */

${body}
`;
}

function main() {
    const profile = process.env.COC_NATIVE_PROFILE === 'debug' ? 'debug' : 'release';
    const target = process.env.CARGO_BUILD_TARGET;
    // The CLI resolves --dts against its own cwd and rejects absolute paths,
    // so this scratch file has to live inside the package.
    const dts = `.napi-dts-${process.pid}.d.ts`;

    // The type definitions are emitted by the proc macro *while compiling*, so
    // a cached crate produces none. Clean the thin wrapper — the logic crate,
    // which is the slow one, stays cached. The profile has to be named or this
    // cleans `debug` while the build below reads `release`.
    const clean = ['clean', '--manifest-path', path.join(cargoCwd, 'Cargo.toml'), '-p', 'coc-native'];
    if (profile === 'release') clean.push('--release');
    if (target) clean.push('--target', target);
    execFileSync('cargo', clean, { cwd: packageRoot, stdio: 'inherit' });

    const args = buildArgs({ profile, target, dts });

    const destination = path.join(packageRoot, nativeBinaryName());
    try {
        execFileSync(process.execPath, [napiCli(), ...args], { cwd: packageRoot, stdio: 'inherit' });

        // napi names the binary from `napi.binaryName` in package.json; the loader
        // computes the same name independently. Fail loudly if they diverge.
        if (!fs.existsSync(destination)) {
            throw new Error(
                `napi build did not produce ${path.relative(packageRoot, destination)}. ` +
                    `Found: ${fs.readdirSync(packageRoot).filter(f => f.endsWith('.node')).join(', ') || 'no .node files'}. ` +
                    'The `napi.name` field in package.json and nativeBinaryName() must agree.',
            );
        }

        const generated = fs.readFileSync(path.join(packageRoot, dts), 'utf-8');

        // A cached crate never reruns the proc macro and so emits no type defs.
        // Writing that emptiness over the committed file would quietly delete
        // the package's whole type surface, so refuse it.
        const missingExports = ['buildFileIndex', 'buildNotesIndex'].filter(
            exportName => !generated.includes(exportName),
        );
        if (missingExports.length > 0) {
            throw new Error(
                `napi build omitted required type definitions (${missingExports.join(', ')}) — ` +
                    'the crate may not have been recompiled, so the `#[napi]` macros never ran. ' +
                    `Try \`cargo clean --manifest-path ${cargoCwd}/Cargo.toml\`.`,
            );
        }

        fs.writeFileSync(path.join(packageRoot, BINDINGS_FILE), renderBindings(generated));
    } finally {
        // Byproducts, cleared even when the build or a check above threw —
        // otherwise a failed run leaves untracked files for someone to commit
        // by accident. `index.js` is the CLI's per-platform npm resolution
        // shim, which this package does not use; the loader reads from disk.
        for (const byproduct of ['index.js', dts]) {
            fs.rmSync(path.join(packageRoot, byproduct), { force: true });
        }
    }

    console.log(`native addon: built ${path.relative(packageRoot, destination)}`);
    console.log(`native addon: generated ${BINDINGS_FILE}`);
}

/**
 * Arguments for `napi build`.
 *
 * Split out so a test can pin the flag spelling: the CLI renamed several of
 * these in v3 (`--cargo-cwd` became `--manifest-path`, `--js false` became
 * `--no-js`) and an unknown flag is not always an error, it can just be
 * ignored and leave the build subtly wrong.
 */
export function buildArgs({ profile, target, dts }) {
    // v3 puts artifacts next to the crate unless told otherwise; everything
    // here — the loader, the byproduct cleanup — expects the package root.
    const args = [
        'build',
        '--manifest-path',
        path.join(cargoCwd, 'Cargo.toml'),
        '--output-dir',
        '.',
        '--platform',
        '--dts',
        dts,
    ];
    if (profile === 'release') args.push('--release');
    // `--target` makes the CLI also emit a JS binding shim that resolves
    // per-platform npm packages. The loader does that itself, from disk.
    if (target) args.push('--target', target, '--no-js');
    return args;
}

/** Resolve the napi CLI from wherever npm hoisted it. */
export function napiCli() {
    const candidates = [
        path.join(packageRoot, 'node_modules', '@napi-rs', 'cli', 'dist', 'cli.js'),
        path.join(packageRoot, '..', '..', 'node_modules', '@napi-rs', 'cli', 'dist', 'cli.js'),
    ];
    const found = candidates.find(candidate => fs.existsSync(candidate));
    if (!found) {
        throw new Error(
            `@napi-rs/cli not found (looked in ${candidates.join(', ')}). Run \`npm install\`.`,
        );
    }
    return found;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    main();
}
